import {corpusPreview} from './corpus.mjs?v=20261002-programmes2';
import {corpusAnalysis,assertionEvidence,evidenceView,evidenceRoles,analysisTerms,analysisCandidateVisible} from '../data/analysis.mjs?v=20261002-programmes2';
import {sourceView,owns,researchVisible} from '../data/research.mjs?v=20261002-programmes2';
import {readerResources,annotationView} from '../data/reader.mjs?v=20261002-programmes2';
import {wizard} from './wizard.mjs?v=20261002-programmes2';
import {hint} from './help.mjs?v=20261002-programmes2';
export const researchStates={open:'Відкрите питання',supported:'Обґрунтовано дослідником',contested:'Є суперечності',withdrawn:'Відкликано дослідником'};
export function analysisUI(c){
 const {st,actor,esc,pg,p,show,heading,panel,body,table,input,details,btn,act,link,dialog,dispatch,rev,sources,go}=c,t=st.tables,by=(k,id)=>t[k]?.find(x=>x.id===id);
 const options=(rows,current)=>rows.map(([id,title])=>`<option value="${esc(id)}" ${id===current?'selected':''}>${esc(title)}</option>`).join('');
 const sourceLink=x=>link(45,x.title,{id:x.id,revision:x.revision_id});
 const evTable=(ev,interactive=true)=>table(['Роль','Матеріал','Локатор / цитата','Пояснення'],ev.map(e=>{const src=evidenceView(st,actor,e);if(src&&interactive)act('evidence-'+e.id,()=>{if(e.annotation_revision_id){const n=by('entity_revision',e.annotation_revision_id).snapshot,v=annotationView(st,actor,n);dialog('Збережена нотатка',details([['Нотатка',n.body],['Уривок',v.quote],['Матеріал',v.target.label]]),()=>{},'Закрити');}else corpusPreview(c,e.target_entity_id?e:{target_entity_id:e.source_entity_id,target_revision_id:e.source_revision_id});});return src?[esc(evidenceRoles[e.role]||e.role),sourceLink(src)+(e.target_entity_id?'<p>Збережено точну версію матеріалу</p>':'')+(e.annotation_revision_id?'<p>Збережено нотатку</p>':''),esc([e.locator,e.quote_text].filter(Boolean).join(' · ')),esc(e.note)+(interactive?btn('Переглянути доказ','evidence-'+e.id):'')]:['—','Доказ недоступний','—','—'];}));
 function edit(a){
  const pool=[];for(const src of sources()){
   pool.push({label:src.title+' · опис',ref:{source_entity_id:src.id,source_revision_id:src.revision_id}});
   for(const r of readerResources(st,actor,src))pool.push({label:src.title+' · '+(by('vocabulary_term',by('entity_revision',r.view.revision_id)?.snapshot.kind_term_id)?.source_label||r.view.files?.map(f=>f.filename).join(', ')||r.view.label)+' · '+(by('entity_revision',r.view.revision_id)?.snapshot.language_tag||'')+' · версія '+r.view.revision_no,ref:r.item});
  }
  for(const n of t.annotation.filter(x=>owns(st,actor,x.id)&&annotationView(st,actor,x)))pool.push({label:'Нотатка: '+n.body,ref:{source_entity_id:n.source_entity_id||n.target_entity_id,source_revision_id:n.source_revision_id||n.target_revision_id,annotation_revision_id:rev(n.id),target_entity_id:n.target_entity_id,target_revision_id:n.target_revision_id,layer_entity_id:n.layer_entity_id,layer_revision_id:n.layer_revision_id}});
  const ev=assertionEvidence(st,a),terms=analysisTerms(st,actor,ev.map(e=>evidenceView(st,actor,e)).filter(Boolean));
  // Keep pinned older materials selectable without substituting their current revisions.
  const initial=ev.map(e=>{const ref=Object.fromEntries(['source_entity_id','source_revision_id','target_entity_id','target_revision_id','annotation_revision_id','layer_entity_id','layer_revision_id'].filter(k=>e[k]).map(k=>[k,e[k]]));pool.push({label:(evidenceView(st,actor,e)?.title||'Матеріал')+' · збережена версія',ref});return {...e,index:pool.length-1};});
  const relationFields='<details><summary>Сформулювати зв’язок понять</summary>'+[['relation_subject','Перше поняття зв’язку',a.analytical_relation?.subject_term_id],['relation_object','Пов’язане поняття',a.analytical_relation?.object_term_id]].map(([name,label,value])=>'<label>'+label+'<select name="'+name+'">'+options([['','Не обрано'],...terms.map(x=>[x.id,x.label])],value||'')+'</select></label>').join('')+'<p>Поясніть зв’язок у твердженні й підкріпіть його доказами.</p></details>';
  let d;d=wizard({dialog,esc},{title:'Уточнити твердження та докази',submit:'Зберегти нову версію',steps:[
   {title:'Висновок',body:input('statement_text','Твердження',a.statement_text,true,true)+`<label>Стан висновку<select name="research_status">${options(Object.entries(researchStates),a.research_status||'open')}</select></label>`+input('analysis_note','Пояснення висновку й альтернатив',a.analysis_note||'',true,true)+`<details><summary>Мотиви, жанри та поняття</summary>${terms.map(x=>`<label class="check-label"><input type="checkbox" name="terms" value="${x.id}" ${(a.analytical_terms||[]).includes(x.id)?'checked':''}>${esc(x.label)}</label>`).join('')||'<p>Немає доступних термінів.</p>'}</details>`+relationFields},
   {title:'Докази й контрдокази',body:'<div data-evidence-list></div><button type="button" class="button secondary" data-add-evidence>Додати доказ</button>'+hint('Зіставлення свідчень','Оберіть точний матеріал або нотатку, роль доказу, локатор і пояснення. Цитата має дослівно міститися в обраній версії. Зміни залишають попередню версію висновку в історії.')}
  ],summary:v=>details([['Твердження',v.statement_text],['Стан',researchStates[v.research_status]],['Доказів',String(d.querySelectorAll('[data-evidence-row]').length)]]),onSubmit:async v=>{
   const evidence=[...d.querySelectorAll('[data-evidence-row]')].map(el=>({...pool[Number(el.querySelector('[data-ref]').value)].ref,role:el.querySelector('[data-role]').value,locator:el.querySelector('[data-locator]').value,note:el.querySelector('[data-note]').value,quote_text:el.querySelector('[data-quote]').value}));
   await dispatch({type:'research.assertion.revise',id:a.id,expected_revision_id:rev(a.id),statement_text:v.statement_text,research_status:v.research_status,analysis_note:v.analysis_note,analytical_terms:[...new Set([...(v.terms||[]),v.relation_subject,v.relation_object].filter(Boolean))],analytical_relation:v.relation_subject||v.relation_object?{predicate:'related_to',subject_term_id:v.relation_subject,object_term_id:v.relation_object}:null,evidence});go(46,{id:a.id});
  }});
  const add=(e={index:0,role:'supports'})=>{const el=document.createElement('fieldset');el.dataset.evidenceRow='';el.innerHTML=`<legend>Доказ</legend><label>Матеріал доказу<select aria-label="Матеріал доказу" data-ref>${options(pool.map((x,i)=>[String(i),x.label]),String(e.index))}</select></label><label>Роль доказу<select aria-label="Роль доказу" data-role>${options(Object.entries(evidenceRoles),e.role)}</select></label><label>Місце в матеріалі<input aria-label="Місце в матеріалі" data-locator required value="${esc(e.locator||'')}"></label><label>Пояснення доказу<textarea aria-label="Пояснення доказу" data-note required>${esc(e.note||'')}</textarea></label><label>Дослівна цитата (необов’язково)<textarea aria-label="Дослівна цитата (необов’язково)" data-quote>${esc(e.quote_text||'')}</textarea></label><button type="button" class="button secondary" data-remove-evidence>Вилучити доказ</button>`;el.querySelector('[data-remove-evidence]').onclick=()=>el.remove();d.querySelector('[data-evidence-list]').append(el);};initial.forEach(add);d.querySelector('[data-add-evidence]').onclick=()=>add();
 }
 function assertion(a){
  act('analysis-edit',()=>edit(a));act('analysis-history',()=>{
   const history=t.entity_revision.filter(x=>x.entity_id===a.id).map(r=>{const ev=assertionEvidence(st,a,r.id),ok=ev.every(e=>evidenceView(st,actor,e))&&(!r.snapshot.annotation_revision_id||annotationView(st,actor,by('entity_revision',r.snapshot.annotation_revision_id).snapshot))&&(!r.snapshot.analytical_terms?.length||r.snapshot.analytical_terms.every(id=>analysisTerms(st,actor,ev.map(e=>evidenceView(st,actor,e)).filter(Boolean)).some(x=>x.id===id)));return `<section><h3>Версія ${r.revision_no}</h3>${ok?'<p>'+esc(r.snapshot.statement_text)+'</p>'+details([['Стан',researchStates[r.snapshot.research_status||'open']],['Пояснення',r.snapshot.analysis_note]])+evTable(ev,false):'<p>Матеріали цієї версії недоступні.</p>'}</section>`;}).join('');dialog('Історія твердження',history,()=>{},'Закрити');
  });
  const ev=assertionEvidence(st,a);return {actions:btn('Уточнити й додати докази','analysis-edit')+btn('Історія твердження','analysis-history'),content:panel('Висновок дослідника',body(details([['Стан',researchStates[a.research_status||'open']],['Пояснення й альтернативи',a.analysis_note],['Зв’язок понять',a.analytical_relation?[a.analytical_relation.subject_term_id,a.analytical_relation.object_term_id].map(id=>analysisTerms(st,actor,ev.map(e=>evidenceView(st,actor,e)).filter(Boolean)).find(x=>x.id===id)?.label).join(' ↔ '):null],['Мотиви, жанри, поняття',(a.analytical_terms||[]).map(id=>analysisTerms(st,actor,ev.map(e=>evidenceView(st,actor,e)).filter(Boolean)).find(x=>x.id===id)?.label).join(' · ')]])))+panel('Докази й контрдокази',evTable(ev))};
 }
 function review(row){
  const report=row.proposed_payload.report,run=by('process_run',row.process_run_id),history=t.review_decision.filter(x=>x.target_entity_id===row.id);
  const html=`<p class="source-text">${esc(row.proposed_payload.statement_text)}</p>`+details([['Метод',run.tool_name],['Версія методу',run.tool_version],['Час підрахунку',run.finished_at],['Основа','Точна версія корпусу; '+report.sources.length+' джерел']])+table(['Джерело','Версія'],report.sources.map(x=>[sourceLink(x),esc(x.revision_id)]))+hint('Як перевіряти','Підрахунок описує лише відібрану добірку. Невідомі дати й місця показані окремо; кілька місць або осіб одного джерела не є незалежними свідченнями. Рішення дослідника не означає прийняття архівом.')+(history.length?table(['Рішення','Пояснення'],history.map(x=>[esc(x.decision),esc(x.reason)])):'');
  if(!['pending','deferred'].includes(row.state))return dialog('Результат порівняння',html+(row.proposed_entity_id?link(46,'Відкрити створене твердження',{id:row.proposed_entity_id}):''),()=>{},'Закрити');
  const d=dialog('Перевірити результат порівняння',html+`<label>Рішення<select name="decision">${options([['defer','Відкласти'],['accept','Використати у твердженні'],['correct','Уточнити й використати'],['reject','Відхилити']],'defer')}</select></label>`+input('statement_text','Уточнений висновок',row.proposed_payload.statement_text,true)+input('reason','Пояснення рішення','',true,true)+'<label class="check-label"><input type="checkbox" name="confirm">Я звірив висновок із джерелами</label>',async fd=>{const r=await dispatch({type:'research.analysis.review',id:row.id,expected_revision_id:rev(row.id),decision:fd.get('decision'),statement_text:fd.get('statement_text'),reason:fd.get('reason'),confirm:fd.has('confirm')});if(r.proposed_entity_id)go(46,{id:r.proposed_entity_id});else go(44,{id:row.proposed_payload.corpus_id,revision:row.proposed_payload.corpus_revision_id,view:'analysis'});},'Зберегти рішення');return d;
 }
 function corpus(row,rid){
  const v=corpusAnalysis(st,actor,row.id,rid);if(!v)return false;
  const candidates=t.candidate.filter(x=>x.payload_schema_version==='research-analysis/1'&&owns(st,actor,x.id)&&x.proposed_payload.corpus_revision_id===rid),states={pending:'Очікує перевірки',deferred:'Відкладено',accepted:'Використано',corrected:'Уточнено й використано',rejected:'Відхилено'};
  act('run-analysis',()=>dialog('Підрахувати склад корпусу',details([['Джерел',String(v.rows.length)],['Метод','Кожна точна версія джерела враховується один раз.']])+'<p>Результат збережеться для вашої перевірки.</p>',async()=>{await dispatch({type:'research.analysis.run',id:row.id,corpus_revision_id:rid});go(44,{id:row.id,revision:rid,view:'analysis',compare:'candidates'});},'Підрахувати'));
  candidates.forEach(x=>act('candidate-'+x.id,()=>review(x)));
  const tab=p.get('compare')||'sources',filters=`<nav class="record-tabs" aria-label="Порівняння">${Object.entries({sources:'Варіанти та свідчення',distribution:'Місце й час',people:'Респонденти й репертуари',terms:'Мотиви й поняття',candidates:'Результати підрахунків'}).map(([key,label])=>`<a href="${pg(44,{role:'R04',id:row.id,revision:rid,view:'analysis',compare:key})}" ${tab===key?'aria-current="page"':''}>${label}</a>`).join('')}</nav>`;
  const dist=(name,rows)=>panel(name,table(['Значення','Джерел'],rows.map(x=>[esc(x.label),String(x.count)])));
  show(link(44,'← До складу корпусу',{id:row.id,revision:rid})+heading('Аналіз корпусу',row.title,'',btn('Підрахувати склад','run-analysis',!v.unavailable&&v.rows.length>=2))+body(`<p>Доступних версій джерел: ${v.rows.length}. Недоступних елементів: ${v.unavailable}.</p>`)+filters+
   (tab==='distribution'?dist('За місцем',v.places)+dist('За датою або періодом',v.periods)+body(hint('Межі підрахунку','Це розподіл джерел у добірці. Дата запису не означає дату виникнення традиції. Невідомі й закриті значення не прирівнюються до нуля. Діапазони дат не замінюються вигаданою точною датою.')):
    tab==='people'?dist('За респондентами / атрибуцією',v.people)+panel('Репертуари й контексти',table(['Особи','Джерело','Жанри й поняття','Контекст'],v.rows.map(x=>[esc(x.people.map(y=>y.label).join(' · ')||'Не зазначено / недоступно'),sourceLink(x),esc(x.terms.map(y=>y.label).join(' · ')||'Не класифіковано'),esc([x.places.map(y=>y.label).join(', '),x.date.label||x.date.from,x.text].filter(Boolean).join(' · '))]))):
    tab==='terms'?dist('Класифікації джерел',v.terms)+panel('Позначки та інтерпретації дослідника',table(['Джерело','Позначки','Нотатка'],v.rows.flatMap(x=>x.notes.map(n=>[sourceLink(x),esc(n.tags.map(y=>y.label).join(' · ')),esc(n.body)])),'Додайте позначки під час читання джерела.'))+body(hint('Зв’язки понять','Сформулюйте зв’язок у твердженні, виберіть мотиви, жанри чи поняття та додайте джерела за і проти. Дослідницька інтерпретація зберігається окремо від прийнятих класифікацій.')):
    tab==='candidates'?panel('Результати для перевірки',table(['Висновок','Стан','Дія'],candidates.map(x=>analysisCandidateVisible(st,actor,x)?[esc(x.proposed_payload.statement_text),states[x.state],btn('Перевірити результат','candidate-'+x.id)]:['Матеріали змінилися або недоступні','Потрібен новий підрахунок','—']),'Натисніть «Підрахувати склад», щоб отримати результат для перевірки.')):
    panel('Порівняння свідчень',table(['Джерело','Текст / опис','Контекст','Нотатки й альтернативи','Дія'],v.rows.map(x=>[sourceLink(x),x.materials.map(m=>'<p><strong>'+esc(m.label)+'</strong></p><p class="source-text">'+esc(m.text||'Текст відсутній')+'</p>').join(''),esc([x.group,x.places.map(y=>y.label).join(', '),x.date.label||x.date.from].filter(Boolean).join(' · ')),esc(x.notes.map(n=>n.body).join('\n')||'—'),link(45,'Читати й сформулювати висновок',{id:x.id,revision:x.revision_id,corpus:row.id,corpus_revision:rid})])))));
  return true;
 }
 return {assertion,corpus};
}
