import {catalogRoles,geoRoles,catalogSchemes,classificationFits} from '../data/catalog.mjs?v=20261002-wf15';
import {mediaPreview} from './session-media.mjs?v=20261002-wf15';
export function catalogPage(c){
 const {st,t,actor,scope,params,by,entity,rev,label,allowed,visible,writable,action,show,heading,panel,body,table,details,btn,button,pg,esc,input,select,opts,choices,dialog,form,dispatch,render,denied}=c;
 const id=params.get('material')||params.get('id'),e=entity(id),row=e&&by(e.entity_type,id);if(!row||!allowed(id)||e.entity_type==='document'&&row.kind==='received_consent'&&!allowed(id,'consent.read')||(scope&&e.archive_id!==scope)){denied();return;}
 const record=t.catalog_record?.find(x=>x.subject_entity_id===id),items=(t.catalog_record_item||[]).filter(x=>x.record_id===record?.id),a=e.archive_id,write=allowed(id,'catalog.write'),kind=e.entity_type;
 const cmd=type=>({type,id,expected_subject_revision_id:rev(id),expected_record_revision_id:record?rev(record.id):null});
 const ofType=type=>(t[type]||[]).filter(x=>entity(x.id)?.archive_id===a&&allowed(x.id)&&(type!=='document'||x.kind!=='received_consent'||allowed(x.id,'consent.read')));
 const termLabel=id=>t.term_label.find(l=>l.term_id===id&&l.kind==='preferred')?.label||by('vocabulary_term',id)?.code||'Термін';
 const evidenceFields=()=>select('evidence_source_id','Джерело підстави',opts([row,...['source_record','document','information_unit','physical_object'].flatMap(ofType).filter(x=>x.id!==id)],id,x=>x.title||x.external_key||x.original_filename||x.raw_text?.slice(0,60)||label(x.id)))+input('locator','Де саме в джерелі','Опис матеріалу','text',true)+input('reason','Підстава та пояснення','','textarea',true);
 const submit=(type,title,html,extra={},after)=>form(title,html,fd=>({...cmd(type),...extra,...Object.fromEntries(fd)}),after);
 const open=id=>location.href=pg(17,{role:'R02',material:id});
 const tabs=[['description','Опис'],['context','Люди й місця'],['classification','Класифікації'],['media','Медіа'],['review','Перевірка']],tab=params.get('section')||'description';
 const nav='<nav class="record-tabs catalog-tabs" aria-label="Розділи архівного опису">'+tabs.map(([code,title])=>`<a href="${pg(17,{role:params.get('role')||'R02',material:id,section:code})}" ${code===tab?'aria-current="page"':''}>${title}</a>`).join('')+'</nav>';
 const back=kind==='source_record'?pg(22,{id,role:'R02'}):pg(17,{role:'R02'});
 const head=()=>heading('Архівний опис',record?.title||row.title||row.original_filename||row.external_key||'Матеріал','',button('← '+(kind==='source_record'?'Джерельний запис':'Матеріали'),back,true))+nav;
 const verifiedLinks=(t.assertion||[]).filter(x=>x.scope==='archival'&&x.acceptance_state==='accepted').map(x=>{const relation=t.semantic_relation?.find(r=>r.assertion_id===x.id),identity=t.identity_resolution?.find(r=>r.assertion_id===x.id),other=relation?.object_entity_id||identity?.object_entity_id;return {claim:x,other,label:relation?termLabel(relation.relation_type_term_id):'Відповідність ресурсу'};}).filter(x=>x.other&&(x.claim.subject_entity_id===id||x.other===id));
 const sourceLink=item=>{const ev=by('evidence',item.evidence_id);return esc(ev?.note||'')+`<span class="sub">${esc(ev?.locator||'')}</span>`;};
 for(const item of items)action('catalog-remove-'+item.id,()=>submit('catalog.remove','Вилучити зв’язок',input('reason','Причина','','textarea',true),{item_id:item.id}));
 const remove=item=>btn('Вилучити','catalog-remove-'+item.id,write);
 if(tab==='description'){
  action('catalog-edit',()=>submit('catalog.describe','Уточнити архівний опис',input('title','Назва',record?.title||row.title||row.external_key||row.original_filename||'','text',true)+(kind==='information_unit'?select('unit_kind','Вид запису',choices([['recorded_work','Фольклорний твір'],['fei','Фольклорно-етнографічна інформація']],row.unit_kind))+input('incipit','Інципіт',row.incipit||'')+input('dialect_label_raw','Говір у джерелі',row.dialect_label_raw||''):'')+input('summary','Зміст',record?.summary||row.summary||row.context_notes||row.purpose||'','textarea')+input('source_label','Назва або позначення в джерелі',record?.source_label||'')+(kind==='collecting_session'?select('date_precision','Точність дати',choices([['unknown','Невідомо'],['exact','Точна дата'],['range','Період'],['approximate','Приблизно']],row.date_precision))+input('date_from','Початок дати',row.date_from||'','date')+input('date_to','Кінець дати',row.date_to||'','date')+input('date_label','Дата словами',row.date_label||''):'')+evidenceFields()));
  // The session revision is captured from the dialog choice before the atomic command.
  action('catalog-unit',()=>form('Виділити інформаційну одиницю',(kind!=='collecting_session'?select('session_id','Документований сеанс',opts(ofType('collecting_session'))):'')+select('unit_kind','Вид запису',choices([['recorded_work','Фольклорний твір'],['fei','Фольклорно-етнографічна інформація']],'recorded_work'))+input('title','Назва запису','','text',true)+input('summary','Зміст','','textarea')+evidenceFields(),fd=>{const v=Object.fromEntries(fd),session=kind==='collecting_session'?id:v.session_id;return {...cmd('catalog.unit'),...v,session_id:session,session_revision_id:rev(session)};},r=>open(r.unit_id)));
  action('catalog-session',()=>form('Зареєструвати документований сеанс',input('title','Назва сеансу','','text',true)+select('research_id','Дослідження','<option value="">Не встановлено</option>'+opts(ofType('field_research')))+input('date_label','Дата в джерелі')+input('summary','Обставини в джерелі','','textarea')+'<label class="check-label"><input type="checkbox" name="confirm" required>Джерело містить підтвердження цього сеансу</label>'+evidenceFields(),fd=>({...cmd('catalog.session'),...Object.fromEntries(fd),confirm:fd.has('confirm')}),r=>open(r.session_id)));
  action('catalog-place',()=>form('Розмістити в архіві',select('node_id','Розділ архіву',opts(ofType('archive_node'))),fd=>({type:'field.placement',id,node_id:fd.get('node_id')})));
  const units=kind==='collecting_session'?t.information_unit.filter(u=>u.session_id===id).sort((a,b)=>a.position-b.position):[];
  units.forEach(u=>[-1,1].forEach(dir=>action('catalog-order-'+u.id+'-'+dir,async()=>{await dispatch({...cmd('catalog.order'),unit_id:u.id,direction:dir});render();})));
  const placement=t.archival_placement.find(x=>x.entity_id===id&&x.placement_role==='primary'),origin=kind==='source_record'?row.raw_text:kind==='document'?row.body_text:null;
  show(head()+panel('Опис',body(details([['Зміст',record?.summary||row.summary||row.context_notes||row.purpose],['Позначення у джерелі',record?.source_label],...(kind==='information_unit'?[['Вид',row.unit_kind==='fei'?'Фольклорно-етнографічна інформація':'Фольклорний твір'],['Інципіт',row.incipit],['Говір',row.dialect_label_raw]]:[])])),btn('Уточнити опис','catalog-edit',write))+panel('Розміщення',body(placement?button(label(placement.archive_node_id),pg(16,{id:placement.archive_node_id,role:'R02'}),true):'<p>Ще не розміщено.</p>'),btn('Розмістити','catalog-place',write&&ofType('archive_node').length>0))+
   (kind==='information_unit'?panel('Сеанс',body(button(label(row.session_id),pg(17,{role:'R02',material:row.session_id}),true))):'')+
   (kind==='field_research'?panel('Сеанси дослідження',table(['Сеанс','Дія'],ofType('collecting_session').filter(x=>x.research_id===id).map(x=>[esc(x.title),button('Опрацювати опис',pg(17,{material:x.id,role:'R02'}),true)]))):'')+
   (kind==='collecting_session'?panel('Інформаційні одиниці',table(['Порядок','Запис','Вид','Дії'],units.map((u,i)=>[u.position,button(u.title,pg(17,{material:u.id,role:'R02'}),true),u.unit_kind==='fei'?'Етнографічна інформація':'Фольклорний твір',btn('Вище','catalog-order-'+u.id+'--1',write&&i>0)+' '+btn('Нижче','catalog-order-'+u.id+'-1',write&&i<units.length-1)])),btn('Додати одиницю','catalog-unit',write)):'')+
   (['source_record','document'].includes(kind)?panel('Документований контекст',body(`<div class="actions">${btn('Пов’язати з одиницею сеансу','catalog-unit',write&&ofType('collecting_session').length>0)}${btn('Зареєструвати сеанс','catalog-session',write)}</div>`)+table(['Створений опис','Дія'],items.filter(i=>['unit','session'].includes(i.kind)).map(i=>[esc(label(i.target_entity_id)),button('Відкрити опис',pg(17,{material:i.target_entity_id,role:'R02'}),true)]))):'')+
   (verifiedLinks.length?panel('Підтверджені зв’язки',table(['Зв’язок','Матеріал','Рішення'],verifiedLinks.map(x=>[esc(x.label),esc(label(x.claim.subject_entity_id===id?x.other:x.claim.subject_entity_id)),button('Переглянути рішення',pg(24,{id:x.claim.id,role:'R02'}),true)]))):'')+
   (origin?panel('Джерело',body('<details><summary>Переглянути незмінний оригінал</summary><pre class="source-text">'+esc(origin)+'</pre></details>')):'')+body('<details class="page-help catalog-help"><summary>Як уточнювати опис</summary><p>Зберігайте джерельні назви окремо від архівного формулювання. Якщо сеанс не підтверджений, описуйте наявний матеріал без створення сеансу. Класифікації та зв’язки передаються на окрему звірку.</p></details>'));
 }else if(tab==='context'){
  action('catalog-person',()=>submit('catalog.participant','Пов’язати особу',select('person_id','Особа',opts(ofType('person')))+select('role_code','Функція',choices(Object.entries(catalogRoles),'performer'))+evidenceFields()));
  const people=kind==='information_unit'?t.unit_participant.filter(p=>p.unit_id===id):[];people.forEach((p,i)=>action('catalog-person-remove-'+i,()=>submit('catalog.participant.remove','Вилучити участь',input('reason','Причина','','textarea',true),{person_id:p.person_id,role_code:p.role_code})));
  action('catalog-geo',()=>submit('catalog.geography','Пов’язати місце',select('place_id','Місце',opts(ofType('place')))+select('role_code','Роль місця',choices(Object.entries(geoRoles),'mentioned_place'))+input('source_label','Назва місця в джерелі')+input('dialect_label_raw','Говір у цьому контексті')+evidenceFields()));
  const geos=t.geographic_context.filter(g=>g.role_code!=='superseded'&&(g.subject_entity_id===id||kind==='information_unit'&&g.subject_entity_id===row.session_id));
  show(head()+(kind==='information_unit'?panel('Особи та функції',table(['Особа','Функція','Дія'],people.map((p,i)=>[esc(label(p.person_id)),esc(catalogRoles[p.role_code]||p.role_code),btn('Вилучити','catalog-person-remove-'+i,write)])),btn('Пов’язати особу','catalog-person',write)):'')+panel('Місця та ролі',table(['Місце','Роль','Назва у джерелі','Підстава','Дія'],geos.map(g=>{const i=items.find(i=>i.kind==='geography'&&i.target_entity_id===g.id);return [esc(label(g.place_id)),esc(geoRoles[g.role_code]||g.role_code)+(g.subject_entity_id!==id?'<span class="sub">Із контексту сеансу</span>':''),esc(g.source_label||'—'),i?sourceLink(i):'Джерельний контекст',i?remove(i):button('Відкрити контекст',pg(17,{material:g.subject_entity_id,role:'R02'}),true)];})),btn('Пов’язати місце','catalog-geo',write)));
 }else if(tab==='classification'){
  const schemes=t.vocabulary_scheme.filter(x=>x.status==='active'&&(!x.owner_archive_id||x.owner_archive_id===a)&&classificationFits(kind,row,x.d_code)),terms=t.vocabulary_term.filter(x=>x.status==='active'&&schemes.some(s=>s.id===x.scheme_id)),codes=Object.entries(catalogSchemes).filter(([code])=>classificationFits(kind,row,code));
  action('catalog-class',()=>submit('catalog.classify','Застосувати термін',select('term_id','Термін',opts(terms,'',x=>catalogSchemes[by('vocabulary_scheme',x.scheme_id).d_code]+' — '+termLabel(x.id)))+input('source_label','Формулювання у джерелі')+evidenceFields()));
  action('catalog-term',()=>submit('catalog.term','Додати термін до довідника',select('d_code','Довідник',choices(codes,codes[0]?.[0]))+input('label','Назва терміна','','text',true)+input('definition','Визначення','','textarea')+input('reason','Джерело або підстава терміна','','textarea',true)));
  show(head()+panel('Робочі класифікації',table(['Довідник','Термін','Формулювання у джерелі','Стан','Підстава','Дії'],items.filter(i=>i.kind==='classification').map(i=>{const k=t.classification.find(k=>k.assertion_id===i.target_entity_id);return [esc(catalogSchemes[by('vocabulary_scheme',k.scheme_id).d_code]),esc(termLabel(k.term_id)),esc(k.source_label||'—'),esc({draft:'На перевірці',accepted:'Прийнято',rejected:'Відхилено',superseded:'Замінено'}[by('assertion',i.target_entity_id).acceptance_state]),sourceLink(i),button('Розглянути',pg(24,{id:i.target_entity_id,role:'R02'}),true)+' '+remove(i)];})),btn('Застосувати термін','catalog-class',write&&terms.length>0))+body(`<div class="actions">${codes.length?btn('Додати термін','catalog-term',allowed(id,'vocabulary.write')&&write):''}</div><details class="page-help catalog-help"><summary>Класифікація і джерельне формулювання</summary><p>Доступні довідники залежать від виду матеріалу. Рубрики етнографічної інформації не застосовуються до фольклорного твору. Позначення джерела зберігається дослівно. Стан показує результат людської звірки; відхилені твердження зберігаються в історії.</p></details>`));
 }else if(tab==='media'){
  const reps=ofType('representation'),media=items.filter(i=>['media','segment'].includes(i.kind));
  if(kind==='information_unit')for(const link of t.unit_segment.filter(x=>x.unit_id===id))if(!media.some(i=>i.target_entity_id===link.segment_id))media.push({id:'existing-'+link.segment_id,kind:'segment',target_entity_id:link.segment_id,target_revision_id:rev(link.segment_id),inherited:true});
  action('catalog-media',()=>form('Пов’язати медіа',select('representation_id','Цифрове представлення',opts(reps,'',x=>label(x.asset_id)+' · '+x.representation_version))+(kind==='information_unit'?input('start_seconds','Початок фрагмента, секунд','','number')+input('end_seconds','Кінець фрагмента, секунд','','number'):'')+evidenceFields(),fd=>{const v=Object.fromEntries(fd);return {...cmd('catalog.media'),...v,representation_revision_id:rev(v.representation_id),start_ms:v.start_seconds?Math.round(Number(v.start_seconds)*1000):null,end_ms:v.end_seconds?Math.round(Number(v.end_seconds)*1000):null};}));
  action('catalog-representation',()=>form('Підготувати представлення файла',input('duration_seconds','Тривалість, секунд','','number')+evidenceFields(),fd=>({...cmd('catalog.representation'),...Object.fromEntries(fd),duration_ms:fd.get('duration_seconds')?Math.round(Number(fd.get('duration_seconds'))*1000):null})));
  for(const i of media)action('catalog-preview-'+i.id,()=>{const segment=i.kind==='segment'?by('entity_revision',i.target_revision_id).snapshot:null,repRev=by('entity_revision',segment?.representation_revision_id||i.target_revision_id),files=repRev.snapshot._relations?.representation_file||[];const d=dialog('Медіа матеріалу',files.map(x=>{const f=by('file_object',x.file_id);return body('<p>'+esc(f.original_filename)+'</p>'+mediaPreview(st.demo.file_contents[f.id],f.mime_type,esc));}).join('')+(segment?body(`<p>Фрагмент: ${segment.start_ms/1000}–${segment.end_ms/1000} с.</p>`):''),null,'Закрити');if(segment)d.querySelectorAll('audio,video').forEach(player=>{player.addEventListener('loadedmetadata',()=>player.currentTime=segment.start_ms/1000,{once:true});player.addEventListener('timeupdate',()=>{if(player.currentTime>=segment.end_ms/1000)player.pause();});});});
  show(head()+(kind==='file_object'?panel('Отриманий файл',body(mediaPreview(st.demo.file_contents[id],row.mime_type,esc)),btn('Підготувати представлення','catalog-representation',write&&allowed(id,'media.write'))):'')+panel('Представлення та фрагменти',table(['Медіа','Межі','Підстава','Дії'],media.map(i=>{const seg=i.kind==='segment'?by('media_segment',i.target_entity_id):null,rep=by('representation',seg?.representation_id||i.target_entity_id);return [esc(label(rep.asset_id)),seg?`${seg.start_ms/1000}–${seg.end_ms/1000} с`:'Повністю',i.inherited?'Наявний зв’язок':sourceLink(i),btn('Переглянути','catalog-preview-'+i.id)+' '+(i.inherited?'':remove(i))];})),btn('Пов’язати медіа','catalog-media',write&&reps.length>0)));
 }else if(tab==='review'){
  action('catalog-issue',()=>submit('catalog.issue','Створити завдання на уточнення',input('title','Що потрібно перевірити','','text',true)+evidenceFields()));
  action('catalog-submit',()=>submit('catalog.submit','Передати опис на звірку',input('reason','Що перевірити','','textarea',true)));
  const tasks=[...new Set([...items.filter(i=>i.kind==='issue').map(i=>i.target_entity_id),record?.review_task_id].filter(Boolean))];
  show(head()+panel('Черга перевірки',table(['Завдання','Стан','Дія'],tasks.map(id=>{const w=by('work_item',id);return [esc(w.title),esc({open:'Відкрите',assigned:'Призначено',in_progress:'У роботі',blocked:'Заблоковано',done:'Виконано',cancelled:'Скасовано'}[w.state]),button('Відкрити',pg(3,{id,role:'R02'}),true)];})),btn('Створити завдання','catalog-issue',write))+body(`<div class="actions">${(record?.review_task_id?button('Розглянути опис',pg(24,{id:record.id,role:'R02'}),true)+' ':'')+btn('Передати на звірку','catalog-submit',write&&!['in_review','verified'].includes(record?.state))}</div><details class="page-help catalog-help"><summary>Що відбувається після передання</summary><p>На перевірку передається точна версія опису. Подальше редагування потребує нового передання. Відкрийте розгляд опису, щоб перевірити класифікації й ухвалити рішення. Права на використання опрацьовуються окремо; заповнення опису не дозволяє публікацію.</p></details>`));
 }else denied();
}
