import {contactStates,contactExpired,contactSession} from '../data/contacts.mjs?v=20260928-one-user';
import {hint} from './help.mjs?v=20260928-one-user';
import {wizard} from './wizard.mjs?v=20260928-one-user';

export function contactsPage(c,r){
 const {st,t,actor,can,by,rev,label,visible,params,pg,button,panel,heading,esc,body,table,details,input,select,choices,opts,btn,form,action,show,tabs,dispatch,render,flash,dialog}=c;
 const help=(title,text)=>`<div class="field-control" style="min-height:24px"><small>${esc(title)}</small>${hint(title,text)}</div>`;
 const all=t.potential_respondent.filter(x=>x.research_id===r.id),write=can(st,actor,'contacts.write',r.id),fieldWrite=can(st,actor,'field.write',r.archive_id),tab=params.get('tab')||'contacts',q=(params.get('q')||'').toLocaleLowerCase('uk');
 const people=visible('person'),places=visible('place'),groups=t.work_group.filter(x=>x.research_id===r.id&&!t.entity.find(e=>e.id===x.id)?.retired_at);
 const url=(extra={})=>pg(6,{role:'R01',research:r.id,tab,q:params.get('q')||'',state:params.get('state')||'',place:params.get('place')||'',group:params.get('group')||'',...extra});
 const command=(type,row,v={})=>({type,id:row?.id,research_id:r.id,expected_revision_id:row?rev(row.id):undefined,...v});
 const privateValue=(row,kind)=>contactExpired(st,row)?'':t.respondent_contact.find(x=>x.respondent_id===row.id&&(x.contact_kind===kind||kind==='contact'&&x.contact_kind==='note'))?.contact_value||'';
 const status=x=>contactStates.find(k=>k[0]===x.state)?.[1]||x.state;
 const when=x=>x.planned_meeting_at?x.planned_meeting_at.replace('T',' ').replace('.000Z',' UTC'):'Без призначеного часу';
 const editContact=row=>form(row?'Контакт і зустріч':'Новий контакт',input('display_hint','Контактна підказка',row?.display_hint||'','text',true,'Лише відомості, потрібні для організації зустрічі. Телефон та адреси зберігайте в полі «Як зв’язатися».')+input('potential_topics','Можливі теми',row?.potential_topics||'','textarea')+select('place_id','Плановане місце','<option value="">Ще не визначено</option>'+opts(places,row?.place_id))+select('work_group_id','Відповідальна група','<option value="">Ще не призначено</option>'+opts(groups,row?.work_group_id,x=>x.name))+
  (row&&contactExpired(st,row)?body('<p>Строк зберігання минув. Способи зв’язку, нотатки та рекомендації приховані. Для продовження роботи перегляньте строк або очистіть ці дані.</p>'):input('contact_value','Як зв’язатися',row?privateValue(row,'contact'):'')+input('working_note','Робочі нотатки',row?privateValue(row,'working_note'):'','textarea',false,'Домовленості, результат спроби зв’язку, причина відмови. Ці нотатки не переносяться до біографії чи сеансу.'))+
  input('planned_meeting_at','Час зустрічі (UTC)',row?.planned_meeting_at?.slice(0,16)||'','datetime-local')+input('retention_until','Зберігати до',row?.retention_until||'','date')+select('state','Домовленість',choices(contactStates,row?.state||'planned'))+select('confirmed_person_id','Підтверджена особа','<option value="">Ще не пов’язано</option>'+opts(people,row?.confirmed_person_id),'Обирайте лише після підтвердження особи. Робоча підказка не створює особу автоматично.'),fd=>command('field.contact',row,Object.fromEntries(fd)));
 const schedule=row=>form('Домовленість про зустріч',body(details([['Контакт',row.display_hint],['Теми',row.potential_topics]]))+input('planned_meeting_at','Час зустрічі (UTC)',row.planned_meeting_at?.slice(0,16)||'','datetime-local')+select('state','Домовленість',choices(contactStates,row.state))+input('working_note','Результат домовленості',privateValue(row,'working_note'),'textarea')+body(help('Перенесення і відмова','Змініть час, щоб перенести зустріч. Порожній час означає, що дату ще не визначено. Відмова або неможливість зв’язатися прибирає зустріч із розкладу.')),fd=>command('field.contact',row,Object.fromEntries(fd)));
 const startSession=row=>{
  const expected=rev(row.id),researchRevision=rev(r.id);
  wizard({dialog,esc},{title:'Почати сеанс',submit:'Створити й відкрити сеанс',steps:[
   {title:'Підтвердження учасника',body:body(details([['Робочий контакт',row.display_hint]]))+select('person_id','Особа','<option value="">Створити підтверджену особу</option>'+opts(people,row.confirmed_person_id))+input('person_name','Ім’я підтвердженої особи')+`<label class="check-label"><input type="checkbox" name="identity_confirmed" value="yes" required>Особу учасника підтверджено</label>`+body(help('Робочі відомості','До особи потрапить лише вибране або явно введене ім’я. Нотатки, спосіб зв’язку й рекомендації залишаться в робочих контактах. Згоду потрібно отримати й задокументувати окремо.'))},
   {title:'Обставини сеансу',body:input('title','Назва сеансу','','text',true)+input('date_from','Дата сеансу',row.planned_meeting_at?.slice(0,10)||'','date')+input('location_description','Місце та умови','','textarea')+body(details([['Група',row.work_group_id?label(row.work_group_id):'Не призначено'],['Плановане місце',row.place_id?label(row.place_id):'Не визначено'],['Програма',r.programme_revision_id?'Поточна програма дослідження':'Не додана']]))+(row.place_id?`<label class="check-label"><input type="checkbox" name="place_confirmed" value="yes">Сеанс відбувається в цьому місці</label>`:'')}
  ],summary:v=>details([['Сеанс',v.title],['Особа',v.person_id?label(v.person_id):v.person_name],['Дата',v.date_from],['Місце',v.place_confirmed?.length?label(row.place_id):'Потребує уточнення'],['Згода','Потрібно задокументувати окремо']]),onSubmit:async v=>{const result=await dispatch(command('field.contact.session',row,{...v,identity_confirmed:!!v.identity_confirmed?.length,place_confirmed:!!v.place_confirmed?.length,expected_revision_id:expected,research_revision_id:researchRevision}));location.href=pg(8,{role:'R01',id:result.id});}});
 };
 const referralForm=(row,x,index)=>{
  const selected=x?.referrer_person_id?'person:'+x.referrer_person_id:x?.referrer_respondent_id?'contact:'+x.referrer_respondent_id:'note';
  const sources=[['note','Інше джерело — описати'],...people.map(p=>['person:'+p.id,'Особа: '+label(p.id)]),...all.filter(p=>p.id!==row.id&&!contactExpired(st,p)).map(p=>['contact:'+p.id,'Контакт: '+p.display_hint])];
  form(x?'Редагувати рекомендацію':'Додати рекомендацію',body(details([['Кого порадили',row.display_hint]]))+select('source','Хто порадив',choices(sources,selected))+input('referrer_note','Пояснення рекомендації',x?.referrer_note||'','textarea'),fd=>{const [kind,id]=fd.get('source').split(':');return command('field.contact.referral',row,{index,referrer_person_id:kind==='person'?id:null,referrer_respondent_id:kind==='contact'?id:null,referrer_note:fd.get('referrer_note')});});
 };
 action('add',()=>editContact(null));
 for(const row of all){
  action('view-'+row.id,()=>dialog(row.display_hint,body(details([['Можливі теми',row.potential_topics],['Місце',row.place_id?label(row.place_id):'Не визначено'],['Група',row.work_group_id?label(row.work_group_id):'Не призначено'],['Домовленість',status(row)],['Зустріч',when(row)],['Як зв’язатися',contactExpired(st,row)?'Приховано після строку зберігання':privateValue(row,'contact')],['Робочі нотатки',contactExpired(st,row)?'Приховано після строку зберігання':privateValue(row,'working_note')],['Зберігати до',row.retention_until]])),null,'Закрити'));

  action('edit-'+row.id,()=>editContact(row));action('schedule-'+row.id,()=>schedule(row));action('start-'+row.id,()=>startSession(row));action('ref-add-'+row.id,()=>referralForm(row));
  action('clear-'+row.id,()=>form('Очистити робочі дані',body(`<p>${esc(row.display_hint)}</p><p>Буде видалено способи зв’язку, робочі нотатки й отримані рекомендації цього контакту. Коротка підказка, стан та зв’язок із підтвердженою особою залишаться.</p>`),()=>command('field.contact.clear',row)));
 }
 const filters=`<form class="filters"><input type="hidden" name="role" value="R01"><input type="hidden" name="research" value="${r.id}"><input type="hidden" name="tab" value="${esc(tab)}">${input('q','Знайти контакт або тему',params.get('q')||'')}${select('state','Стан контакту',choices([['','Усі стани'],...contactStates],params.get('state')||''))}${select('place','Місце','<option value="">Усі місця</option>'+opts(places,params.get('place')))}${select('group','Група','<option value="">Усі групи</option>'+opts(groups,params.get('group'),x=>x.name))}<button class="button">Знайти</button>${button('Скинути фільтри',pg(6,{role:'R01',research:r.id,tab}),true)}</form>`;
 const rows=all.filter(x=>(x.display_hint+' '+(x.potential_topics||'')).toLocaleLowerCase('uk').includes(q)&&(!params.get('state')||x.state===params.get('state'))&&(!params.get('place')||x.place_id===params.get('place'))&&(!params.get('group')||x.work_group_id===params.get('group')));
 const next=row=>{const session=contactSession(st,row.id);return session?button('Відкрити сеанс',pg(8,{id:session.id,role:'R01'}),true):btn('Почати сеанс','start-'+row.id,write&&fieldWrite&&!contactExpired(st,row)&&['contacted','confirmed'].includes(row.state));};
 let content='';
 if(tab==='referrals'){
  const selected=params.get('contact')?all.find(x=>x.id===params.get('contact')):null;
  if(params.get('contact')&&!selected){show(heading(r.title,'Рекомендації','Контакт недоступний.'));return;}
  const targets=selected?[selected]:rows;
  content=panel(selected?'Хто порадив: '+selected.display_hint:'Ланцюг рекомендацій',table(['Кого порадили','Хто порадив','Пояснення','Дії'],targets.flatMap(row=>contactExpired(st,row)?[[esc(row.display_hint),'Приховано після строку зберігання','',btn('Переглянути строк','edit-'+row.id,write)]]:t.respondent_referral.filter(x=>x.respondent_id===row.id).map((x,i)=>{
   action('ref-edit-'+row.id+'-'+i,()=>referralForm(row,x,i));action('ref-remove-'+row.id+'-'+i,()=>form('Прибрати рекомендацію',body(`<p>${esc(row.display_hint)}</p>`),()=>command('field.contact.referral',row,{index:i,remove:true})));
   const source=all.find(p=>p.id===x.referrer_respondent_id);
   return [esc(row.display_hint),x.referrer_person_id?esc(label(x.referrer_person_id)):source?`<a href="${url({contact:source.id})}">${esc(source.display_hint)}</a>`:'Інше джерело',esc(x.referrer_note||'—'),btn('Редагувати','ref-edit-'+row.id+'-'+i,write)+' '+btn('Прибрати','ref-remove-'+row.id+'-'+i,write)];
  }))),selected?btn('Додати рекомендацію','ref-add-'+selected.id,write&&!contactExpired(st,selected)):'' )+(!selected?panel('Додати рекомендацію',table(['Контакт','Дія'],rows.map(row=>[esc(row.display_hint),btn('Хто порадив','ref-add-'+row.id,write&&!contactExpired(st,row))]))):button('Усі рекомендації',url({contact:''}),true));
 }else{
  const list=tab==='meetings'?rows.filter(x=>x.planned_meeting_at&&!['declined','unreachable'].includes(x.state)).sort((a,b)=>a.planned_meeting_at.localeCompare(b.planned_meeting_at)):tab==='expired'?rows.filter(x=>contactExpired(st,x)):rows;
  content=panel(tab==='meetings'?'Заплановані зустрічі':tab==='expired'?'Потребують перегляду строку':'Потенційні респонденти',table(['Контакт і теми','Місце та група','Домовленість','Дії'],list.map(row=>[
   `<button type="button" class="link-button" data-action="view-${row.id}">${esc(row.display_hint)}</button><span class="sub">${esc(row.potential_topics||'Теми ще не визначено')}</span>`+(row.confirmed_person_id?`<span class="sub">Підтверджена особа: ${esc(label(row.confirmed_person_id))}</span>`:''),esc(row.place_id?label(row.place_id):'Місце не визначено')+`<span class="sub">${esc(row.work_group_id?label(row.work_group_id):'Групу не призначено')}</span>`,esc(status(row))+`<span class="sub">${esc(when(row))}</span><span class="sub">${row.retention_until?'Зберігати до: '+esc(row.retention_until):'Строк не визначено'}${contactExpired(st,row)?' · Строк минув':''}</span>`,btn('Редагувати','edit-'+row.id,write)+' '+btn('Домовитися','schedule-'+row.id,write&&!contactExpired(st,row))+' '+button('Рекомендації',url({tab:'referrals',contact:row.id}),true)+' '+next(row)+(tab==='expired'?' '+btn('Очистити дані','clear-'+row.id,write):'')
  ])));
 }
 show(heading(r.title,'Контакти та зустрічі','',btn('Новий контакт','add',write))+tabs(r)+`<nav class="record-tabs field-control" style="padding-right:30px" aria-label="Робота з контактами">${[['contacts','Контакти'],['meetings','Зустрічі'],['referrals','Рекомендації'],['expired','Строк зберігання']].map(([k,v])=>`<a href="${url({tab:k,contact:''})}" ${tab===k?'aria-current="page"':''}>${v}</a>`).join('')}${hint('Підготовка респондентів','Оберіть місце з маршруту та групу, запишіть можливі теми й мінімальний спосіб зв’язку. Програма й готовність доступні на вкладці «Підготовка». Домовленість не означає підтвердження біографії або отримання згоди. Строки оцінюються за датою демонстраційних даних.')}</nav>`+filters+content);
}
