import {corpusTarget,corpusCandidates,corpusKey} from '../data/corpus.mjs?v=20261002-wf19';
import {corpusItems} from '../data/research.mjs?v=20261002-wf19';
import {wizard} from './wizard.mjs?v=20261002-wf19';
import {hint} from './help.mjs?v=20261002-wf19';
import {mediaPreview} from './session-media.mjs?v=20261002-wf19';
export function corpusWizard(c,selected=[],old=null){
 const {st,actor,p,esc,dialog,input,details,sources,rev,dispatch,go,queryContext}=c;
 const existing=old?corpusItems(st,rev(old.id)):[],pool=new Map();
 for(const x of [...existing,...corpusCandidates(st,actor,[...sources(),...selected])])if(!pool.has(corpusKey(x)))pool.set(corpusKey(x),x);
 const candidates=[...pool.values()],views=candidates.map(x=>corpusTarget(st,actor,x));
 const chosen=new Set(old?existing.map(corpusKey):selected.map(x=>corpusKey({target_entity_id:x.id,target_revision_id:x.revision_id})));
 let order=candidates.map((x,i)=>i).filter(i=>chosen.has(corpusKey(candidates[i])));
 const title=i=>views[i]?.title||'Елемент недоступний',items=v=>order.filter(i=>(v.items||[]).includes(String(i)));
 const d=wizard({dialog,esc},{title:old?'Нова версія корпусу':'Створити корпус',submit:old?'Зберегти версію':'Створити корпус',steps:[
  {title:'Питання та критерії',body:input('title','Назва корпусу',old?.title||'',false,true)+input('research_question','Дослідницьке питання',old?.research_question||p.get('question')||'',true,true)+input('inclusion_criteria','Критерії включення',old?.inclusion_criteria||'',true,true)+input('exclusion_criteria','Критерії виключення',old?.exclusion_criteria||'',true)+hint('Критерії виключення','Зазначте, які матеріали не підходять. Якщо окремих обмежень немає, так і напишіть.')},
  {title:'Оберіть склад',body:'<label>Знайти серед доступних елементів<input type="search" data-corpus-filter></label><div class="corpus-options">'+candidates.map((x,i)=>`<label class="check-label" data-corpus-option="${i}"><input type="checkbox" name="items" value="${i}" ${chosen.has(corpusKey(x))?'checked':''}>${esc(title(i))} · ${views[i]?'версія '+views[i].revision_no:'зніміть вибір, щоб продовжити'}${views[i]?.newer?' · попередня версія':''}<small>${esc((views[i]?.text||views[i]?.files.map(f=>f.filename).join(', ')||views[i]?.segments.map(s=>s.text).join(' ')||'').slice(0,120))}</small></label>`).join('')+'</div>'+hint('Що додати','Джерело — архівний опис. Текст і медіа — його представлення. Фрагмент — точний часовий інтервал. Можна вибрати їх окремо. Нові версії не замінюють вибрані автоматично.')},
  {title:'Групи та порядок',body:'<div data-corpus-arrange></div>'+input('method_notes','Методичні нотатки',old?.method_notes||'',true)+hint('Порядок і пояснення','Перемістіть елементи кнопками. Однакова назва групи об’єднує їх логічно; порядок задається окремо. Підставу добору можна зазначити для кожного елемента.')}
 ],summary:v=>details([['Назва',v.title],['Питання',v.research_question],['Включення',v.inclusion_criteria],['Виключення',v.exclusion_criteria]])+'<ol>'+items(v).map(i=>'<li>'+esc(title(i))+' · '+esc(v['group_'+i]||'Без групи')+(v['reason_'+i]?'<br>'+esc(v['reason_'+i]):'')+'</li>').join('')+'</ol>'+(!items(v).length?'<p role="alert">Оберіть хоча б один елемент.</p>':''),onSubmit:async v=>{
  const row=await dispatch({type:old?'research.corpus.revise':'research.corpus.create',id:old?.id,expected_revision_id:old?rev(old.id):null,title:v.title,research_question:v.research_question,inclusion_criteria:v.inclusion_criteria,exclusion_criteria:v.exclusion_criteria,method_notes:v.method_notes,saved_query_id:!old&&p.get('query')||null,selection_spec:queryContext(),items:items(v).map(i=>({...candidates[i],group_label:v['group_'+i],selection_reason:v['reason_'+i]}))});go(44,{id:row.id});
 }});
 const host=d.querySelector('[data-corpus-arrange]'),cards=candidates.map((x,i)=>{const el=document.createElement('section');el.className='panel corpus-card';el.innerHTML='<div class="panel-body"><h3>'+esc(title(i))+'</h3>'+input('group_'+i,'Група',views[i]?x.group_label||'':'')+input('reason_'+i,'Підстава добору',views[i]?x.selection_reason||'':'',true)+`<div class="actions"><button class="button secondary small" type="button" data-up>Вище</button><button class="button secondary small" type="button" data-down>Нижче</button></div></div>`;return el;});
 const arrange=()=>{order.forEach((i,pos)=>{host.append(cards[i]);cards[i].hidden=false;cards[i].querySelector('[data-up]').disabled=pos===0;cards[i].querySelector('[data-down]').disabled=pos===order.length-1;});cards.forEach((card,i)=>{if(!order.includes(i))card.remove();});};
 cards.forEach((card,i)=>{for(const [key,delta]of [['up',-1],['down',1]])card.querySelector('[data-'+key+']').onclick=()=>{const pos=order.indexOf(i),next=pos+delta;if(next<0||next>=order.length)return;[order[pos],order[next]]=[order[next],order[pos]];arrange();card.querySelector('[data-'+key+']').focus();};});
 d.querySelectorAll('[name="items"]').forEach(el=>el.onchange=()=>{const i=Number(el.value);order=el.checked?[...order,i]:order.filter(x=>x!==i);arrange();});
 d.querySelector('[data-corpus-filter]').oninput=e=>{const q=e.target.value.toLocaleLowerCase('uk');d.querySelectorAll('[data-corpus-option]').forEach(el=>el.hidden=!el.textContent.toLocaleLowerCase('uk').includes(q));};arrange();return d;
}
export function corpusPreview({st,actor,esc,dialog,table},item){
 const v=corpusTarget(st,actor,item);if(!v)throw Error('Цей елемент більше недоступний.');
 const d=dialog(v.title,'<p>Версія '+v.revision_no+'</p>'+(!v.text&&!v.files.length&&!v.segments.length?'<p>Немає дозволеного вмісту для перегляду.</p>':'')+(v.text?'<pre class="reading-text">'+esc(v.text)+'</pre>':'')+v.files.map(f=>mediaPreview(st.demo.file_contents[f.id]||'Файл відсутній у цьому браузері.',f.mime,esc)).join('')+(v.segments.length?table(['Інтервал','Текст'],v.segments.map(x=>[`<button class="button secondary" type="button" data-play="${x.id}">${x.start_ms/1000}–${x.end_ms/1000} с</button>`,esc(x.text)])):''),null,'Закрити');
 d.querySelectorAll('[data-play]').forEach(b=>b.onclick=()=>{const seg=v.segments.find(x=>x.id===b.dataset.play),idx=v.files.findLastIndex(f=>f.offset_ms!=null&&f.offset_ms<=seg.start_ms),player=d.querySelectorAll('audio,video')[idx];if(player){player.currentTime=(seg.start_ms-v.files[idx].offset_ms)/1000;player.ontimeupdate=()=>{if(player.currentTime>=(seg.end_ms-v.files[idx].offset_ms)/1000)player.pause();};player.play().catch(()=>{});}});return d;
}
