import {evidenceRoles} from '../data/analysis.mjs?v=20261002-programmes';
import {fileBytes} from '../data/binary.mjs?v=20261002-programmes';
import {datasetProjection,deliveredSource,materialCitationView,assertionResult} from '../data/delivery.mjs?v=20261002-programmes';
import {sourceView,corpusItems,owns,researchVisible,exportDownload} from '../data/research.mjs?v=20261002-programmes';
import {corpusTarget} from '../data/corpus.mjs?v=20261002-programmes';
import {annotationView} from '../data/reader.mjs?v=20261002-programmes';
import {feedbackView,feedbackTerms,feedbackFields,feedbackKinds} from '../data/feedback.mjs?v=20261002-programmes';
import {wizard} from './wizard.mjs?v=20261002-programmes';
import {hint} from './help.mjs?v=20261002-programmes';
const states={pending:'Очікує розгляду',accepted:'Прийнято',corrected:'Уточнено й прийнято',rejected:'Відхилено',deferred:'Відкладено',superseded:'Замінено новою пропозицією'};
export function deliveryUI(c){
 const {st,actor,esc,pg,show,heading,panel,body,table,input,details,btn,act,link,dialog,dispatch,rev,sources,go}=c,t=st.tables,own=type=>t[type].filter(x=>owns(st,actor,x.id)),by=(k,id)=>t[k]?.find(x=>x.id===id);
 const select=(name,label,rows,current='')=>`<label>${esc(label)}<select name="${name}">${rows.map(([id,title])=>`<option value="${esc(id)}" ${id===current?'selected':''}>${esc(title)}</option>`).join('')}</select></label>`;
 const check=(name,value,label,on=true)=>`<label class="check-label"><input type="checkbox" name="${name}" value="${esc(value)}" ${on?'checked':''}>${esc(label)}</label>`;
 function dataset(corpusId='',rid=null){
  const corpora=own('research_corpus'),resultPool=[...own('assertion').filter(x=>researchVisible(st,actor,x,'assertion')).map(x=>({id:x.id,revision_id:rev(x.id),label:'Твердження: '+x.statement_text})),...own('annotation').filter(x=>annotationView(st,actor,x)).map(x=>({id:x.id,revision_id:rev(x.id),label:'Нотатка: '+x.body}))];
  let d;const selection=v=>({corpus_id:v.corpus||null,corpus_revision_id:v.corpus?d.querySelector('[name=version]').value:null,positions:(v.positions||[]).map(Number),results:(v.results||[]).map(i=>({id:resultPool[Number(i)].id,revision_id:resultPool[Number(i)].revision_id})),include_files:!!v.include_files?.length});
  d=wizard({dialog,esc},{title:'Експортувати корпус і результати',submit:'Підготувати пакет',steps:[
   {title:'Корпус і версія',body:input('title','Назва експорту','Дослідницький пакет',false,true)+select('corpus','Корпус',[['','Лише результати'],...corpora.map(x=>[x.id,x.title])],corpusId)+select('version','Версія корпусу',[])},
   {title:'Склад пакета',body:'<fieldset><legend>Матеріали корпусу</legend><div data-export-items></div></fieldset><fieldset><legend>Результати</legend>'+resultPool.map((x,i)=>check('results',String(i),x.label,false)).join('')+'</fieldset>'+check('include_files','yes','Додати файли вибраних медіапредставлень',false)+hint('Що входить у пакет','Зберігаються точні версії, тексти, інтервали, результати та посилання на джерела. Повні файли додаються лише для вибраних медіапредставлень, а не автоматично для окремих уривків. Закриті матеріали потрібно виключити. Розмір пакета — до 8 МіБ.')}
  ],summary:v=>{const pr=datasetProjection(st,actor,selection(v));return pr?details([['Назва',v.title],['Елементів',String(pr.items.length)],['Результатів',String(pr.results.length)],['Файлів',String(pr.files.length)],['Формат','Переносний пакет JSON; файли включено в дані']]):'<p>Перевірте склад: потрібен хоча б один матеріал або результат із дозволом на цитування та завантаження.</p>';},onSubmit:async v=>{await dispatch({type:'research.dataset',title:v.title,selection:selection(v)});go(55);}});
  const items=()=>{const id=d.querySelector('[name=corpus]').value,r=d.querySelector('[name=version]').value;d.querySelector('[data-export-items]').innerHTML=(id?corpusItems(st,r):[]).map(i=>{const v=corpusTarget(st,actor,i),allowed=v&&deliveredSource(st,actor,v.source.id,v.source.revision_id);return allowed?check('positions',String(i.position),i.position+'. '+v.title):'<p>Елемент '+i.position+' недоступний для експорту.</p>';}).join('')||'<p>Оберіть результати нижче.</p>';};
  const versions=()=>{const id=d.querySelector('[name=corpus]').value,rows=t.entity_revision.filter(x=>x.entity_id===id);d.querySelector('[name=version]').innerHTML=rows.map(x=>`<option value="${x.id}" ${x.id===(rid||rev(id))?'selected':''}>Версія ${x.revision_no}</option>`).join('');items();};d.querySelector('[name=corpus]').onchange=()=>{rid=null;versions();};d.querySelector('[name=version]').onchange=items;versions();
 }
 function citations(corpusId,rid){
  const items=corpusItems(st,rid),pool=items.filter(i=>{const v=corpusTarget(st,actor,i);return v&&sourceView(st,actor,v.source.id,v.source.revision_id,'cite');});
  dialog('Цитування матеріалів корпусу',pool.map((i,n)=>check('items',String(n),corpusTarget(st,actor,i).title)).join('')||'<p>Немає дозволених матеріалів.</p>',async fd=>{await dispatch({type:'research.citations',items:fd.getAll('items').map(i=>pool[Number(i)])});go(55);},'Підготувати цитування');
 }
 function exports(){
  const rows=own('citation').filter(x=>researchVisible(st,actor,x,'citation')),files=[...own('bibliographic_export'),...t.handover.filter(x=>x.profile==='research-dataset/1'&&x.owner_account_id===actor)];
  rows.forEach(x=>act('copy-'+x.id,()=>dialog('Цитування',`<label>Текст цитування<textarea readonly rows="6">${esc(x.rendered_text)}</textarea></label>`,async()=>{if(!researchVisible(c.s?c.s():st,actor,x,'citation'))throw Error('Цитування недоступне.');await navigator.clipboard.writeText(x.rendered_text);},'Скопіювати')));
  act('dataset',()=>dataset());act('bibliography',()=>wizard({dialog,esc},{title:'Експортувати бібліографію',submit:'Підготувати файл',steps:[{title:'Цитування',body:rows.map(x=>check('citations',x.id,x.structured_data.title)).join('')},{title:'Формат',body:select('format','Формат',[['text','Текст (.txt)'],['csl_json','CSL JSON (.json)']])}],summary:v=>details([['Цитувань',String(v.citations?.length||0)],['Формат',v.format]]),onSubmit:async v=>{await dispatch({type:'research.export',citation_ids:v.citations||[],format:v.format});go(55);}}));
  for(const x of files){act('download-'+x.id,()=>{const f=exportDownload(c.s?c.s():st,actor,x.id);if(!f)throw Error('Доступ або склад матеріалів змінився. Підготуйте новий пакет.');const url=URL.createObjectURL(new Blob([f.content],{type:f.mime})),a=document.createElement('a');a.href=url;a.download=f.filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});if(x.format==='dataset_json'){act('repeat-'+x.id,()=>dataset(x.context_entity_id,x.context_revision_id));act('contents-'+x.id,()=>{const f=exportDownload(c.s?c.s():st,actor,x.id);if(!f)throw Error('Пакет недоступний.');const payload=JSON.parse(f.content),d=dialog('Склад пакета',table(['Матеріал','Версія'],payload.items.map(i=>[esc(i.source.title),esc(i.reference)]))+table(['Результат'],payload.results.map(r=>[esc(r.statement||r.body)]))+table(['Файл','Розмір','Дія'],payload.files.map((f,i)=>[esc(f.name),String(f.byte_size)+' байт','<button type="button" class="button secondary" data-package-file="'+i+'">Завантажити файл</button>'])),()=>{},'Закрити');d.querySelectorAll('[data-package-file]').forEach(b=>b.onclick=()=>{const current=exportDownload(c.s?c.s():st,actor,x.id);if(!current){d.close();return;}const file=JSON.parse(current.content).files[Number(b.dataset.packageFile)],url=URL.createObjectURL(new Blob([fileBytes(file.content)],{type:file.mime})),a=document.createElement('a');a.href=url;a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});});}}
  show(heading('Дослідницька робота','Цитування та експорт','',btn('Експортувати корпус і результати','dataset')+btn('Експортувати бібліографію','bibliography',!!rows.length))+panel('Мої цитування',table(['Матеріал','Версія','Дія'],rows.map(x=>{const src=x.style_code==='research-material/1'?materialCitationView(st,actor,x)?.source:sourceView(st,actor,x.target_entity_id,x.target_revision_id);return [link(45,x.structured_data.title,{id:src.id,revision:src.revision_id}),String(by('entity_revision',x.target_revision_id).revision_no),btn('Скопіювати','copy-'+x.id)];}),'Підготуйте цитування зі сторінки джерела або корпусу.'))+panel('Підготовлені файли',table(['Назва','Формат','Стан','Дія'],files.map(x=>{const allowed=!!exportDownload(st,actor,x.id);return [esc(x.title||'Бібліографія'),x.format==='dataset_json'?'Корпус і результати (JSON)':x.format==='text'?'Текст':'CSL JSON',allowed?'Готово':'Доступ або матеріали змінилися','<div class="public-actions">'+btn('Завантажити','download-'+x.id,allowed)+(x.format==='dataset_json'?btn('Переглянути склад','contents-'+x.id,allowed)+btn('Підготувати знову','repeat-'+x.id):'')+'</div>'];})))+body(hint('Права й посилання','Посилання фіксують точну версію. Права перевіряються знову перед копіюванням і завантаженням. Уже завантажений файл залишається у вас; зміна доступу блокує наступне завантаження.')));
 }
 function propose(a,old=null){
  const src=sourceView(st,actor,a.subject_entity_id);if(!src)throw Error('Поточна версія джерела недоступна.');const relation=(t.semantic_relation||[]).find(x=>x.assertion_id===a.id),payload=old?.proposed_payload||(relation?{operation:'relation',object_entity_id:relation.object_entity_id,predicate:by('vocabulary_term',relation.relation_type_term_id)?.code,rationale:a.statement_text}:null),terms=feedbackTerms(st,src.id),others=sources().filter(x=>x.id!==src.id&&x.archive_id===src.archive_id);
  const fields=feedbackFields[src.type],kind=payload?.operation||'description';let d;
  d=wizard({dialog,esc},{title:old?'Доопрацювати пропозицію':'Подати пропозицію архіву',submit:'Подати пропозицію',steps:[
   {title:'Предмет пропозиції',body:details([['Джерело',src.title],['Поточна версія',String(src.revision_no)],['Твердження',a.statement_text]])+select('operation','Вид пропозиції',Object.entries(feedbackKinds),kind)+'<fieldset data-proposal-kind="description">'+select('field','Поле опису',Object.entries(fields),payload?.field)+input('value','Запропоноване значення',payload?.value||'',true)+'</fieldset><fieldset data-proposal-kind="classification">'+select('term_id','Термін',terms.map(x=>[x.id,x.label]),payload?.term_id)+'</fieldset><fieldset data-proposal-kind="relation">'+select('predicate','Вид зв’язку',[['related_to','Пов’язано з'],['variant_of','Варіант виконання']],payload?.predicate)+select('object_id','Інше джерело',others.map(x=>[x.id,x.title]),payload?.object_entity_id)+'</fieldset>'},
   {title:'Докази й обґрунтування',body:input('rationale','Чому потрібна зміна',payload?.rationale||'',true,true)+table(['Роль','Джерело','Локатор','Підстава'],(assertionResult(st,actor,a.id,rev(a.id))?.evidence||[]).map(e=>[esc(evidenceRoles[e.role]||e.role),esc(e.source.title),esc(e.locator),esc(e.note)]))+hint('Передання','До пропозиції входить ця версія твердження та її докази. Подання не змінює архів. Рішення ухвалюється в черзі архівіста.')}
  ],summary:v=>details([['Вид',feedbackKinds[v.operation]],['Пропозиція',v.operation==='description'?v.value:v.operation==='classification'?terms.find(x=>x.id===v.term_id)?.label:others.find(x=>x.id===v.object_id)?.title],['Обґрунтування',v.rationale]]),onSubmit:async v=>{const other=others.find(x=>x.id===v.object_id);await dispatch({type:'research.feedback',assertion_id:a.id,assertion_revision_id:rev(a.id),base_revision_id:src.revision_id,replaces_id:old?.id,expected_revision_id:old?rev(old.id):null,payload:{operation:v.operation,field:v.field,value:v.value,term_id:v.term_id,predicate:v.predicate,object_entity_id:other?.id,object_revision_id:other?.revision_id,rationale:v.rationale}});go(47);}});
  // Wizard values must retain inactive fields but those fields must not block validation.
  const update=()=>d.querySelectorAll('[data-proposal-kind]').forEach(el=>{el.hidden=el.dataset.proposalKind!==d.querySelector('[name=operation]').value;});d.querySelector('[name=operation]').onchange=update;update();
 }
 function proposals(){
  const rows=own('candidate').filter(x=>x.payload_schema_version==='research-feedback/1');for(const x of rows){const v=feedbackView(st,actor,x.id);act('proposal-'+x.id,()=>dialog('Пропозиція архіву',details([['Стан',states[v.state]],['Пропозиція',v.proposed_payload.description],['Обґрунтування',v.proposed_payload.rationale]])+table(['Рішення','Пояснення'],v.decisions.map(d=>[esc({accept:'Прийнято',correct:'Виправлено',reject:'Відхилено',defer:'Відкладено'}[d.decision]),esc(d.reason)]))+(v.applications.length?'<p>Зміна застосована до архіву. Показ матеріалу потребує перевірки прав.</p>':'')+(v.reviewer?`<a href="${pg(24,{role:'R02',id:x.id})}">Відкрити розгляд архівіста</a>`:''),()=>{},'Закрити'));
   if(['pending','deferred','rejected'].includes(x.state)&&v.readable){const basis=x.proposed_payload.basis,a=by('assertion',basis.id);act('revise-'+x.id,()=>propose(a,x));}
  }
  const legacy=own('candidate').filter(x=>x.kind==='change_proposal'&&x.payload_schema_version==='research-proposal-1');for(const x of legacy)act('legacy-'+x.id,()=>dialog('Раніше подана пропозиція',details([['Стан',states[x.state]],['Пропозиція',researchVisible(st,actor,x,'candidate')?x.proposed_payload.description:'Матеріали недоступні']])+table(['Рішення','Пояснення'],t.review_decision.filter(d=>d.target_entity_id===x.id).map(d=>[esc(d.decision),esc(d.reason)])),()=>{},'Закрити'));show(heading('Дослідницька робота','Мої пропозиції','',link(46,'До тверджень'))+panel('Пропозиції архіву',table(['Пропозиція','Стан','Дії'],rows.map(x=>{const v=feedbackView(st,actor,x.id);return [esc(v.proposed_payload.description),states[x.state],btn('Переглянути','proposal-'+x.id)+(['pending','deferred','rejected'].includes(x.state)&&v.readable?btn('Доопрацювати','revise-'+x.id):'')];}),'Подайте пропозицію з дослідницького твердження.'))+(legacy.length?panel('Раніше подані пропозиції',table(['Пропозиція','Стан','Дія'],legacy.map(x=>[researchVisible(st,actor,x,'candidate')?esc(x.proposed_payload.description):'Матеріали недоступні',states[x.state],btn('Переглянути','legacy-'+x.id)]))):''));
 }
 return {dataset,citations,exports,propose,proposals};
}
export function feedbackReviewUI(c,id){
 const {st,actor,esc,pg,show,heading,panel,body,table,details,btn,action,link,dialog,dispatch,render,denied,input,area,select}=c,v=feedbackView(st,actor,id);if(!v?.reviewer)return denied();const p=v.proposed_payload;
 for(const decision of ['accept','correct','reject','defer'])action('feedback-'+decision,()=>{
  const apply=['accept','correct'].includes(decision),correct=decision==='correct',terms=feedbackTerms(st,v.source_id),others=st.tables.entity.filter(x=>x.archive_id===v.archive_id&&['information_unit','document','physical_object'].includes(x.entity_type)&&x.id!==v.source_id).map(x=>({id:x.id,revision_id:x.current_revision_id,title:st.tables[x.entity_type].find(y=>y.id===x.id)?.title||'Матеріал'}));
  dialog('Рішення щодо пропозиції',details([['Пропозиція',p.description]])+(correct?(p.operation==='description'?area('value','Виправлене значення',p.value):p.operation==='classification'?select('term_id','Виправлений термін',terms.map(x=>[x.id,x.label]),p.term_id):select('object_id','Виправлена ціль зв’язку',others.map(x=>[x.id,x.title]),p.object_entity_id)):'')+area('reason','Обґрунтування рішення')+(apply?'<label class="check-label"><input type="checkbox" name="confirm">Я звірив пропозицію та всі докази</label>':''),async fd=>{const other=others.find(x=>x.id===fd.get('object_id'));await dispatch({type:'archive.feedback.review',id,expected_revision_id:v.revision_id,decision,reason:fd.get('reason'),confirm:fd.has('confirm'),correction:correct?{...(p.operation==='description'?{value:fd.get('value')}:p.operation==='classification'?{term_id:fd.get('term_id')}:{object_entity_id:other?.id,object_revision_id:other?.revision_id})}:null});render();},'Зберегти рішення');
 });
 const active=['pending','deferred'].includes(v.state);show(link(23,'← Черга перевірки')+heading('Архівіст','Пропозиція дослідника','',active?btn('Прийняти','feedback-accept',v.readable&&!v.stale)+btn('Виправити й прийняти','feedback-correct',v.readable&&!v.stale)+btn('Відхилити','feedback-reject')+btn('Відкласти','feedback-defer'):'')+body(details([['Стан',states[v.state]]]))+(v.stale?body('<p>Основа змінилася. Потрібна нова пропозиція за поточною версією.</p>'):'')+(v.readable?panel('Пропозиція й основа',body(details([['Вид',feedbackKinds[p.operation]],['У поточному описі',p.operation==='description'?v.current[p.field]:null],['Пропонується',p.description],['Обґрунтування',p.rationale],['Дослідницьке твердження',p.basis.statement]])))+panel('Подані докази й контрдокази',table(['Роль','Джерело','Локатор','Цитата','Пояснення'],p.basis.evidence.map(e=>[esc(evidenceRoles[e.role]||e.role),'<a href="'+pg(45,{role:'R04',id:e.source.id,revision:e.source.revision_id})+'">'+esc(e.source.title)+'</a>',esc(e.locator),esc(e.quote||e.annotation?.quote||''),esc(e.note)]))):body('<p>Подані матеріали зараз недоступні.</p>'))+panel('Історія рішень',table(['Рішення','Пояснення'],v.decisions.map(d=>[esc({accept:'Прийнято',correct:'Виправлено',reject:'Відхилено',defer:'Відкладено'}[d.decision]),esc(d.reason)]))));
}
