import {captureFormats} from '../data/digitization.mjs?v=20261002-wf16';
import {plannedOutputs} from '../data/capture-preparation.mjs?v=20261002-wf16';
import {MAX_MEDIA_BYTES} from '../data/binary.mjs?v=20261002-wf16';
import {encode,download} from './session-media.mjs?v=20261002-wf16';
import {wizard} from './wizard.mjs?v=20261002-wf16';
export function digitizationDialog(ctx,job,previous){
 const {st,t,rev,label,esc,dialog,input,select,options,choices,details,dispatch,done}=ctx;
 const profile=job.specification.capture_profile,parts=plannedOutputs(st,job.capture_plan_revision_id);let files=[],stream=null,recorder=null,chunks=[],timer=null,closed=false,pending=false,blob=null,previewUrl=null,recordingMetadata=null;
 const people=t.person.filter(x=>t.entity.find(e=>e.id===x.id)?.archive_id===t.entity.find(e=>e.id===job.work_item_id)?.archive_id);
 const stamp=()=>new Date().toISOString().slice(0,16);
 const d=wizard({dialog,esc},{title:previous?'Повторити фіксацію':'Зафіксувати матеріал',submit:'Зберегти фіксацію',steps:[
  {title:'Обставини та обладнання',body:details([['Носій',label(job.physical_object_id)],['План',profile.kind==='image'?'Зображення':profile.kind==='audio'?'Аудіо':'Відео']])+select('operator_person_id','Оператор',options(people,previous?.operator_person_id||people[0]?.id))+input('occurred_at','Дата і час фіксації (UTC)',stamp(),'datetime-local',true)+input('device_make','Виробник пристрою',previous?.device_make||'')+input('device_model','Пристрій',profile.device,'text',true)+input('device_serial','Серійний номер',previous?.device_serial||'')+input('software_name','Програма',(previous?.settings?.contract==='digitization/1'?previous.software_name:'')||'','text',true)+input('software_version','Версія програми',previous?.software_version||'','text',true)+input('actual_settings','Фактичні параметри','','textarea',true,'Запишіть параметри, використані під час фіксації. Запланований профіль зберігається окремо; відповідність перевіряється на етапі контролю якості.')+select('role','Роль результату',choices({received_original:'Отриманий оригінал',preservation_master:'Майстер збереження'},'preservation_master'))+(previous?input('recapture_reason','Причина повторної фіксації','','textarea',true):'')},
  {title:'Файли та порядок частин',body:'<label>Отримані файли<input type="file" name="capture_files" multiple accept="'+Object.keys(captureFormats).filter(x=>x.startsWith(profile.kind+'/')).join(',')+'"></label><p>До 2 МБ разом за одне збереження.</p><div data-capture-files></div><details><summary>Записати з камери або мікрофона</summary><p>Короткий запис до 30 секунд. Фактичний формат браузера може відрізнятися від плану; зазначте відхилення.</p><div class="actions"><button class="button secondary" type="button" data-record="start">Увімкнути '+(profile.kind==='audio'?'мікрофон':'камеру')+'</button><button class="button secondary" type="button" data-record="stop" disabled>'+(profile.kind==='image'?'Зробити фото':'Зупинити запис')+'</button><button class="button secondary" type="button" data-record="download" disabled>Завантажити запис</button></div><div data-record-preview></div><p role="status" data-record-status></p></details>'},
  {title:'Відхилення та підтвердження',body:input('deviation_reason','Пояснення відхилень або пропусків','','textarea',false,'Обов’язкове, якщо формат, пристрій або комплектність відрізняються від плану.')+input('technical_incidents','Технічні проблеми','','textarea')+'<label class="check-label"><input type="checkbox" name="confirm" required>Я перевірив походження файлів, порядок і фактичні параметри</label>'}
 ],summary:v=>details([['Оператор',label(v.operator_person_id)],['Пристрій',v.device_model],['Програма',v.software_name+' '+v.software_version],['Файли',read().sort((a,b)=>a.position-b.position).map(f=>`${f.position}. ${parts[f.position-1]?.label} — ${f.filename}`).join('\n')],['Відхилення',v.deviation_reason||'Не зазначено'],['Проблеми',v.technical_incidents||'Не зазначено']]),onSubmit:async v=>{
  if(pending||stream)throw Error('Завершіть запис і дочекайтеся підготовки файла.');
  await dispatch({type:'media.capture',job_id:job.work_item_id,expected_revision_id:rev(job.work_item_id),previous_capture_id:previous?.id,expected_previous_revision_id:previous?rev(previous.id):null,...v,occurred_at:v.occurred_at+'Z',method:files.some(f=>f.live)?'browser':'import',files:read(),confirm:v.confirm.length>0});done('Фіксацію збережено. Результат очікує перевірки.');
 }});
 const q=x=>d.querySelector('[data-record="'+x+'"]'),status=message=>d.querySelector('[data-record-status]').textContent=message;
 function read(){return files.map((f,i)=>({...f,position:Number(d.querySelector(`[data-file-position="${i}"]`).value),source_path:d.querySelector(`[data-file-path="${i}"]`).value}));}
 function draw(){d.querySelector('[data-capture-files]').innerHTML=files.map((f,i)=>`<fieldset><legend>${esc(f.filename)}</legend><label>Частина для файла ${i+1}<select data-file-position="${i}">${parts.map((p,n)=>`<option value="${n+1}" ${f.position===n+1?'selected':''}>${n+1}. ${esc(p.label)}</option>`).join('')}</select></label><label>Початковий шлях файла ${i+1}<input data-file-path="${i}" value="${esc(f.source_path||'')}"></label><p>${esc(f.mime_type)}</p><button type="button" class="button secondary" data-file-remove="${i}">Прибрати файл ${i+1}</button></fieldset>`).join('');d.querySelectorAll('[data-file-remove]').forEach(el=>el.onclick=()=>{files=read();files.splice(Number(el.dataset.fileRemove),1);draw();});}
 async function add(blobs,live=false){files=read();if(files.length+blobs.length>parts.length)throw Error('Файлів більше, ніж частин плану.');if(files.reduce((n,f)=>n+f.size,0)+blobs.reduce((n,f)=>n+f.size,0)>MAX_MEDIA_BYTES)throw Error('Додайте до 2 МБ файлів разом.');const additions=[];for(const b of blobs){const suffix=b.name?.split('.').at(-1)?.toLowerCase(),mime=b.type.split(';')[0]||({tif:'image/tiff',tiff:'image/tiff',wav:'audio/wav',flac:'audio/flac',mkv:'video/x-matroska',mov:'video/quicktime'})[suffix];if(!captureFormats[mime]||!mime.startsWith(profile.kind+'/'))throw Error('Формат файла не відповідає виду фіксації.');additions.push({content:await encode(b),mime_type:mime,filename:b.name||'Запис-'+Date.now()+(mime==='image/png'?'.png':mime.includes('mp4')?'.mp4':'.webm'),size:b.size,live,recording_metadata:live?recordingMetadata:null});}for(const f of additions){f.position=parts.findIndex((_,i)=>!files.some(x=>x.position===i+1))+1;files.push(f);}draw();}
 d.querySelector('[name=capture_files]').onchange=async e=>{pending=true;d.querySelector('[type=submit]').disabled=true;try{await add([...e.target.files]);status('Файли додано до чернетки. Звірте частини плану.');}catch(error){status(error.message);}finally{pending=false;d.querySelector('[type=submit]').disabled=false;e.target.value='';}};
 const release=()=>{clearTimeout(timer);stream?.getTracks().forEach(t=>t.stop());stream=null;};
 const cleanup=()=>{closed=true;if(recorder?.state&&recorder.state!=='inactive')recorder.stop();release();if(previewUrl)URL.revokeObjectURL(previewUrl);window.removeEventListener('pagehide',cleanup);};d.addEventListener('close',cleanup);d.addEventListener('cancel',cleanup);window.addEventListener('pagehide',cleanup);
 async function finish(){release();if(closed)return;pending=true;d.querySelector('[type=submit]').disabled=true;try{if(previewUrl)URL.revokeObjectURL(previewUrl);previewUrl=URL.createObjectURL(blob);d.querySelector('[data-record-preview]').innerHTML=profile.kind==='image'?`<img src="${previewUrl}" alt="Зафіксований носій" style="max-width:100%;max-height:300px">`:`<${profile.kind} controls src="${previewUrl}" style="max-width:100%;max-height:300px"></${profile.kind}>`;q('download').disabled=false;await add([blob],true);status('Запис додано до чернетки. Звірте частину плану.');}catch(error){status(error.message+' Запис можна завантажити.');}finally{pending=false;d.querySelector('[type=submit]').disabled=false;q('stop').disabled=true;q('start').disabled=false;}}
 const stop=()=>{if(recorder?.state==='recording'){pending=true;recorder.stop();release();}};
 q('start').onclick=async()=>{if(pending||stream)return;pending=true;q('start').disabled=true;try{if(!navigator.mediaDevices?.getUserMedia)throw Error('Запис недоступний. Додайте файл із пристрою.');stream=await navigator.mediaDevices.getUserMedia({audio:profile.kind!=='image',video:profile.kind!=='audio'});if(closed){release();return;}recordingMetadata={software:navigator.userAgent,tracks:stream.getTracks().map(track=>({kind:track.kind,label:track.label,settings:Object.fromEntries(Object.entries(track.getSettings()).filter(([k])=>['width','height','frameRate','sampleRate','sampleSize','channelCount','echoCancellation','noiseSuppression','autoGainControl'].includes(k)))}))};if(profile.kind==='image'){const v=document.createElement('video');v.muted=true;v.autoplay=true;v.playsInline=true;v.style.maxWidth='100%';v.srcObject=stream;d.querySelector('[data-record-preview]').replaceChildren(v);await v.play();}else{const types=profile.kind==='audio'?['audio/webm;codecs=opus','audio/mp4']:['video/webm;codecs=vp8,opus','video/mp4'],mime=types.find(x=>MediaRecorder.isTypeSupported(x));if(!mime)throw Error('Формат запису недоступний.');chunks=[];recorder=new MediaRecorder(stream,{mimeType:mime,audioBitsPerSecond:64000,videoBitsPerSecond:250000});recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);if(chunks.reduce((n,b)=>n+b.size,0)>=MAX_MEDIA_BYTES)stop();};recorder.onstop=()=>{blob=new Blob(chunks,{type:mime.split(';')[0]});finish();};recorder.onerror=()=>{status('Запис перервано. Перевірте результат і зазначте проблему.');stop();};recorder.start(500);timer=setTimeout(stop,30000);}q('stop').disabled=false;status(profile.kind==='image'?'Камеру ввімкнено. Зробіть фото.':'Запис триває.');}catch(error){release();status(error.name==='NotAllowedError'?'Доступ до пристрою не надано. Можна додати готовий файл.':error.message);q('start').disabled=false;}finally{pending=false;}};
 q('stop').onclick=()=>{if(profile.kind!=='image'){stop();return;}const v=d.querySelector('[data-record-preview] video'),canvas=document.createElement('canvas');canvas.width=v.videoWidth;canvas.height=v.videoHeight;if(!canvas.width){status('Дочекайтеся зображення.');return;}canvas.getContext('2d').drawImage(v,0,0);pending=true;canvas.toBlob(b=>{blob=b;finish();},'image/png');};
 q('download').onclick=async()=>download(await encode(blob),blob.type,profile.kind==='image'?'Носій.png':blob.type.includes('mp4')?'Запис.mp4':'Запис.webm');
 d.querySelector('form').addEventListener('submit',e=>{if(pending||stream){e.preventDefault();e.stopImmediatePropagation();status('Завершіть запис і дочекайтеся підготовки файла.');}},true);
 return d;
}
