import {landPath} from '../vendor/discovery-land.mjs?v=20261002-programmes2';
import {discoveryKeys,discoverySpec,discoverySearch,discoverySource,discoveryFacets,discoveryFile,termNeighbours} from '../data/discovery.mjs?v=20261002-programmes2';
import {sourceView} from '../data/research.mjs?v=20261002-programmes2';
import {mediaPreview} from './session-media.mjs?v=20261002-programmes2';
export const discoveryContext=p=>({...Object.fromEntries(discoveryKeys.map(k=>[k,p.get(k)||''])),archive_id:p.get('archive_id')||p.get('archive')||'',query:p.get('query')||''});
export function discoverySearchPage(c){
 const {st,actor,scope,p,esc,pg,show,heading,panel,body,table,input,details,btn,act,link,form,go,enabled,corpusWizard,dialog}=c;
 let q;try{q=discoverySpec({...discoveryContext(p),archive_id:scope||p.get('archive_id')||p.get('archive')||''});}catch(e){show(heading('Дослідження','Пошук джерел',e.message)+link(41,'Очистити фільтри'));return;}
 const query=p.get('query')||'',rows=discoverySearch(st,actor,q),facets=discoveryFacets(discoverySearch(st,actor,{archive_id:q.archive_id})),basketKey='hereditas.discovery.basket.'+actor;
 let selected;try{selected=JSON.parse(sessionStorage.getItem(basketKey)||'[]');}catch{selected=[];}
 const keep=()=>sessionStorage.setItem(basketKey,JSON.stringify(selected)),selectedRows=()=>selected.map(x=>sourceView(st,actor,x.id,x.revision_id)).filter(Boolean);
 const options=(key,title,values)=>`<label>${esc(title)}<select name="${key}">${key==='mode'?'':'<option value="">Усі</option>'}${values.map(x=>`<option value="${esc(x.id)}" ${q[key]===x.id?'selected':''}>${esc(x.label)}${x.count==null?'':' ('+x.count+')'}</option>`).join('')}</select></label>`;
 const nav=extra=>({...q,query,...extra});
 const mark=text=>{const n=q.q.trim(),i=n?String(text).toLocaleLowerCase('uk').indexOf(n.toLocaleLowerCase('uk')):-1;return i<0?esc(text):esc(text.slice(0,i))+'<mark>'+esc(text.slice(i,i+n.length))+'</mark>'+esc(text.slice(i+n.length));};
 act('save-query',()=>form('Зберегти пошук',input('name','Назва пошуку','',false,true)+input('question','Дослідницьке питання',q.question,true)+details([['Запит',q.q||'Усі доступні матеріали'],['Режим',q.mode==='context'?'За змістовими зв’язками':'За словами'],['Фільтри',Object.entries(q).filter(([k,v])=>v&&!['q','question','mode','archive_id'].includes(k)).map(([k,v])=>({kind:'Тип',person:'Особа',place:'Місце',institution:'Установа',term:'Поняття',language:'Мова',media:'Медіа',verified:'Перевірка',date_from:'Від дати',date_to:'До дати',bounds:'Область карти'}[k])+': '+(facets[k]?.find(x=>x.id===v)?.label||({information_unit:'Запис',document:'Документ',physical_object:'Носій',verified:'Є підтвердження',unverified:'Немає підтвердження'}[v])||(['person','place','institution','term'].includes(k)?'Значення недоступне':v))).join('\n')||'Без додаткових обмежень']]),v=>({type:'research.query',name:v.name,spec:{...q,question:v.question}}),()=>go(42)));
 act('create-corpus',()=>{const current=selectedRows();if(!current.length)return;corpusWizard(current);});
 act('basket',()=>{const available=selectedRows(),d=dialog('Відібрані джерела',table(['Джерело','Версія',''],available.map(x=>[link(45,x.title,{id:x.id,revision:x.revision_id,...nav()}),x.revision_no,`<button type="button" class="button secondary" data-remove="${x.id}">Прибрати</button>`]))+(available.length<selected.length?'<p>Частина джерел стала недоступною й не буде передана до корпусу.</p>':''),null,'Закрити');d.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{selected=selected.filter(x=>x.id!==b.dataset.remove);keep();b.closest('tr').remove();updateCount();});});
 const names={person:'Особа',place:'Місце',institution:'Установа',term:'Поняття',language:'Мова',media:'Медіа'},kindOptions=[{id:'information_unit',label:'Запис'},{id:'document',label:'Документ'},{id:'physical_object',label:'Носій'}];
 const filterHTML=options('kind','Тип джерела',kindOptions)+Object.entries(names).map(([key,title])=>options(key,title,facets[key])).join('')+options('verified','Перевірка',[{id:'verified',label:'Є підтвердження цієї версії'},{id:'unverified',label:'Немає підтвердження цієї версії'}])+input('date_from','Від дати',q.date_from)+input('date_to','До дати',q.date_to);
 const points=rows.flatMap(x=>x.places.filter(p=>Number.isFinite(p.latitude)&&Number.isFinite(p.longitude)).map(p=>({...p,source:x}))),grouped=[...new Map(points.map(x=>[x.id,x])).values()];
 const map=grouped.length?`<div class="discovery-map" aria-label="Карта місць"><div class="research-toolbar"><button class="button secondary" type="button" data-map-zoom="in">Наблизити</button><button class="button secondary" type="button" data-map-zoom="out">Віддалити</button><button class="button secondary" type="button" data-map-zoom="reset">Увесь світ</button><button class="button secondary" type="button" data-map-area>Шукати в цій області</button></div><svg viewBox="0 0 720 360" role="img" aria-label="Географічна сітка: довгота від −180 до 180, широта від −90 до 90"><rect width="720" height="360" fill="#e1edf0"/><path d="${landPath}" fill="#eaf0df" stroke="#b3c2b0" stroke-width="0.5" vector-effect="non-scaling-stroke"/>${[-120,-60,0,60,120].map(l=>`<path d="M${(l+180)*2} 0v360" stroke="#cad7c9"/><text x="${(l+180)*2+3}" y="350" font-size="11">${l}°</text>`).join('')}${[-60,-30,0,30,60].map(l=>`<path d="M0 ${(90-l)*2}h720" stroke="#cad7c9"/><text x="4" y="${(90-l)*2-4}" font-size="11">${l}°</text>`).join('')}${grouped.map(pt=>`<a href="${pg(41,{role:'R04',...nav({place:pt.id})})}" aria-label="${esc(pt.label)}"><circle cx="${(pt.longitude+180)*2}" cy="${(90-pt.latitude)*2}" r="7" fill="#235844" stroke="white" stroke-width="2" vector-effect="non-scaling-stroke"/><title>${esc(pt.label)}: ${pt.latitude}, ${pt.longitude}</title></a>`).join('')}</svg></div>`+table(['Місце','Координати','Джерела'],grouped.map(pt=>[link(41,pt.label,nav({place:pt.id})),`${pt.latitude}, ${pt.longitude}${pt.note?' · '+esc(pt.note):''}`,points.filter(x=>x.id===pt.id).map(x=>link(45,x.source.title,{id:x.source.id,revision:x.source.revision_id,...nav()})).join('<br>')])):'<p>У результатах немає дозволених координат. Місця без координат залишаються доступними у фільтрі та списку.</p>';
 show(heading('Дослідницька робота','Пошук джерел','Шукайте в описах, дозволених текстах і часових фрагментах. Перед добором перегляньте джерело, походження та перевірку.')+
  `<form class="discovery-search"><input type="hidden" name="role" value="R04"><input type="hidden" name="query" value="${esc(query)}"><input type="hidden" name="archive_id" value="${esc(q.archive_id)}"><input type="hidden" name="question" value="${esc(q.question)}">${input('q','Знайти джерело',q.q)}${options('mode','Спосіб пошуку',[{id:'literal',label:'За словами'},{id:'context',label:'За змістовими зв’язками'}])}<details ${discoveryKeys.some(k=>!['q','mode','question','archive_id'].includes(k)&&q[k])?'open':''}><summary>Уточнити пошук</summary><div class="discovery-facets">${filterHTML}${input('bounds','Область карти: захід, південь, схід, північ',q.bounds)}</div></details><button class="button">Знайти</button> ${link(41,'Скинути фільтри')}</form>`+
  `<div class="research-toolbar">${btn('Відібрано: '+selectedRows().length,'basket')}${btn('Створити корпус із вибраного','create-corpus',enabled)}${btn('Зберегти пошук','save-query',enabled)}</div>`+
  panel('Результати: '+rows.length,table(['Обрати','Джерело та збіг','Контекст'],rows.map(x=>[`<input type="checkbox" name="source-selection" value="${x.id}" aria-label="${esc('Обрати: '+x.title)}" ${selected.some(v=>v.id===x.id&&v.revision_id===x.revision_id)?'checked':''}>`,link(45,x.title,{id:x.id,revision:x.revision_id,...nav(),from:'search'})+x.hits.slice(0,3).map(h=>`<p><strong>${esc(h.kind)}</strong> ${h.start_ms==null?'':(h.start_ms/1000)+' с'}<br>${mark(h.text)} ${h.resource_id?link(45,'Відкрити збіг',{id:x.id,revision:x.revision_id,...nav(),resource:h.resource_id,segment:h.segment_id||''}):''}</p>`).join('')+x.paths.map(t=>`<p>Змістовий зв’язок: ${esc(t.relation)} → ${esc(t.label)}</p>`).join(''),esc('Версія '+x.revision_no)+'<br>'+esc(x.verified?'Є підтвердження':'Підтвердження не показано')+'<br>'+x.places.map(p=>link(41,p.label,nav({place:p.id}))).join(', ')]),'За цими умовами доступних джерел немає.'))+
  `<details class="record-history"><summary>Карта місць</summary>${body(map)}<p>Основа: Natural Earth. Позначено лише відомі й дозволені координати. Область карти можна задати у фільтрах; натисніть місце для переходу.</p></details>`+
  `<details><summary>Як працює пошук за змістом</summary><p>Використовуються назви й альтернативні назви активних понять, їхні батьківські/дочірні терміни та підтверджені відповідності. У результаті показано підставу збігу. Це пошук за явними зв’язками довідника, без прихованої оцінки подібності.</p></details>`);
 const svg=document.querySelector('.discovery-map svg');if(svg){let box=[0,0,720,360];const center=grouped.length?[(grouped[0].longitude+180)*2,(90-grouped[0].latitude)*2]:[360,180];document.querySelectorAll('[data-map-zoom]').forEach(b=>b.onclick=()=>{if(b.dataset.mapZoom==='reset')box=[0,0,720,360];else{const factor=b.dataset.mapZoom==='in'?0.5:2,w=Math.min(720,Math.max(8,box[2]*factor)),h=w/2;box=[Math.max(0,Math.min(720-w,center[0]-w/2)),Math.max(0,Math.min(360-h,center[1]-h/2)),w,h];}svg.setAttribute('viewBox',box.join(' '));svg.querySelectorAll('circle').forEach(c=>c.setAttribute('r',7*box[2]/720));svg.querySelectorAll('text').forEach(t=>t.setAttribute('font-size',11*box[2]/720));});document.querySelector('[data-map-area]').onclick=()=>{const bounds=[box[0]/2-180,90-(box[1]+box[3])/2,(box[0]+box[2])/2-180,90-box[1]/2].map(x=>x.toFixed(3)).join(',');go(41,nav({bounds}));};}
 function updateCount(){const b=document.querySelector('[data-research-action=basket]');if(b)b.textContent='Відібрано: '+selectedRows().length;}
 document.querySelectorAll('[name=source-selection]').forEach(el=>el.onchange=()=>{selected=selected.filter(x=>x.id!==el.value);if(el.checked){const x=rows.find(x=>x.id===el.value);selected.push({id:x.id,revision_id:x.revision_id});}keep();updateCount();});
}
export function discoverySourcePanels(c,source){
 const {st,actor,p,esc,link,panel,body,table,details,btn,act,dialog}=c,v=discoverySource(st,actor,source.id,source.revision_id);if(!v)return '';
 const nav=extra=>({...discoveryContext(p),...extra}),chips=(rows,key)=>rows.map(x=>link(41,x.label,nav({[key]:x.id}))).join(' · ')||'Не зазначено або не дозволено';
 const highlight=text=>{const q=p.get('q')||'',i=q?text.toLocaleLowerCase('uk').indexOf(q.toLocaleLowerCase('uk')):-1;return i<0?esc(text):esc(text.slice(0,i))+'<mark>'+esc(text.slice(i,i+q.length))+'</mark>'+esc(text.slice(i+q.length));};
 const open=r=>{let html='';if(r.type==='text')html='<pre class="reading-text">'+highlight(r.text)+'</pre>';else if(r.type==='media')html=r.files.map(f=>mediaPreview(discoveryFile(st,actor,v.id,v.revision_id,f.id),f.mime,esc)).join('');else{const rep=v.resources.find(x=>x.type==='media'&&x.id===r.representation_id);html=(rep?.files||[]).map(f=>mediaPreview(discoveryFile(st,actor,v.id,v.revision_id,f.id),f.mime,esc)).join('')+table(['Фрагмент','Текст','Мовець'],r.segments.map(e=>[`<button type="button" class="button secondary" data-segment="${e.id}">${e.start_ms/1000}–${e.end_ms/1000} с</button>`,esc(e.text),esc(e.speaker||'Не визначено')]));}
  const d=dialog(r.label,html,null,'Закрити');d.querySelector('mark')?.scrollIntoView({block:'center'});d.querySelectorAll('[data-segment]').forEach(b=>b.onclick=()=>{const seg=r.segments.find(x=>x.id===b.dataset.segment),rep=v.resources.find(x=>x.type==='media'&&x.id===r.representation_id),files=rep?.files||[],idx=files.findLastIndex(f=>f.offset_ms!=null&&f.offset_ms<=seg.start_ms),player=d.querySelectorAll('audio,video')[idx];if(player){player.currentTime=(seg.start_ms-files[idx].offset_ms)/1000;player.ontimeupdate=()=>{if(player.currentTime>=(seg.end_ms-files[idx].offset_ms)/1000)player.pause();};player.play().catch(()=>{});}});if(p.get('segment'))d.querySelector(`[data-segment="${CSS.escape(p.get('segment'))}"]`)?.click();
 };
 v.resources.forEach(r=>act('resource-'+r.id,()=>open(r)));
 if(p.get('resource')){const r=v.resources.find(x=>x.id===p.get('resource'));if(r)setTimeout(()=>open(r),0);}
 return panel('Контекст',body(details([['Період',[v.date.from,v.date.to,v.date.label].filter(Boolean).join(' — ')||'Не зазначено або не дозволено'],['Мови',v.languages.join(', ')]]))+body('<p>Особи: '+chips(v.people,'person')+'</p><p>Місця: '+chips(v.places,'place')+'</p><p>Установи: '+chips(v.institutions,'institution')+'</p><p>Поняття: '+chips(v.terms,'term')+'</p>'+v.terms.map(t=>'<details><summary>'+esc(t.label)+': пов’язані поняття</summary>'+termNeighbours(st,t.id).map(n=>'<p>'+esc(n.relation)+': '+link(41,n.label,nav({term:n.id,mode:'context'}))+'</p>').join('')+'</details>').join('')))+
  panel('Тексти й медіа',table(['Ресурс','Мова',''],v.resources.map(r=>[esc(r.label),esc(r.language||'—'),btn('Відкрити','resource-'+r.id)]),'Дозволених ресурсів для цієї версії немає.'))+
  panel('Походження й перевірка',body(details([['Версія джерела',v.revision_no],['Архівний шифр',v.reference],['Атрибуція',v.attribution],['Ідентифікатори',v.identifiers.map(x=>x.scheme+': '+x.value).join('\n')]]))+table(['Дата','Спосіб / аспект','Висновок'],v.verification.map(x=>[esc(x.date),esc(x.method+' · '+x.aspect),esc(x.result)]),'Підтвердження цієї версії не надано або недоступне.')+table(['Джерело походження','Місце'],v.evidence.map(e=>[link(45,e.label,{id:e.id,revision:e.revision_id}),esc(e.locator||'—')]),'Додаткових дозволених джерел походження немає.'));
}
