import {intakeFacts,intakePackage} from '../data/intake.mjs?v=20261002-wf17';
import {verifyTransferBundle} from '../data/handover.mjs?v=20261002-wf17';
import {download,mediaPreview} from './session-media.mjs?v=20261002-wf17';
import {wizard} from './wizard.mjs?v=20261002-wf17';
const states={reviewing:'Очікує розгляду',partial:'Прийнято частково',accepted:'Прийнято',returned:'На доопрацюванні'};
const decisions={pending:'Не розглянуто',accept:'Прийняти',restricted:'Прийняти з обмеженням',defer:'Відкласти',return:'Повернути'};
const docStates={missing:'Відсутнє / не перевірено',verified:'Перевірено',not_applicable:'Не потрібне — з поясненням'};
export function intakePages(c){
 const {st,actor,archive,can,scope,params,by,rev,action,dialog,input,select,choices,options,dispatch,render,flash,panel,body,table,details,btn,button,pg,esc,show,heading,label}=c,t=st.tables;
 const visible=(t.intake_record||[]).filter(r=>can(st,actor,'domain.read',r.archive_id)&&(!scope||r.archive_id===scope));
 const open=id=>location.href=pg(11,{role:'R02',intake:id});
 function receive(local=null){
  const a=local?t.entity.find(e=>e.id===by('workflow_run',local.from_workflow_run_id)?.primary_entity_id)?.archive_id:archive;
  if(!can(st,actor,'intake.receive',a))return;
  const research=t.field_research.filter(r=>r.archive_id===a),primary=local&&by('workflow_run',local.from_workflow_run_id).primary_entity_id;
  dialog('Зареєструвати надходження',(local?body(details([['Пакет',label(primary)]])):'<label>Файл пакета<input type="file" name="package" accept=".json" required></label>')+input('title','Назва надходження',local?label(primary):'','text',true)+input('sender_label','Від кого отримано',local?'Користувач':'','text',true)+select('research_id','Заявлене дослідження',options(research,by('collecting_session',primary)?.research_id,x=>x.title)),async fd=>{
   let bundle;if(!local){const f=fd.get('package');if(!f?.size||f.size>32*1024*1024)throw Error('Оберіть пакет до 32 МБ.');try{bundle=JSON.parse(await f.text());}catch{throw Error('Не вдалося прочитати пакет.');}await verifyTransferBundle(bundle);}
   const result=await dispatch({type:local?'intake.receive-local':'intake.import',archive_id:a,handover_id:local?.id,bundle,title:fd.get('title'),sender_label:fd.get('sender_label'),research_id:fd.get('research_id')});open(result.id);
  },'Зареєструвати');
 }
 function list(){
  action('intake-import',()=>receive());
  const q=(params.get('q')||'').toLocaleLowerCase('uk'),filter=params.get('state')||'';
  const rows=visible.filter(r=>(!filter||(filter==='sent'?'reviewing':filter)===r.state)&&(!q||(r.title+' '+r.sender_label).toLocaleLowerCase('uk').includes(q)));
  return panel('Зареєстровані надходження',table(['Надходження','Відправник','Стан','Прийнято','Дія'],rows.map(r=>{const items=(t.intake_item||[]).filter(i=>i.intake_id===r.id);return [esc(r.title),esc(r.sender_label),esc(states[r.state]),items.filter(i=>i.local_entity_id).length+' / '+items.length,button('Відкрити',pg(11,{role:'R02',intake:r.id}),true)];})),btn('Зареєструвати надходження','intake-import',can(st,actor,'intake.receive',archive)));
 }
 function review(r){
  const facts=intakeFacts(st,r),bundle=intakePackage(st,r),pending=t.intake_item.filter(i=>i.intake_id===r.id&&!i.local_entity_id),expected=rev(r.id),old=r.checks||{};
  wizard({dialog,esc},{title:'Розглянути надходження',submit:'Зафіксувати рішення',steps:[
   {title:'Дослідження та зв’язки',body:body(details([['Заявлене дослідження',by('field_research',r.research_id).title],['Дослідження джерела',bundle.payload.context?.researches?.map(x=>x.title).join('; ')||'Назви не передано'],['Сеансів',facts.sessions.length],['Файлів',facts.files.length]]))+(facts.problems.length?body('<ul>'+facts.problems.map(p=>'<li>'+esc(p)+'</li>').join('')+'</ul>'):'')+'<label class="check-label"><input type="checkbox" name="research_confirmed" required>Належність матеріалів дослідженню перевірено</label><label class="check-label"><input type="checkbox" name="links_confirmed" required>Зв’язки дослідження, сеансів і матеріалів перевірено</label>'+input('relationship_note','Підстава звірки',old.relationship_note||'','textarea',true)},
   {title:'Документація',body:body(details([['Бланків у пакеті',facts.forms.length],['Польових зошитів',facts.notebooks.length],['Невирішених питань відправника',facts.openIssues.length]]))+select('forms','Бланки сеансів',choices(docStates,old.forms||'missing'))+input('forms_note','Пояснення щодо бланків',old.forms_note||'','textarea')+select('notes','Польові нотатки',choices(docStates,old.notes||'missing'))+input('notes_note','Пояснення щодо нотаток',old.notes_note||'','textarea')},
   ...facts.consentRows.map((person,index)=>{const prev=old.consents?.find(x=>x.key===person.key);return {title:'Згода: '+person.label,body:body(`<p>${esc(person.available?'У пакеті є запис про згоду. Окремо перевірте підтвердження та обсяг.':'Підтвердження згоди потрібно звірити окремо. Відсутність запису не означає дозвіл.')}</p>`)+select('consent_'+index,'Результат звірки згоди',choices(docStates,prev?.status||'missing'))+input('evidence_'+index,'Де зберігається підтвердження',prev?.evidence_locator||'')+input('consent_note_'+index,'Обсяг, обмеження та результат перевірки',prev?.note||'','textarea',true)};}),
   ...pending.map(item=>{const source=bundle.payload.items.find(i=>i.position===item.position),snap=source.revision.snapshot;return {title:'Матеріал '+item.position,body:body(details([['Матеріал',snap.title||snap.original_filename||'Опис'],['Версія джерела',source.revision.revision_no],['Опис',snap.summary||snap.body_text||snap.context_notes||'Не зазначено']]))+select('decision_'+item.position,'Рішення щодо матеріалу',choices({accept:decisions.accept,restricted:decisions.restricted,defer:decisions.defer,return:decisions.return},'defer'))+input('code_'+item.position,'Архівний шифр',item.archive_code||(r.local_handover_id?t.identifier.find(x=>x.entity_id===item.source_entity_id&&x.scheme==='archive_inventory'&&x.namespace===r.archive_id)?.value:null)||'НД-'+r.id.slice(0,8)+'-'+String(item.position).padStart(3,'0'))+input('reason_'+item.position,'Підстава рішення',item.reason||'','textarea')};})
  ],summary:v=>body(`<p>Рішення буде збережено для ${pending.length} матеріалів. Відкладені та обмежені матеріали отримають завдання. Приймання не дозволяє публікацію.</p>`),onSubmit:async v=>{
   await dispatch({type:'intake.review',id:r.id,expected_revision_id:expected,checks:{research_confirmed:!!v.research_confirmed?.length,links_confirmed:!!v.links_confirmed?.length,relationship_note:v.relationship_note,forms:v.forms,forms_note:v.forms_note,notes:v.notes,notes_note:v.notes_note,consents:facts.consentRows.map((p,i)=>({key:p.key,status:v['consent_'+i],evidence_locator:v['evidence_'+i],note:v['consent_note_'+i]}))},decisions:pending.map(i=>({position:i.position,decision:v['decision_'+i.position],archive_code:v['code_'+i.position],reason:v['reason_'+i.position]}))});flash('Рішення приймання зафіксовано.');render();
  }});
 }
 function detail(){
  const r=visible.find(r=>r.id===params.get('intake'));if(!r){show(heading('Надходження','Надходження недоступне','',button('До надходжень',pg(10,{role:'R02'}))));return;}
  const bundle=intakePackage(st,r),items=t.intake_item.filter(i=>i.intake_id===r.id),canReview=can(st,actor,'intake.receive',r.archive_id)&&can(st,actor,'consent.read',r.archive_id),facts=intakeFacts(st,r);
  action('intake-review',()=>review(r));action('intake-original',()=>download(st.demo.file_contents[r.package_file_id],'application/json','Надходження-'+r.source_package_id+'.json'));
  items.forEach(i=>action('intake-view-'+i.position,()=>{const source=bundle.payload.items.find(x=>x.position===i.position),snap=source.revision.snapshot,f=bundle.payload.files.find(x=>x.id===i.source_entity_id),canConsent=i.source_type!=='consent_record'||can(st,actor,'consent.read',r.archive_id);if(!canConsent)throw Error('Немає доступу до згоди.');const d=dialog(snap.title||snap.original_filename||'Опис матеріалу',body(details([['Версія джерела',source.revision.revision_no],['Архівний шифр',i.archive_code],['Опис',snap.body_text||snap.summary||snap.context_notes||snap.terms||'Не зазначено'],['Рішення',i.reason||decisions[i.decision]]]))+(f?body(mediaPreview(f.content,f.mime_type,esc))+'<button type="button" class="button secondary" data-intake-file>Завантажити оригінал</button>':''),null,'Закрити');if(f)d.querySelector('[data-intake-file]').onclick=()=>download(f.content,f.mime_type,f.filename.split(/[\\/]/).at(-1));}));
  const taskIds=[...new Set([...r.followup_task_ids,...items.map(i=>i.task_id).filter(Boolean)])];
  show(heading('Надходження',r.title,'',button('← Надходження',pg(10,{role:'R02'}),true))+panel('Облік',table(['Стан','Від кого','Дослідження','Прийнято'],[[esc(states[r.state]),esc(r.sender_label),esc(by('field_research',r.research_id).title),items.filter(i=>i.local_entity_id).length+' / '+items.length]])+body(`<div class="actions">${btn('Розглянути надходження','intake-review',canReview&&r.state!=='accepted')}${btn('Завантажити отриманий пакет','intake-original',canReview)}${items.some(i=>i.local_entity_id)?button('Опрацювати прийняті матеріали',pg(17,{role:'R02',intake:r.id}),true):''}</div>`))+panel('Матеріали',table(['Матеріал','Архівний шифр','Рішення','Дія'],items.map(i=>{const snap=bundle.payload.items.find(x=>x.position===i.position).revision.snapshot;return [esc(snap.title||snap.original_filename||'Опис'),esc(i.archive_code||'Ще не присвоєно'),esc(i.decision==='pending'?'Не розглянуто':i.decision==='restricted'?'Прийнято з обмеженням':i.local_entity_id?'Прийнято':i.decision==='defer'?'Відкладено':'Повернуто'),btn('Переглянути','intake-view-'+i.position,i.source_type!=='consent_record'||canReview)];})))+panel('Питання на доопрацювання',table(['Завдання','Стан','Дія'],taskIds.map(id=>{const w=by('work_item',id);return [esc(w.title),w.state==='done'?'Виконано':'Відкрите',button('Відкрити',pg(3,{id}),true)];})))+body('<details class="page-help"><summary>Що означає приймання</summary><p>Файли й описи взято на облік. Обмеження та питання згоди опрацьовуються окремо. Доступ для відвідувачів і публікація не змінюються.</p></details>'));
 }
 return {list,detail,receive};
}
