import {parseInventory,inventoryRows,exampleInventory} from '../data/legacy-import.mjs?v=20260930-wf06';
import {download,encode,mediaPreview} from './session-media.mjs?v=20260930-wf06';
import {wizard} from './wizard.mjs?v=20260930-wf06';
const priorities={none:'Не визначено',normal:'Планово',urgent:'Терміново'};
export function legacyPages(c){
 const {st,actor,archive,scope,params,t,by,rev,can,visible,allowed,label,action,dialog,input,select,options,choices,dispatch,render,flash,panel,body,table,details,btn,button,pg,esc,show,heading,form}=c;
 const openBatch=(source,batch)=>location.href=pg(21,{role:'R02',id:source,batch});
 const docs=source=>t.document.filter(d=>d.kind==='source_document'&&t.document_context.some(x=>x.document_id===d.id&&x.target_entity_id===source));
 const documentFile=d=>t.document_context.find(x=>x.document_id===d.id&&x.context_role==='original_file')?.target_entity_id;
 const invFor=id=>t.legacy_inventory?.find(i=>i.source_record_id===id);
 function sourceForm(){form('Додати спадкове джерело',input('name','Назва джерела','','text',true)+select('system_kind','Вид джерела',choices({catalogue:'Каталог',cards:'Картотека',spreadsheet:'Електронна таблиця',document:'Документ',database:'База даних',file_register:'Файловий реєстр',other:'Інше'},'catalogue'))+input('source_uri','Посилання або місце оригіналу')+input('description','Походження та наявна структура','','textarea',true),fd=>({type:'legacy.source',archive_id:archive,...Object.fromEntries(fd)}),r=>location.href=pg(21,{role:'R02',id:r.id}));}
 function mapTable(source,text,filename,delimiter){
  const parsed=parseInventory(text,delimiter),suggest={key:'Ключ',parent:'Батько',code:'Шифр',text:'Опис',locator:'Місце',path:'Шлях'},fields={key:'Ключ рядка',parent:'Батьківський ключ',code:'Історичний шифр',text:'Оригінальний опис',locator:'Сторінка / картка',path:'Початковий шлях файла'};
  wizard({dialog,esc},{title:'Імпортувати інвентар',submit:'Імпортувати',steps:[{title:'Стовпці та структура',body:input('title','Назва партії',filename,'text',true)+Object.entries(fields).map(([key,title])=>select(key,title,'<option value="">Не задано</option>'+parsed.headers.map(h=>`<option value="${esc(h)}" ${h===(suggest[key])?'selected':''}>${esc(h)}</option>`).join(''))).join('')+body('<details><summary>Як зберігається структура</summary><p>Ключ рядка й батьківський ключ відтворюють вкладеність. Історичні шифри можуть повторюватися. Порожні поля залишаються невідомими. Таблицю Excel збережіть як CSV UTF-8; оригінальний файл можна окремо додати до документів джерела.</p></details>')},{title:'Оригінальні рядки',body:table(parsed.headers,parsed.rows.slice(0,5).map(r=>r.cells.map(esc)))+body(`<p>Усього рядків: ${parsed.rows.length}. Показано перші ${Math.min(5,parsed.rows.length)}.</p>`)}],summary:v=>{try{const mapping=Object.fromEntries(Object.keys(fields).map(k=>[k,v[k]])),rows=inventoryRows(parsed,mapping);return body(details([['Партія',v.title],['Рядків',rows.length],['Вкладених записів',rows.filter(r=>r.parent_key).length],['Оригінал',filename]]));}catch(e){return body('<p class="notice warning">'+esc(e.message)+'</p>');}},onSubmit:async v=>{const result=await dispatch({type:'legacy.import',id:source.id,raw_text:text,filename,delimiter:parsed.delimiter,title:v.title,mapping:Object.fromEntries(Object.keys(fields).map(k=>[k,v[k]]))});openBatch(source.id,result.id);}});
 }
 function importTable(source){dialog('Вибрати таблицю','<label>Таблиця CSV або TSV<input type="file" name="file" accept=".csv,.tsv,.txt" required></label>'+select('delimiter','Роздільник',choices({auto:'Визначити автоматично',',':'Кома',';':'Крапка з комою','\t':'Табуляція'},'auto')),async fd=>{const f=fd.get('file');if(!f?.size||f.size>2*1024*1024)throw Error('Оберіть таблицю до 2 МБ.');const bytes=await f.arrayBuffer();let text;try{text=new TextDecoder('utf-8',{fatal:true}).decode(bytes);}catch{throw Error('Збережіть таблицю в UTF-8 і повторіть імпорт.');}if(new Uint8Array(bytes).slice(0,3).join(',')==='239,187,191')text='\ufeff'+text;parseInventory(text,fd.get('delimiter'));setTimeout(()=>mapTable(source,text,f.name,fd.get('delimiter')),0);},'Переглянути');}
 function recordForm(source){form('Додати джерельний запис',input('external_key','Історичний шифр')+input('source_position','Порядок у джерелі',t.source_record.filter(r=>r.source_system_id===source.id).length+1,'number',true)+select('parent_record_id','Батьківський запис','<option value="">Не задано</option>'+options(t.source_record.filter(r=>r.source_system_id===source.id),'',r=>r.external_key||r.source_locator||r.raw_text?.slice(0,70)))+select('document_id','Документ джерела','<option value="">Не задано</option>'+options(docs(source.id)))+input('source_locator','Сторінка / картка')+input('source_path','Початковий шлях файла')+input('raw_text','Оригінальний текст','','textarea',true),fd=>({type:'legacy.record',id:source.id,...Object.fromEntries(fd)}),r=>location.href=pg(22,{role:'R02',id:r.id}));}
 function documentForm(source){dialog('Додати документ джерела',input('title','Назва документа','','text',true)+input('body_text','Оригінальний текст','','textarea')+'<label>Оригінальний файл<input type="file" name="file"></label>',async fd=>{const f=fd.get('file');if(f?.size>2*1024*1024)throw Error('Файл перевищує 2 МБ.');await dispatch({type:'legacy.document',id:source.id,title:fd.get('title'),body_text:fd.get('body_text'),content:f?.size?await encode(f):null,filename:f?.name,mime_type:f?.type});render();});}
 function list(){
  action('legacy-source',sourceForm);const systems=visible('source_system');
  if(!params.has('id')){show(heading('Архівна робота','Спадкові джерела','',btn('Додати джерело','legacy-source',can(st,actor,'legacy.write',archive)))+panel('Джерела',table(['Джерело','Записів','Питань','Дія'],systems.map(s=>{const rows=t.source_record.filter(r=>r.source_system_id===s.id);return [esc(s.name),rows.length,rows.filter(r=>invFor(r.id)?.unresolved_note).length,button('Відкрити записи',pg(21,{role:'R02',id:s.id}),true)];}))));return;}
  const source=systems.find(s=>s.id===params.get('id'));if(!source){show(heading('Спадкові джерела','Джерело недоступне','',button('До джерел',pg(21,{role:'R02'}))));return;}
  const batches=(t.legacy_batch||[]).filter(b=>b.source_system_id===source.id),batch=params.get('batch')?batches.find(b=>b.id===params.get('batch')):null,q=(params.get('q')||'').toLocaleLowerCase('uk'),filter=params.get('filter')||'';
  if(params.has('batch')&&!batch){show(heading('Спадкові джерела','Партія недоступна','',button('До джерела',pg(21,{role:'R02',id:source.id}))));return;}
  const records=t.source_record.filter(r=>r.source_system_id===source.id&&(!batch||r.import_run_id===batch.workflow_run_id)).filter(r=>{const i=invFor(r.id);return (!q||(r.external_key+' '+r.raw_text+' '+i?.title).toLocaleLowerCase('uk').includes(q))&&(!filter||filter==='issues'&&i?.unresolved_note||filter==='urgent'&&(i?.digitization_priority==='urgent'||i?.description_priority==='urgent')||filter==='physical'&&i?.physical_object_id||filter==='digital'&&i?.file_id);});
  action('legacy-import',()=>importTable(source));action('legacy-record',()=>recordForm(source));action('legacy-doc',()=>documentForm(source));action('legacy-example',()=>mapTable(source,exampleInventory,'Приклад інвентарю.csv',';'));
  for(const b of batches)action('legacy-download-'+b.id,()=>download(st.demo.file_contents[b.original_file_id],'text/csv;charset=utf-8',by('file_object',b.original_file_id).original_filename));
  for(const d of docs(source.id))action('legacy-doc-'+d.id,()=>{const f=by('file_object',documentFile(d));const modal=dialog(d.title,body('<pre class="source-text">'+esc(d.body_text||'Оригінал збережено у файлі.')+'</pre>')+(f?'<button type="button" class="button secondary" data-original>Завантажити оригінал</button>':''),null,'Закрити');if(f)modal.querySelector('[data-original]').onclick=()=>download(st.demo.file_contents[f.id],f.mime_type,f.original_filename);});
  show(heading('Спадкові джерела',batch?.title||source.name,'',button('← '+(batch?'Джерело':'Джерела'),pg(21,{role:'R02',...(batch?{id:source.id}:{})}),true))+body(`<div class="actions">${btn('Імпортувати таблицю','legacy-import',allowed(source.id,'legacy.write'))}${btn('Додати запис','legacy-record',allowed(source.id,'legacy.write'))}${btn('Додати документ','legacy-doc',allowed(source.id,'legacy.write'))}</div>`)+`<form class="filters"><input type="hidden" name="id" value="${source.id}"><input type="hidden" name="role" value="R02">${batch?`<input type="hidden" name="batch" value="${batch.id}">`:''}${input('q','Пошук',params.get('q')||'')}${select('filter','Показати',choices({'':'Усі записи',issues:'Невирішені питання',urgent:'Термінове опрацювання',physical:'Зареєстровані носії',digital:'Зареєстровані файли'},filter))}<button class="button">Знайти</button></form>`+
   panel('Інвентар',table(['Порядок / батько','Шифр','Джерельний опис','Облік / пріоритет','Дія'],records.map(r=>{const i=invFor(r.id),parent=by('source_record',r.parent_record_id);return [esc(r.source_position)+(parent?'<small>'+esc(parent.external_key||parent.source_locator||'Батьківський запис')+'</small>':''),esc(r.external_key||'Не зазначено'),esc(i?.title||r.raw_text),esc([i?.physical_object_id?'Носій зареєстровано':'',i?.file_id?'Файл зареєстровано':'',i?.unresolved_note?'Є питання':'',i?.digitization_priority==='urgent'||i?.description_priority==='urgent'?'Терміново':''].filter(Boolean).join(' · ')||'До опрацювання'),button('Відкрити',pg(22,{id:r.id,role:'R02'}),true)];})))+
   panel('Партії імпорту',table(['Партія','Рядків','Дії'],batches.map(b=>[esc(b.title),b.row_count,button('Відкрити партію',pg(21,{id:source.id,batch:b.id,role:'R02'}),true)+' '+btn('Оригінал таблиці','legacy-download-'+b.id)])))+
   panel('Документи джерела',table(['Документ','Дія'],docs(source.id).map(d=>[esc(d.title),btn('Переглянути','legacy-doc-'+d.id)])))+
   body('<details class="page-help"><summary>Як розпочати інвентаризацію</summary><p>Імпортуйте CSV/TSV або внесіть записи вручну. Збережіть стару структуру й формулювання. Носії, цифрові файли, питання та пріоритети опрацьовуються в картці запису. Документи Word, Excel і скани можна зберегти як оригінали.</p>'+btn('Спробувати на прикладі','legacy-example',allowed(source.id,'legacy.write'))+'</details>'));
 }
 function record(row){
  const inv=invFor(row.id),expected=inv?rev(inv.id):rev(row.id),a=t.entity.find(e=>e.id===row.id).archive_id;
  const command=type=>({type,id:row.id,expected_revision_id:expected});
  action('legacy-physical',()=>form('Зареєструвати фізичний носій',input('title','Назва носія',inv?.title||row.raw_text?.slice(0,160)||'','text',true)+input('reference_code','Історичний шифр',row.external_key||'')+select('carrier_type_term_id','Тип носія',options(t.vocabulary_term.filter(v=>v.status==='active'&&by('vocabulary_scheme',v.scheme_id)?.d_code==='D12'),'',v=>t.term_label.find(l=>l.term_id===v.id)?.label||v.code))+input('inscriptions','Написи без виправлень','','textarea')+input('composition','Частини та склад','','textarea')+select('location_id','Місце зберігання','<option value="">Невідоме</option>'+options(visible('storage_location').filter(l=>t.entity.find(e=>e.id===l.id).archive_id===a)))+select('condition_code','Стан носія',choices({unknown:'Не визначено',stable:'Придатний',fragile:'Крихкий',unsafe:'Працювати небезпечно'},'unknown'))+input('risk_notes','Ризики','','textarea')+input('handling_instructions','Правила поводження','','textarea')+input('registration_note','Підстава реєстрації та огляду','','textarea',true),fd=>({...command('legacy.physical'),...Object.fromEntries(fd)})));
  action('legacy-file',()=>dialog('Зареєструвати цифровий файл','<label>Файл<input name="file" type="file" required></label>'+input('source_path','Початковий шлях',inv?.source_path||'')+input('registration_note','Підстава зв’язку із джерелом','','textarea',true),async fd=>{const f=fd.get('file');if(!f?.size||f.size>2*1024*1024)throw Error('Оберіть файл до 2 МБ.');await dispatch({...command('legacy.file'),filename:f.name,mime_type:f.type,content:await encode(f),source_path:fd.get('source_path'),registration_note:fd.get('registration_note')});render();}));
  action('legacy-triage',()=>form('Пріоритети та невирішені питання',select('digitization_priority','Пріоритет оцифрування',choices(priorities,inv?.digitization_priority||'none'))+select('description_priority','Пріоритет опису',choices(priorities,inv?.description_priority||'none'))+input('priority_note','Підстава пріоритету',inv?.priority_note||'','textarea')+input('unresolved_note','Невирішене питання',inv?.unresolved_note||'','textarea')+input('resolution_note','Результат з’ясування питання','','textarea'),fd=>({...command('legacy.triage'),...Object.fromEntries(fd)})));
  action('legacy-file-view',()=>{const f=by('file_object',inv.file_id);const d=dialog(f.original_filename,body(mediaPreview(st.demo.file_contents[f.id],f.mime_type,esc))+'<button class="button secondary" type="button" data-original>Завантажити оригінал</button>',null,'Закрити');d.querySelector('[data-original]').onclick=()=>download(st.demo.file_contents[f.id],f.mime_type,f.original_filename);});
  const physical=inv?.physical_object_id,file=inv?.file_id,tasks=Object.values(inv?.tasks||{}).filter(Boolean),b=t.legacy_batch?.find(b=>b.workflow_run_id===row.import_run_id);
  return panel('Облік та опрацювання',table(['Носій','Цифровий файл','Оцифрування','Опис'],[[physical?button(label(physical),pg(32,{id:physical,role:'R02'}),true):'Не зареєстровано',file?btn('Переглянути файл','legacy-file-view'):'Не зареєстровано',esc(priorities[inv?.digitization_priority||'none']),esc(priorities[inv?.description_priority||'none'])]])+body(`<div class="actions">${btn('Зареєструвати носій','legacy-physical',!physical&&allowed(row.id,'physical.write')&&allowed(row.id,'legacy.write'))}${btn('Додати файл','legacy-file',!file&&allowed(row.id,'media.write')&&allowed(row.id,'legacy.write'))}${btn('Пріоритети та питання','legacy-triage',allowed(row.id,'legacy.write'))}${b?button('До партії',pg(21,{id:row.source_system_id,batch:b.id,role:'R02'}),true):''}</div>`)+(inv?.unresolved_note?body('<p><strong>Потрібно з’ясувати:</strong> '+esc(inv.unresolved_note)+'</p>'):'')+(tasks.length?table(['Завдання','Стан','Дія'],tasks.map(id=>{const w=by('work_item',id);return [esc(w.title),esc({open:'Відкрите',done:'Виконано',cancelled:'Скасовано',in_progress:'У роботі',blocked:'Заблоковано',assigned:'Призначено'}[w.state]),button('Відкрити завдання',pg(3,{id,role:'R02'}),true)];})):''));
 }
 return {list,record};
}
