import {can} from '../data/model.mjs?v=20260928-one-user';
import {museumEnabled,museumOwned,museumMaterials,museumReasons,setItems,setTexts,setIssues,setState,resolvePoint,museumAuthor,museumPrintView} from '../data/museum.mjs?v=20260928-one-user';
import {publicView,publicResources} from '../data/public.mjs?v=20260928-one-user';
import {museumRequestUI} from './museum-requests.mjs?v=20260928-one-user';
import {wizard} from './wizard.mjs?v=20260928-one-user';

export function museumPages(ctx){
 const {s,actor,scope,esc,pg,panel,heading,shell,dialog,render,flash,dispatch,denied}=ctx,st=s(),t=st.tables,p=new URLSearchParams(location.search);
 const by=(k,id)=>t[k].find(x=>x.id===id),rev=id=>by('entity',id)?.current_revision_id,own=(k)=>t[k].filter(x=>museumOwned(st,actor,x.id)&&(!scope||by('entity',x.id).archive_id===scope));
 const names={draft:'Чернетка',ready:'Готова',needs_review:'Потрібна перевірка',open:'Відкрита',closed:'Закрита',archived:'В архіві',active:'Активна',access_unavailable:'Недоступна'},kinds={printed_qr:'QR на етикетці',label:'Етикетка',interactive_panel:'Інтерактивна панель',kiosk:'Кіоск'},langs={uk:'Українська',en:'English',pl:'Polski',de:'Deutsch'};
 const badge=(state)=>`<span class="badge ${esc(state)}">${esc(names[state]||state)}</span>`;
 const link=(n,label,q={})=>`<a href="${pg(n,{role:'R05-M',...q})}">${esc(label)}</a>`,go=(n,q={})=>location.assign(pg(n,{role:'R05-M',...q}));
 const body=x=>`<div class="panel-body">${x}</div>`,details=rows=>`<dl class="detail-list">${rows.map(([k,v])=>`<div><dt>${esc(k)}</dt><dd>${esc(v||'Не зазначено')}</dd></div>`).join('')}</dl>`;
 const table=(heads,rows,empty)=>rows.length?`<div class="table-wrap media-table"><table><thead><tr>${heads.map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map((x,i)=>`<td data-label="${esc(heads[i])}">${x}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`:body(`<p class="muted">${esc(empty||'Поки немає записів.')}</p>`);
 const shortLabel=(name,label)=>/^(position|reason|note)-/.test(name)?label.split(' — ')[0]:label;
 const input=(name,label,value='',required=false,type='text')=>`<label>${esc(shortLabel(name,label))}<input aria-label="${esc(label)}" name="${name}" type="${type}" value="${esc(value)}" ${required?'required':''}></label>`;
 const textarea=(name,label,value='',required=false)=>`<label>${esc(label)}<textarea name="${name}" rows="4" ${required?'required':''}>${esc(value)}</textarea></label>`;
 const select=(name,label,rows,value='',blank=null)=>`<label>${esc(shortLabel(name,label))}<select aria-label="${esc(label)}" name="${name}" required>${blank!==null?`<option value="">${esc(blank)}</option>`:''}${rows.map(([id,title])=>`<option value="${esc(id)}" ${id===value?'selected':''}>${esc(title)}</option>`).join('')}</select></label>`;
 const actions={},act=(key,fn)=>actions[key]=fn,btn=(label,key,enabled=true,primary=false)=>`<button type="button" class="button ${primary?'':'secondary'}" data-museum-action="${key}" ${enabled?'':'disabled'}>${esc(label)}</button>`;
 const bind=()=>document.querySelectorAll('[data-museum-action]').forEach(el=>el.onclick=async()=>{try{await actions[el.dataset.museumAction]?.();}catch(e){flash(e.message,'error');render();}});
 const show=html=>{shell(html);bind();},done=message=>{flash(message);render();};
 const check=(k,id)=>museumOwned(st,actor,id)?by(k,id):null;
 const unavailable=()=>show(heading('Музей','Запис недоступний','Поверніться до переліку експозицій.')+link(56,'До експозицій'));
 const writable=ex=>!['closed','archived'].includes(ex.state);
 const setRows=rows=>table(['Добірка','Експонат','Матеріалів','Стан'],rows.map(x=>[link(58,x.title,{id:x.id}),esc(x.exhibit_title),setItems(st,x.id).length,badge(setState(st,x.id))]),'Додайте першу добірку при експонаті.');
 const pointTitle=x=>{const target=by('access_point_target',x.current_target_id);return by('exhibit_set',target?.target_entity_id)?.title||'Точка доступу';};
 const pointRows=rows=>table(['Точка доступу','Експозиція','Тип','Стан'],rows.map(x=>[link(60,pointTitle(x),{id:x.id}),esc(by('museum_exhibition',x.exhibition_id)?.title),esc(kinds[x.kind]),badge(x.state==='active'&&!resolvePoint(st,x.stable_token).available?'access_unavailable':x.state)]),'Точок доступу поки немає. Створіть точку для перевіреної добірки.');
 function createExhibition(old=null){
  const archives=t.archive.filter(x=>can(st,actor,'museum.write',x.id)&&(!scope||x.id===scope)),selected=old?by('entity',old.id).archive_id:archives[0]?.id;
  const institutions=id=>t.institution.filter(x=>by('entity',x.id).archive_id===id).map(x=>[x.id,x.name]);
  const d=wizard({dialog,esc},{title:old?'Редагувати експозицію':'Створити експозицію',submit:old?'Зберегти зміни':'Створити експозицію',steps:[
   {title:'Назва та установа',body:input('title','Назва експозиції',old?.title||'',true)+(old?'':select('archive_id','Архів',archives.map(x=>[x.id,x.name]),selected))+select('institution_id','Установа',institutions(selected),old?.institution_id||'')},
   {title:'Дати показу',body:input('opens_on','Дата відкриття',old?.opens_on||'',false,'date')+input('closes_on','Дата завершення',old?.closes_on||'',false,'date')+select('place_id','Місце',[['','Не зазначено'],...t.place.filter(x=>by('entity',x.id).archive_id===selected).map(x=>[x.id,x.name])],old?.place_id||'').replace(' required','')+select('responsible_person_id','Відповідальна особа',t.account.filter(x=>can(st,x.id,'museum.write',selected)).map(x=>[x.person_id,by('person',x.person_id)?.preferred_name]),old?.responsible_person_id||by('account',actor)?.person_id)+'<p class="muted">Для постійної експозиції дату завершення можна не зазначати.</p>'}
  ],summary:v=>details([['Експозиція',v.title],['Установа',by('institution',v.institution_id)?.name],['Відкриття',v.opens_on],['Завершення',v.closes_on||'Без визначеної дати']]),onSubmit:async v=>go(57,{id:(await dispatch({type:old?'museum.exhibition.save':'museum.exhibition.create',id:old?.id,expected_revision_id:old?rev(old.id):undefined,archive_id:selected,...v})).id})});
  d.querySelector('[name=archive_id]')?.addEventListener('change',e=>{const archive=e.target.value;d.querySelector('[name=institution_id]').innerHTML=institutions(archive).map(([id,name])=>`<option value="${id}">${esc(name)}</option>`).join('');d.querySelector('[name=place_id]').innerHTML='<option value="">Не зазначено</option>'+t.place.filter(x=>by('entity',x.id).archive_id===archive).map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('');d.querySelector('[name=responsible_person_id]').innerHTML=t.account.filter(x=>can(st,x.id,'museum.write',archive)).map(x=>`<option value="${x.person_id}">${esc(by('person',x.person_id)?.preferred_name)}</option>`).join('');});
 }
 const requests=museumRequestUI(ctx,{body,details,input,textarea,select,table,act,btn,show});
 function exhibitions(){
  if(p.get('tab')==='requests'||p.get('role')==='R02')return requests.list();
  act('new',createExhibition);const rows=own('museum_exhibition').filter(x=>(!p.get('state')||x.state===p.get('state'))&&x.title.toLocaleLowerCase('uk').includes((p.get('q')||'').toLocaleLowerCase('uk')));
  show(heading('Музейник','Експозиції','Створіть експозицію, додайте добірки при експонатах і перевірте їх перед відкриттям.',`<div class="public-actions">${btn('Створити експозицію','new',museumEnabled(st,actor),true)}${link(56,'Звернення до архіву',{tab:'requests'})}</div>`)+
   `<form class="filters"><input type="hidden" name="role" value="R05-M">${input('q','Знайти експозицію',p.get('q')||'')}${select('state','Стан',[['','Усі стани'],...['draft','open','closed','archived'].map(x=>[x,names[x]])],p.get('state')||'').replace(' required','')}<button class="button">Знайти</button></form>`+
   panel('Мої експозиції',table(['Експозиція','Добірок','Стан'],rows.map(x=>[link(57,x.title,{id:x.id}),t.exhibit_set.filter(y=>y.exhibition_id===x.id).length,badge(x.state)]),'Немає експозицій за цими умовами.')));
 }
 function changeExhibition(ex,state){dialog(({open:'Відкрити',closed:'Закрити',archived:'Архівувати'})[state]+' експозицію',`<p>${state==='open'?'Перевірені добірки стануть доступні за активними точками.':'Точки цієї експозиції буде заархівовано. Їхні посилання збережуть пояснення та назву архіву.'}</p>`+textarea('reason','Підстава','',true),async fd=>{await dispatch({type:'museum.exhibition.state',id:ex.id,expected_revision_id:rev(ex.id),state,reason:fd.get('reason')});done('Стан експозиції оновлено.');},({open:'Відкрити',closed:'Закрити',archived:'Архівувати'})[state]);}
 function exhibition(){
  if(!p.has('id'))return exhibitions();const ex=check('museum_exhibition',p.get('id'));if(!ex)return unavailable();
  const allSets=own('exhibit_set').filter(x=>x.exhibition_id===ex.id),sets=allSets.filter(x=>x.state!=='archived'),archived=allSets.filter(x=>x.state==='archived'),points=own('access_point').filter(x=>x.exhibition_id===ex.id),ready=sets.filter(x=>setState(st,x.id)==='ready').length,tab=p.get('tab')||'sets';
  act('edit-ex',()=>createExhibition(ex));act('request',()=>requests.create(ex));act('new-set',()=>editSet(ex));act('new-point',()=>editPoint(ex));act('open',()=>changeExhibition(ex,'open'));act('close',()=>changeExhibition(ex,'closed'));act('archive',()=>changeExhibition(ex,'archived'));
  show(link(56,'← Експозиції')+heading('Експозиція',ex.title,'Добірка пояснює зв’язок архівних матеріалів з експонатом. Після перевірки створіть постійне посилання для етикетки або кіоску.',`<div class="public-actions">${btn('Редагувати експозицію','edit-ex',writable(ex))}${btn('Звернутися до архіву','request',writable(ex))}${ex.state==='draft'?btn('Відкрити експозицію','open',!!sets.length&&ready===sets.length):ex.state==='open'?btn('Закрити експозицію','close'):ex.state==='closed'?btn('Архівувати експозицію','archive'):''}${ex.state==='draft'?btn('Архівувати експозицію','archive'):''}</div>`)+
   `<div class="museum-summary">${badge(ex.state)}<span>${esc(by('institution',ex.institution_id)?.name)}</span><span>Готові добірки: ${ready} із ${sets.length}</span></div>`+`<details class="museum-history"><summary>Про експозицію</summary>${details([['Місце',by('place',ex.place_id)?.name],['Відкриття',ex.opens_on],['Завершення',ex.closes_on],['Відповідальна особа',by('person',ex.responsible_person_id)?.preferred_name]])}</details>`+
   `<nav class="record-tabs" aria-label="Експозиція"><a href="${pg(57,{role:'R05-M',id:ex.id})}" ${tab==='sets'?'aria-current="page"':''}>Добірки (${sets.length})</a><a href="${pg(57,{role:'R05-M',id:ex.id,tab:'points'})}" ${tab==='points'?'aria-current="page"':''}>Точки доступу (${points.length})</a></nav>`+
   (tab==='points'?panel('Точки доступу',pointRows(points),btn('Створити точку','new-point',writable(ex)&&ready>0,true)):panel('Добірки при експонатах',setRows(sets),btn('Додати добірку','new-set',writable(ex),true)))+(archived.length?`<details class="museum-history"><summary>Архівні добірки (${archived.length})</summary>${setRows(archived)}</details>`:''));
 }
 function editSet(ex,old=null){
  const materials=museumMaterials(st),items=old?setItems(st,old.id):[],texts=old?setTexts(st,old.id):[],defaultLang=texts.find(x=>x.is_default)?.language_tag||'uk';
  const missing=items.filter(x=>!materials.some(m=>m.id===x.publication_id));
  const chosen=materials.filter(x=>items.some(i=>i.publication_id===x.id)),other=materials.filter(x=>!chosen.includes(x));chosen.sort((a,b)=>items.find(x=>x.publication_id===a.id).position-items.find(x=>x.publication_id===b.id).position);
  const d=wizard({dialog,esc},{title:old?'Редагувати добірку':'Додати добірку',submit:'Зберегти добірку',steps:[
   {title:'Експонат',body:(missing.length?`<p>Матеріалів, які більше недоступні для музейного показу: ${missing.length}. Вони залишаться в історії попередньої версії.</p><label><input type="checkbox" name="remove_unavailable" required>Вилучити недоступні матеріали з нової версії</label>`:'')+input('title','Назва добірки',old?.title||'',true)+input('exhibit_title','Назва експоната',old?.exhibit_title||'',true)+input('museum_inventory_number','Інвентарний номер',old?.museum_inventory_number||'')+input('museum_record_uri','Посилання на музейний запис',old?.museum_record_uri||'')},
   {title:'Матеріали та зв’язок з експонатом',body:materials.length?`<div class="museum-search">${input('material_query','Знайти матеріал','','', 'search')}${select('material_category','Тема',[['','Усі теми'],...[...new Set(materials.map(x=>x.category).filter(Boolean))].map(x=>[x,x])]).replace(' required','')}<button type="button" class="button secondary" data-selected-only aria-pressed="false">Лише обрані</button><p data-selection-count role="status"></p></div>`+[...chosen,...other].map((x,i)=>{const item=items.find(y=>y.publication_id===x.id);return `<fieldset class="museum-choice" data-material-card="${x.id}"><legend><label><input type="checkbox" name="materials" value="${x.id}" ${item?'checked':''}>${esc(x.title)}</label></legend><div class="form-grid">${input('position-'+x.id,'Порядок — '+x.title,item?.position||i+1,false,'number')}${select('reason-'+x.id,'Зв’язок — '+x.title,Object.entries(museumReasons),item?.link_reason||'same_ethnographic_region')}</div>${input('note-'+x.id,'Пояснення зв’язку — '+x.title,item?.reason_note||'')}<button type="button" class="button secondary" data-preview-material="${x.id}">Переглянути джерело</button></fieldset>`;}).join(''):'<p>Наразі немає матеріалів із дозволом на музейне використання.</p>'},
   {title:'Текст для відвідувача',body:`<p>Автор пояснення: ${esc(museumAuthor(st,by('account',actor)?.person_id)||'Публічне ім’я ще не погоджено')}</p>`+select('default_language','Основна мова',Object.entries(langs),defaultLang)+Object.entries(langs).map(([code,name])=>{const txt=texts.find(x=>x.language_tag===code),html=input('text-title-'+code,'Заголовок — '+name,txt?.title||'')+textarea('text-'+code,'Пояснення — '+name,txt?.curator_note||'');return code===defaultLang?html:`<details class="museum-translation"><summary>${esc(name)}</summary>${html}</details>`;}).join('')}
  ],summary:v=>details([['Добірка',v.title],['Експонат',v.exhibit_title],['Матеріалів',(v.materials||[]).length],['Основна мова',langs[v.default_language]],['Після збереження','Чернетка, яку потрібно перевірити']]),onSubmit:async v=>{
   const selected=(v.materials||[]).map(id=>({publication_id:id,publication_revision_id:materials.find(x=>x.id===id).revision_id,link_reason:v['reason-'+id],reason_note:v['note-'+id],order:Number(v['position-'+id])}));
   if(selected.some(x=>!Number.isInteger(x.order)||x.order<1)||new Set(selected.map(x=>x.order)).size!==selected.length)throw new Error('Зазначте різні додатні номери порядку.');selected.sort((a,b)=>a.order-b.order);
   const row=await dispatch({type:old?'museum.set.save':'museum.set.create',id:old?.id,expected_revision_id:old?rev(old.id):undefined,exhibition_id:ex.id,title:v.title,exhibit_title:v.exhibit_title,museum_inventory_number:v.museum_inventory_number,museum_record_uri:v.museum_record_uri,items:selected,texts:Object.keys(langs).filter(code=>v['text-'+code]?.trim()).map(code=>({language_tag:code,title:v['text-title-'+code],curator_note:v['text-'+code],is_default:code===v.default_language}))});go(58,{id:row.id});
  }});
  let selectedOnly=false;const update=()=>{const q=d.querySelector('[name=material_query]')?.value.toLocaleLowerCase('uk').trim()||'',category=d.querySelector('[name=material_category]')?.value||'';let visible=0;d.querySelectorAll('[data-material-card]').forEach(el=>{const x=materials.find(x=>x.id===el.dataset.materialCard),checked=el.querySelector('[type=checkbox]').checked;el.hidden=!!((selectedOnly&&!checked)||(category&&x.category!==category)||![x.title,x.summary,x.place,x.category].join(' ').toLocaleLowerCase('uk').includes(q));if(!el.hidden)visible++;});const count=d.querySelector('[data-selection-count]');if(count)count.textContent=`Показано: ${visible}. Обрано: ${d.querySelectorAll('[name=materials]:checked').length}.`;};
  d.querySelector('[name=material_query]')?.addEventListener('input',update);d.querySelector('[name=material_category]')?.addEventListener('change',update);d.querySelectorAll('[name=materials]').forEach(el=>el.addEventListener('change',update));d.querySelector('[data-selected-only]')?.addEventListener('click',e=>{selectedOnly=!selectedOnly;e.currentTarget.setAttribute('aria-pressed',String(selectedOnly));update();});d.querySelectorAll('[data-preview-material]').forEach(el=>el.onclick=()=>previewMaterial(el.dataset.previewMaterial));update();
 }
 function previewMaterial(id){
  const pub=publicView(s(),id,'museum');if(!pub){dialog('Джерело недоступне','<p>Доступ до матеріалу змінився. Оновіть добірку.</p>',null,'Закрити');return;}
  const resources=publicResources(s(),id,'museum');dialog('Перегляд джерела',`<h3>${esc(pub.title)}</h3><p>${esc(pub.summary||'')}</p>${details([['Місце',pub.place],['Період',pub.period],['Джерело',pub.attribution],['Умови використання',pub.terms]])}${resources.map(x=>`<article class="public-reader source-text">${esc(x.content)}</article>`).join('')||'<p>Оприлюднено лише опис.</p>'}<a href="${pg(50,{role:'R05',id:pub.id})}" target="_blank" rel="noopener">Відкрити архівний контекст ↗</a>`,null,'Закрити');
 }
 function reviewSet(row){
  const items=setItems(st,row.id),texts=setTexts(st,row.id);
  const d=dialog('Перевірити добірку',`<p>Підтвердьте добір матеріалів, зв’язки з експонатом і тексти всіма зазначеними мовами.</p><ul>${items.map(x=>`<li>${esc(publicView(st,x.publication_id,'museum')?.title)} — ${esc(museumReasons[x.link_reason])}${x.reason_note?`<p>${esc(x.reason_note)}</p>`:''}${details([['Джерело',publicView(st,x.publication_id,'museum')?.attribution],['Умови використання',publicView(st,x.publication_id,'museum')?.terms]])}<button type="button" class="button secondary" data-preview-material="${x.publication_id}">Переглянути джерело</button></li>`).join('')}</ul>${texts.map(x=>`<h3>${langs[x.language_tag]}</h3><p>${esc(x.curator_note)}</p><p>Автор: ${esc(museumAuthor(st,x.author_person_id))}</p>`).join('')}<label class="check"><input type="checkbox" name="confirm" required>Матеріали, підписи, мови та умови використання перевірено</label>`+textarea('reason','Підсумок перевірки','',true),async fd=>{await dispatch({type:'museum.set.review',id:row.id,expected_revision_id:rev(row.id),confirm:fd.has('confirm'),reason:fd.get('reason')});done('Добірку перевірено. Можна створити точку доступу.');},'Підтвердити готовність');
  d.querySelectorAll('[data-preview-material]').forEach(el=>el.onclick=()=>previewMaterial(el.dataset.previewMaterial));
 }
 function exhibitSet(){
  if(!p.has('id'))return exhibitions();const row=check('exhibit_set',p.get('id'));if(!row)return unavailable();const ex=by('museum_exhibition',row.exhibition_id),items=setItems(st,row.id),texts=setTexts(st,row.id),issues=setIssues(st,row.id),status=setState(st,row.id);
  act('archive-set',()=>changeSetState(row,false));act('restore-set',()=>changeSetState(row,true));act('edit',()=>editSet(ex,row));act('review',()=>reviewSet(row));act('point',()=>editPoint(ex,null,row.id));
  show(link(57,'← '+ex.title,{id:ex.id})+heading('Добірка при експонаті',row.title,'Редагуйте добірку у формі. Перевірка підтверджує саме цей склад і тексти; після змін її потрібно повторити.',`<div class="public-actions">${btn('Редагувати добірку','edit',writable(ex)&&status!=='archived')}${status==='archived'?btn('Відновити добірку','restore-set',writable(ex)):btn('Архівувати добірку','archive-set',writable(ex))}${status==='ready'?btn('Створити точку доступу','point',writable(ex),true):btn('Перевірити добірку','review',writable(ex)&&status!=='archived'&&!issues.length,true)}</div>`)+
   `<div class="museum-summary">${badge(status)}<span>Експонат: ${esc(row.exhibit_title)}</span>${row.museum_inventory_number?`<span>№ ${esc(row.museum_inventory_number)}</span>`:''}</div>`+
   (row.museum_record_uri?body(`<a href="${esc(row.museum_record_uri)}" target="_blank" rel="noopener">Запис у музейній системі ↗</a>`):'')+(issues.length?`<div class="notice warning"><ul>${issues.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`:'')+
   panel('Матеріали',table(['Порядок','Матеріал','Зв’язок з експонатом'],items.map(x=>{const pub=publicView(st,x.publication_id,'museum');return [x.position,pub?esc(pub.title):'<span class="muted">Матеріал недоступний</span>',esc(museumReasons[x.link_reason])+(pub&&x.reason_note?`<span class="sub">${esc(x.reason_note)}</span>`:'')];})))+
   panel('Тексти для відвідувача',body(texts.map(x=>`<article class="museum-text"><h3>${langs[x.language_tag]}${x.is_default?' · основна':''}</h3>${x.title?`<strong>${esc(x.title)}</strong>`:''}<p class="source-text">${esc(x.curator_note)}</p><p class="muted">Автор: ${esc(museumAuthor(st,x.author_person_id)||'Публічне ім’я ще не погоджено')}</p></article>`).join(''))));
 }
 function changeSetState(row,restore){const points=t.access_point.filter(x=>by('access_point_target',x.current_target_id)?.target_entity_id===row.id&&x.state==='active');dialog(restore?'Відновити добірку':'Архівувати добірку',`<p>${restore?'Добірка повернеться до чернеток. Перевірте її перед показом.':`Добірка залишиться в історії. Активні точки (${points.length}) тимчасово показуватимуть пояснення про недоступність; їх можна буде спрямувати на іншу добірку.`}</p>`+textarea('reason','Підстава','',true),async fd=>{await dispatch({type:restore?'museum.set.restore':'museum.set.archive',id:row.id,expected_revision_id:rev(row.id),reason:fd.get('reason')});done(restore?'Добірку відновлено як чернетку.':'Добірку заархівовано.');},restore?'Відновити':'Архівувати');}
 function editPoint(ex,old=null,setId=null){
  const sets=own('exhibit_set').filter(x=>x.exhibition_id===ex.id&&setState(st,x.id)==='ready');
  wizard({dialog,esc},{title:old?'Змінити ціль точки':'Створити точку доступу',submit:old?'Змінити ціль':'Створити точку',steps:[
   {title:'Добірка для показу',body:select('set_id','Добірка',sets.map(x=>[x.id,x.title]),setId||'')+(old?'':select('kind','Тип точки',Object.entries(kinds)))},
   {title:'Підстава',body:textarea('reason','Пояснення','',true)+(old?'<p>Надрукована адреса та QR-код залишаться тими самими.</p>':'')}
  ],summary:v=>details([['Експозиція',ex.title],['Добірка',by('exhibit_set',v.set_id)?.title],['Тип',kinds[old?.kind||v.kind]],['Підстава',v.reason]]),onSubmit:async v=>go(60,{id:(await dispatch({type:old?'museum.point.retarget':'museum.point.create',id:old?.id,expected_revision_id:old?rev(old.id):undefined,exhibition_id:ex.id,set_revision_id:rev(v.set_id),...v})).id})});
 }
 function points(){
  const ex=own('museum_exhibition'),selected=ex.find(x=>x.id===p.get('exhibition')),rows=own('access_point').filter(x=>(!selected||x.exhibition_id===selected.id)&&(!p.get('state')||x.state===p.get('state')));
  act('new',()=>{const options=ex.filter(x=>writable(x)&&own('exhibit_set').some(y=>y.exhibition_id===x.id&&setState(st,y.id)==='ready'));if(selected)return editPoint(selected);dialog('Оберіть експозицію',select('exhibition','Експозиція',options.map(x=>[x.id,x.title])),fd=>{setTimeout(()=>editPoint(ex.find(x=>x.id===fd.get('exhibition'))),0);},'Далі');});
  const enabled=ex.some(x=>(!selected||x.id===selected.id)&&writable(x)&&own('exhibit_set').some(y=>y.exhibition_id===x.id&&setState(st,y.id)==='ready'));
  show(heading('Музейник','Точки доступу','Кожна точка має постійну адресу. Відкрийте точку, щоб змінити добірку, перевірити вигляд для відвідувача або надрукувати QR.',btn('Створити точку доступу','new',enabled,true))+
   `<form class="filters"><input type="hidden" name="role" value="R05-M">${select('exhibition','Експозиція',[['','Усі експозиції'],...ex.map(x=>[x.id,x.title])],selected?.id||'').replace(' required','')}${select('state','Стан',[['','Усі стани'],...['active','archived'].map(x=>[x,names[x]])],p.get('state')||'').replace(' required','')}<button class="button">Показати</button></form>`+panel('Мої точки доступу',pointRows(rows)));
 }
 function saveFile(content,name,mime){const u=URL.createObjectURL(new Blob([content],{type:mime})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
 function printPreview(row){
  const current=museumPrintView(s(),actor,row.id);if(!current)throw new Error('Етикетка стосується попередньої або недоступної добірки. Перевірте ціль і підготуйте нову етикетку.');const svg=current.svg; // Read the committed file, including a just-created print.
  const label=`<section class="museum-print-label"><div class="museum-qr" style="width:${row.minimum_size_mm}mm;height:${row.minimum_size_mm}mm">${svg}</div><strong>${esc(row.archive_name)}</strong><p>Відкрийте матеріали до експоната</p><p class="museum-print-url">${esc(row.human_readable_url)}</p>${current.citation?`<p class="museum-print-citation source-text">${esc(current.citation)}</p>`:'<p>Цитування відсутнє у старій етикетці. Підготуйте нову.</p>'}</section>`;
  const d=dialog('Етикетка для друку',label+'<button type="button" class="button secondary" data-save-qr>Завантажити QR</button>',()=>{const area=document.createElement('div');area.id='museum-print-area';area.innerHTML=label;document.body.append(area);document.body.classList.add('printing-museum');const cleanup=()=>{area.remove();document.body.classList.remove('printing-museum');};window.addEventListener('afterprint',cleanup,{once:true});try{window.print();}finally{cleanup();}return false;},'Друкувати');
  d.querySelector('[data-save-qr]').onclick=()=>saveFile(svg,'museum-qr.svg','image/svg+xml');
 }
 function preparePrint(point){
  const stable=pg(61,{token:point.stable_token});
  wizard({dialog,esc},{title:'Підготувати етикетку',submit:'Підготувати етикетку',steps:[{title:'Розмір QR-коду',body:input('minimum_size_mm','Ширина QR, мм',40,true,'number')+`<p>Посилання: <span class="museum-url">${esc(stable)}</span></p><details class="page-help"><summary>Перед друком</summary><p>Цей локальний приклад відкривається на цьому комп’ютері. Для відвідувачів потрібні опублікований портал і спільне сховище даних.</p></details>`}],summary:v=>details([['QR',v.minimum_size_mm+' мм'],['Архів',by('archive',point.contact_archive_id)?.name],['Адреса',stable]]),onSubmit:async v=>{const row=await dispatch({type:'museum.point.print',id:point.id,expected_revision_id:rev(point.id),url:stable,minimum_size_mm:v.minimum_size_mm});setTimeout(()=>{render();printPreview(row);},0);}});
 }
 function point(){
  if(!p.has('id'))return points();const row=check('access_point',p.get('id'));if(!row)return unavailable();const ex=by('museum_exhibition',row.exhibition_id),target=by('access_point_target',row.current_target_id),set=by('exhibit_set',target.target_entity_id),available=resolvePoint(st,row.stable_token).available,prints=t.access_point_print.filter(x=>x.access_point_id===row.id);
  act('retarget',()=>editPoint(ex,row,set.id));act('print',()=>preparePrint(row));act('archive',()=>dialog('Архівувати точку',textarea('reason','Підстава','',true),async fd=>{await dispatch({type:'museum.point.archive',id:row.id,expected_revision_id:rev(row.id),reason:fd.get('reason')});done('Точку заархівовано.');},'Архівувати'));act('copy',async()=>{await navigator.clipboard.writeText(pg(61,{token:row.stable_token}));done('Посилання скопійовано.');});prints.forEach(x=>act('print-'+x.id,()=>printPreview(x)));
  show(link(57,'← '+ex.title,{id:ex.id,tab:'points'})+heading('Точка доступу',pointTitle(row),'Постійна адреса веде до перевіреної добірки. Зміна цілі зберігає цю адресу та попередню історію.',btn('Підготувати етикетку','print',row.state==='active'&&setState(st,set.id)==='ready'&&rev(set.id)===target.target_revision_id,true))+
   `<div class="museum-summary">${badge(row.state)}<span>${esc(kinds[row.kind])}</span></div>`+(!available?'<p class="notice warning">Показ для відвідувачів недоступний. Перевірте готовність добірки, ціль точки та відкриття експозиції.</p>':'')+
   panel('Поточна добірка',body(link(58,set.title,{id:set.id})),btn('Змінити ціль','retarget',writable(ex)&&row.state!=='archived'&&own('exhibit_set').some(x=>x.exhibition_id===ex.id&&setState(st,x.id)==='ready')))+
   panel('Постійне посилання',body(`<p class="museum-url">${esc(pg(61,{token:row.stable_token}))}</p><div class="public-actions">${btn('Скопіювати посилання','copy')}<a class="button secondary" href="${pg(61,{token:row.stable_token})}" target="_blank" rel="noopener">Перегляд відвідувача</a><a class="button secondary" href="${pg(62,{token:row.stable_token})}" target="_blank" rel="noopener">Відкрити кіоск</a></div>`))+
   panel('Етикетки',table(['Адреса','Розмір QR','Дія'],prints.map(x=>[`<span class="museum-url">${esc(x.human_readable_url)}</span>`,x.minimum_size_mm+' мм',btn('Відкрити етикетку','print-'+x.id)]),'Підготуйте етикетку для друку.'))+
   `<details class="museum-history"><summary>Історія зміни цілі (${t.access_point_target.filter(x=>x.access_point_id===row.id).length})</summary>${table(['Зміна','Добірка','Підстава'],t.access_point_target.filter(x=>x.access_point_id===row.id).map(x=>[x.target_version,esc(by('entity_revision',x.target_revision_id).snapshot.title),esc(x.reason)]))}</details><div class="public-actions">${btn('Архівувати точку','archive',row.state!=='archived')}</div>`);
 }
 function visitor(kiosk=false){
  const token=p.get('token'),view=resolvePoint(st,token,p.get('lang')||'uk');
  const visitorShell=html=>{const app=document.getElementById('app');app.className='museum-visitor'+(kiosk?' museum-kiosk':'');app.innerHTML=`<main id="main">${html}</main>`;bind();};
  if(!view.available){visitorShell(`<div class="museum-welcome">${kiosk?'<span class="brand">hereditas</span>':`<a class="brand" href="${pg(48,{role:'R05'})}">hereditas</a>`}<h1>Матеріали зараз недоступні</h1><p>${esc(view.message)}</p>${view.archive_name?`<p>Архів: ${esc(view.archive_name)}</p>`:''}${kiosk?`<a class="button secondary" href="${pg(62,{token})}">Перевірити доступність</a>`:''}</div>`);return;}
  const current=p.get('item'),item=view.items.find(x=>x.publication_id===current),home=pg(kiosk?62:61,{token,lang:view.language});
  visitorShell(`<header class="museum-visitor-head"><a class="brand" href="${home}">hereditas</a><span>${esc(view.exhibition_title)}</span><nav aria-label="Мова">${view.languages.map(code=>`<a href="${pg(kiosk?62:61,{token,lang:code,item:current})}" lang="${code}" ${code===view.language?'aria-current="page"':''}>${langs[code]}</a>`).join('')}</nav></header>`+
   (item?`<a class="button secondary" href="${home}">← До експоната</a><h1>${esc(item.title)}</h1>${!kiosk?`<div class="public-actions"><a class="button secondary" href="${pg(50,{role:'R05',id:item.publication_id})}">Архівний контекст і цитування</a><a class="button secondary" href="${pg(50,{role:'R05',id:item.publication_id,save:'1'})}">Зберегти до моєї добірки</a></div>`:''}<p>${esc(item.summary||'')}</p>${item.resources.length?item.resources.map(x=>`<article class="public-reader source-text">${esc(x.content)}</article>`).join(''):'<p>Для цього матеріалу доступний опис.</p>'}<p>${esc(item.attribution||'')}</p><p>${esc(item.terms||'')}</p>${item.citation?`<details><summary>Цитування</summary><p>${esc(item.citation)}</p></details>`:''}`:
   `<section class="museum-welcome"><p class="eyebrow">${esc(view.exhibit_title)}</p><h1>${esc(view.title)}</h1><p class="museum-intro">${esc(view.curator_note)}</p><p class="museum-author">Пояснення: ${esc(view.author_credit)}</p></section><section aria-label="Матеріали експоната" class="museum-tiles">${view.items.map((x,i)=>`<a class="museum-tile" href="${pg(kiosk?62:61,{token,lang:view.language,item:x.publication_id})}"><span class="eyebrow">${i+1} · ${esc(x.reason)}</span><h2>${esc(x.title)}</h2><p>${esc(x.reason_note||x.summary||'')}</p><span>Відкрити →</span></a>`).join('')}</section>`)+`<footer class="museum-visitor-footer">${esc(view.archive_name)}${kiosk?`<a class="button secondary" href="${home}">На початок</a>`:''}</footer>`);
 }
 return {'PG-56':exhibitions,'PG-57':exhibition,'PG-58':exhibitSet,'PG-59':points,'PG-60':point,'PG-61':()=>visitor(false),'PG-62':()=>visitor(true)};
}
