import {preservationStatus} from '../data/preservation.mjs?v=20261002-programmes';
import {fileBytes,MAX_MEDIA_BYTES} from '../data/binary.mjs?v=20261002-programmes';
import {download,encode} from './session-media.mjs?v=20261002-programmes';
import {wizard} from './wizard.mjs?v=20261002-programmes';

const mime=file=>file.type||({tif:'image/tiff',tiff:'image/tiff',wav:'audio/wav',flac:'audio/flac',mkv:'video/x-matroska',mov:'video/quicktime'}[file.name.split('.').at(-1).toLowerCase()]||'application/octet-stream');
async function selectedFile(d,selector='[data-copy-file]'){
 const f=d.querySelector(selector).files[0];if(!f)throw Error('Оберіть файл із вказаного місця зберігання.');if(!f.size||f.size>MAX_MEDIA_BYTES)throw Error('Оберіть файл до 2 МБ.');return encode(f);
}
const confirm='<label class="check-label"><input name="confirm" type="checkbox" required>Підтверджую перевірку вказаного місця</label>';

export function preservationUI(ctx){
 const {write,st,t,esc,dialog,input,select,choices,options,details,table,dispatch,render,flash,rev,archive,pg,button,btn,action,allowed,visible,by,panel,body,heading,show,label,params,date,badge}=ctx;
 const done=message=>{flash(message);render();};
 const picker='<label>Файл із місця зберігання<input type="file" data-copy-file></label>';
 function ingest(rep=null){
  let chosen=[];
  const d=wizard({dialog,esc},{title:rep?'Додати похідне представлення':'Прийняти цифрові файли',submit:'Зберегти файли',steps:[
   {title:rep?'Походження перетворення':'Матеріал і походження',body:(rep?select('role','Роль представлення',choices({access_derivative:'Копія для перегляду',preservation_master:'Майстер для збереження',mezzanine:'Проміжна копія',thumbnail:'Мініатюра'},'access_derivative'))+input('operation','Інструмент, версія та параметри перетворення','','textarea',true):input('title','Назва ресурсу','','text',true)+select('subject_id','Пов’язаний матеріал','<option value="">Пов’язати пізніше</option>'+options(['physical_object','collecting_session','information_unit','document'].flatMap(visible))))+input('description','Відомості про походження','','textarea',true,'Хто передав файли, звідки їх отримано та де зафіксовано підставу приймання. Публікація і права оформлюються окремо.')},
   {title:'Файли',body:'<label>Оберіть файли<input type="file" multiple data-ingest-files></label><div data-ingest-list></div><details><summary>Як підготувати файли</summary><p>До 2 МБ за одне збереження. Зазначте первісний шлях для кожного файла. За наявності контрольної суми від відправника додайте її для звірки. Порядок у списку стане порядком представлення.</p></details><label class="check-label"><input name="confirm" type="checkbox" required>Підтверджую походження та порядок файлів</label>'}
  ],summary:v=>details([['Ресурс',rep?label(rep.asset_id):v.title],['Кількість файлів',chosen.length],['Обсяг',chosen.reduce((n,f)=>n+f.size,0)+' байт'],['Походження',v.description],['Перетворення',v.operation||'Отриманий оригінал']]),onSubmit:async v=>{
   if(!chosen.length)throw Error('Оберіть файли.');if(chosen.reduce((n,f)=>n+f.size,0)>MAX_MEDIA_BYTES)throw Error('За одне збереження можна додати до 2 МБ.');
   const files=await Promise.all(chosen.map(async(f,i)=>({filename:f.name,mime_type:mime(f),content:await encode(f),source_path:v['path_'+i],expected_sha256:v['hash_'+i]})));
   const result=await dispatch({type:rep?'media.derivative':'media.ingest',archive_id:archive,representation_id:rep?.id,expected_revision_id:rep&&rev(rep.id),title:v.title,description:v.description,subject_id:v.subject_id,role:v.role,operation:rep?v.operation+'; '+v.description:null,files,confirm:v.confirm.length>0});location.href=pg(38,{id:result.id,representation:result.representation_id});
  }});
  d.querySelector('[data-ingest-files]').onchange=e=>{chosen=[...e.target.files];d.querySelector('[data-ingest-list]').innerHTML=chosen.map((f,i)=>`<fieldset><legend>${i+1}. ${esc(f.name)} · ${f.size} байт</legend>`+input('path_'+i,'Первісний шлях '+(i+1),f.webkitRelativePath||f.name,'text',true)+input('hash_'+i,'Очікувана SHA-256 '+(i+1),'','text',false)+'</fieldset>').join('');};
 }
 function thumbnail(rep){
  const files=t.representation_file.filter(x=>x.representation_id===rep.id).map(x=>by('file_object',x.file_id)).filter(x=>/^image\/(png|jpeg|webp)$/.test(x.mime_type));
  if(!files.length)throw Error('Для мініатюри потрібне зображення PNG, JPEG або WebP.');
  const d=dialog('Створити мініатюру',select('file_id','Джерельне зображення',options(files))+select('size','Довша сторона',choices({'320':'320 px','640':'640 px','1280':'1280 px'},'640'))+'<details><summary>Що збережеться</summary><p>Зображення буде зменшено зі збереженням пропорцій у PNG. Походження посилатиметься на поточну версію представлення та обраний файл.</p></details>',async fd=>{
   const f=by('file_object',fd.get('file_id')),image=await createImageBitmap(new Blob([fileBytes(st.demo.file_contents[f.id])],{type:f.mime_type}));let blob,width,height;
   try{if(image.width*image.height>40000000)throw Error('Зображення завелике для браузерного перетворення.');const ratio=Math.min(1,Number(fd.get('size'))/Math.max(image.width,image.height)),canvas=document.createElement('canvas');width=canvas.width=Math.max(1,Math.round(image.width*ratio));height=canvas.height=Math.max(1,Math.round(image.height*ratio));canvas.getContext('2d').drawImage(image,0,0,width,height);blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));}finally{image.close();}
   if(!blob||blob.size>MAX_MEDIA_BYTES)throw Error('Оберіть менший розмір мініатюри.');
   const result=await dispatch({type:'media.derivative',representation_id:rep.id,expected_revision_id:rev(rep.id),role:'thumbnail',operation:`Canvas 2D / PNG; ${width}×${height}; джерело ${f.original_filename}, SHA-256 ${f.sha256}`,confirm:true,files:[{filename:f.original_filename.replace(/\.[^.]+$/,'')+'-thumbnail.png',mime_type:'image/png',content:await encode(blob),source_path:'derived/'+f.id}]});location.href=pg(38,{id:result.id,representation:result.representation_id});
  },'Створити');return d;
 }
 function preservation(files,selected,packageRow){
  const scoped=selected?[selected]:files,q=(params.get('q')||'').toLocaleLowerCase('uk'),filter=params.get('state')||'',shown=scoped.filter(f=>{const s=preservationStatus(st,f.id);return f.original_filename.toLocaleLowerCase('uk').includes(q)&&(!filter||(filter==='ready'?s.ready:!s.ready));});
  const rows=visible('storage_copy').filter(x=>shown.some(f=>f.id===x.file_id));
  const external=t.digital_storage_location.filter(x=>x.storage_kind!=='browser-local');
  action('location',()=>dialog('Додати місце зберігання',input('name','Назва місця','','text',true)+input('failure_domain','Група спільного ризику','','text',true,'Копії на одному диску або залежних сховищах мають однакову групу. Іншу групу зазначайте лише для незалежного носія чи місця.')+input('notes','Носій, відповідальний та підстава незалежності','','textarea',true),async fd=>{await dispatch({type:'media.storage.location',archive_id:archive,...Object.fromEntries(fd)});done('Місце зберігання додано.');}));
  action('copy',()=>{
   const d=dialog('Додати перевірену копію',select('file_id','Оригінальний файл',options(files,selected?.id))+'<button class="button secondary" type="button" data-export>Завантажити оригінал</button>'+select('location_id','Місце копії',options(external,'',x=>x.name))+input('storage_key','Шлях копії','','text',true)+picker+confirm+'<details><summary>Як створити копію</summary><p>Завантажте оригінал і збережіть у вибраному місці. Потім оберіть збережений там файл для повторного читання. Назва місця сама по собі не підтверджує наявності резерву.</p></details>',async fd=>{const result=await dispatch({type:'media.copy',file_id:fd.get('file_id'),location_id:fd.get('location_id'),storage_key:fd.get('storage_key'),content:await selectedFile(d),confirm:fd.has('confirm')});done(result.result==='match'?'Копію перевірено: контрольна сума збігається.':'Копія не збігається. Створено питання для перевірки.');},'Перевірити та зберегти');
   d.querySelector('[data-export]').onclick=()=>{const f=by('file_object',d.querySelector('[name=file_id]').value);download(st.demo.file_contents[f.id],f.mime_type,f.original_filename);};
  });
  for(const f of scoped){
   action('plan-'+f.id,()=>{const status=preservationStatus(st,f.id);dialog('План збереження',input('required_copies','Незалежних копій потрібно',status.required,'number',true)+input('check_interval_days','Повторна перевірка через, днів',status.days,'number',true)+input('reason','Підстава зміни плану','','textarea',true),async fd=>{await dispatch({type:'media.preservation.plan',file_id:f.id,expected_plan_id:status.plan?.id||null,...Object.fromEntries(fd)});done('План збереження оновлено.');});});
   action('export-'+f.id,()=>download(st.demo.file_contents[f.id],f.mime_type,f.original_filename));
  }
  rows.forEach(x=>{
   action('fixity-'+x.id,()=>{
    const d=dialog('Перевірити копію',details([['Файл',label(x.file_id)],['Місце',by('digital_storage_location',x.storage_location_id).name],['Шлях',x.storage_key]])+select('status','Доступність копії',choices({readable:'Файл доступний для читання',missing:'Файл відсутній',unreadable:'Не вдалося прочитати'},'readable'))+picker+input('notes','Спостереження','','textarea')+confirm,async fd=>{const result=await dispatch({type:'media.fixity',id:x.id,expected_revision_id:rev(x.id),status:fd.get('status'),content:fd.get('status')==='readable'?await selectedFile(d):null,notes:fd.get('notes'),confirm:fd.has('confirm')});done(result.result==='match'?'Контрольна сума та розмір збігаються.':'Розбіжність збережено; відкрито питання щодо копії.');},'Записати перевірку');
    d.querySelector('[name=status]').onchange=e=>{d.querySelector('[data-copy-file]').disabled=e.target.value!=='readable';};
   });
   action('restore-'+x.id,()=>{
    const candidates=t.storage_copy.filter(r=>r.file_id===x.file_id&&r.id!==x.id&&by('digital_storage_location',r.storage_location_id).failure_domain!==by('digital_storage_location',x.storage_location_id).failure_domain);
    if(!candidates.length)throw Error('Спочатку додайте копію в незалежному місці зберігання.');
    const d=dialog('Перевірити відновлення',details([['Цільове місце',by('digital_storage_location',x.storage_location_id).name],['Шлях',x.storage_key]])+select('source_copy_id','Резервна копія',options(candidates,'',r=>by('digital_storage_location',r.storage_location_id).name+' · '+r.storage_key))+picker+input('notes','Підстава перевірки відновлення','','textarea',true)+confirm+'<details><summary>Як завершити відновлення</summary><p>Прочитайте резерв із вибраного місця. Якщо байти збігаються з оригіналом, завантажиться відновлений файл. Збережіть його в цільовому місці та виконайте «Перевірити» для цільової копії. До цього її стан не зміниться.</p></details>',async fd=>{const content=await selectedFile(d),source=fd.get('source_copy_id'),result=await dispatch({type:'media.restore',id:x.id,expected_revision_id:rev(x.id),source_copy_id:source,expected_source_revision_id:rev(source),content,notes:fd.get('notes'),confirm:fd.has('confirm')});if(result.ok){const f=by('file_object',x.file_id);download(content,f.mime_type,f.original_filename);}done(result.ok?'Файл відновлено для завантаження. Збережіть його в цільовому місці та перевірте копію.':'Відновлення не пройшло: резерв пошкоджений.');},'Перевірити й завантажити');
   });
  });
  action('report',()=>{const fileIds=new Set(scoped.map(f=>f.id)),copyIds=new Set(t.storage_copy.filter(c=>fileIds.has(c.file_id)).map(x=>x.id)),repIds=new Set(t.representation_file.filter(x=>fileIds.has(x.file_id)).map(x=>x.representation_id)),report={format:'hereditas-preservation/1',exported_at:new Date().toISOString(),files:scoped,plans:(t.preservation_plan||[]).filter(x=>fileIds.has(x.file_id)),occurrences:t.file_ingest_occurrence.filter(x=>fileIds.has(x.file_id)),representations:t.representation.filter(x=>repIds.has(x.id)),derivations:t.representation_derivation.filter(x=>repIds.has(x.output_representation_id)),copies:t.storage_copy.filter(x=>copyIds.has(x.id)),locations:t.digital_storage_location.filter(x=>t.storage_copy.some(c=>copyIds.has(c.id)&&c.storage_location_id===x.id)),fixity:t.fixity_check.filter(x=>copyIds.has(x.copy_id)),recovery:t.storage_recovery_check.filter(x=>copyIds.has(x.copy_id))};download(JSON.stringify(report,null,2),'application/json','preservation-report.json');});
  show(heading('Збереження',selected?selected.original_filename:'Цифрові копії та перевірки','Збережіть файл у незалежному місці та прочитайте копію для звірки. Перевірки виконуються з обраними вами файлами.',btn('Додати копію','copy',!!files.length&&allowed(files[0].id,'media.write'))+' '+btn('Додати місце','location',write)+' '+btn('Звіт','report'))+
   (selected?body(button('Усі файли',pg(39),true)):!files.length?body(button('Прийняти файли',pg(37),true)):'')+
   (packageRow?body(button('До надходження',pg(10,{role:'R02'}),true)):'')+
   `<form class="filters"><input type="hidden" name="role" value="R03">${selected?`<input type="hidden" name="id" value="${selected.id}">`:''}${packageRow?`<input type="hidden" name="handover" value="${packageRow.id}">`:''}${input('q','Пошук файла',params.get('q')||'')}${select('state','Стан збереження',choices({'':'Усі',attention:'Потребують уваги',ready:'План виконано'},filter))}<button class="button">Знайти</button></form>`+
   panel('План збереження',table(['Файл','Перевірені незалежні копії','Наступний крок',''],shown.map(f=>{const s=preservationStatus(st,f.id),rep=t.representation.find(r=>t.representation_file.some(x=>x.file_id===f.id&&x.representation_id===r.id));return [button(f.original_filename,pg(39,{id:f.id}),true),`${s.independent} із ${s.required}<span class="sub">Перевіряти кожні ${s.days} днів</span>`,!s.qualityReady?button('Пройти контроль якості',pg(36,{id:rep?.id}),true):s.ready?'План виконано':`Перевірити / додати копії${s.confirmed.length?'':' — немає актуальної перевірки'}`,btn('План','plan-'+f.id,allowed(f.id,'media.write'))+' '+btn('Завантажити','export-'+f.id)+(rep?' '+button('Ресурс',pg(38,{id:rep.asset_id,representation:rep.id}),true):'')];})))+
   panel('Копії',table(['Файл','Місце / шлях','Стан','Остання перевірка',''],rows.map(x=>{const check=t.fixity_check.filter(c=>c.copy_id===x.id).at(-1),loc=by('digital_storage_location',x.storage_location_id),confirmed=preservationStatus(st,x.file_id).confirmed.some(c=>c.id===x.id);return [esc(label(x.file_id)),esc(loc.name)+`<span class="sub">${esc(loc.storage_kind==='browser-local'?label(x.file_id):x.storage_key)}</span><span class="sub">Група ${[...new Set(t.digital_storage_location.map(l=>l.failure_domain))].indexOf(loc.failure_domain)+1}</span>`,badge(x.state)+(confirmed?'':'<span class="sub">Потрібна актуальна перевірка</span>'),check?badge(check.result)+`<span class="sub">${esc(date(check.checked_at))}</span>`:'Ще не перевірено',btn('Перевірити','fixity-'+x.id,allowed(x.id,'media.write'))+' '+btn('Відновлення','restore-'+x.id,allowed(x.id,'media.write'))];})))+
   '<details class="record-history"><summary>Історія цілісності та відновлення</summary>'+panel('Цілісність',table(['Файл','Результат','Дата / доказ'],t.fixity_check.filter(x=>rows.some(r=>r.id===x.copy_id)).slice().reverse().map(x=>[esc(label(by('storage_copy',x.copy_id).file_id)),badge(x.result),esc(date(x.checked_at))+'<span class="sub">'+esc(x.evidence_method==='selected-file'?'Прочитано обраний файл':x.evidence_method==='browser-ingest'?'Прийнято байти в браузер':x.evidence_method==='reported-unavailable'?'Повідомлено про недоступність':'Попередній запис; потрібна повторна перевірка')+'</span>'])))+panel('Відновлення',table(['Результат','Примітка','Дата'],t.storage_recovery_check.filter(x=>rows.some(r=>r.id===x.copy_id)).slice().reverse().map(x=>[badge(x.result),esc(x.notes),esc(date(x.checked_at))])))+'</details>'+
   (selected?'<details class="record-history"><summary>Походження та план</summary>'+table(['Первісна назва','Первісний шлях','Прийнято'],t.file_ingest_occurrence.filter(x=>x.file_id===selected.id).map(x=>[esc(x.received_filename),esc(x.source_path||'Не зазначено'),esc(date(x.received_at))]))+table(['Копій / інтервал','Підстава'],(t.preservation_plan||[]).filter(x=>x.file_id===selected.id).map(x=>[`${x.required_copies} / ${x.check_interval_days} днів`,esc(x.reason)]))+'</details>':'')+
   body('<details><summary>Як працювати зі збереженням</summary><p>У план зараховуються лише актуальні перевірки фактичних байтів. Старі приклади копій потрібно перечитати. Фізичну незалежність місць підтверджує відповідальний. Браузер не підключається до віддалених дисків; автоматичне резервування й фонові перевірки тут не виконуються.</p></details>'));
 }
 return {ingest,thumbnail,preservation};
}
