import {processingOperations,processingInputs,processingSource,processingDecision,processingProblem,processingJob} from '../data/processing.mjs?v=20261002-programmes';
import {mediaPreview,download} from './session-media.mjs?v=20261002-programmes';
import {wizard} from './wizard.mjs?v=20261002-programmes';
export function processingPage(ctx){
 const {st,t,p,actor,scope,esc,pg,dialog,dispatch,done,denied,by,reg,rev,allowed,some,btn,act,link,go,body,input,area,options,select,checks,details,table,show,heading,panel}=ctx;
 const sourceLabel=id=>processingSource(st,id),labelState={running:'Очікує результату',succeeded:'Результат отримано',failed:'Не виконано'},candidateState={pending:'Очікує перевірки',deferred:'Відкладено',accepted:'Прийнято',corrected:'Виправлено',rejected:'Відхилено'},kind={text:'Текст',segmentation:'Часові межі та мовці',metadata:'Метадані'},metadataKind={language:'Мова',person:'Особа',place:'Місце',date:'Дата',topic:'Тема'};
 const allSources=t.entity.filter(e=>!e.retired_at&&allowed('processing.run',e.id)&&processingInputs(st,e.id).length),sourceOptions=allSources.map(e=>[e.id,sourceLabel(e.id)+(processingDecision(st,e.id)?'':' — потрібен дозвіл')]);
 function prepare(previous=null){
  if(!allSources.length)return;const selected=allSources.find(x=>x.id===(previous?.job?.source_id||p.get('source')))||allSources[0];
  const ops=id=>{const inputs=processingInputs(st,id);return Object.entries(processingOperations).filter(([k])=>inputs.every(x=>k==='stt'?/^(audio|video)\//.test(x.mime_type):['ocr','htr'].includes(k)?x.mime_type.startsWith('image/'):x.mime_type==='text/plain'));};
  const d=wizard({dialog,esc},{title:previous?'Повторити обробку':'Підготувати обробку',submit:'Створити завдання',steps:[
   {title:'Джерело',body:select('source_id','Матеріал',sourceOptions,selected.id)+select('operation','Що розпізнати',ops(selected.id),previous?.operation)+'<div data-processing-inputs></div><div data-processing-rights></div>'},
   {title:'Контекст',body:input('language_hint','Очікувана мова (код або auto)',previous?.job?.parameters.language_hint||'auto',false)+area('context','Мовний або предметний контекст',previous?.job?.parameters.context||'',false)+'<label class="check-label"><input type="checkbox" name="speakers_requested">Потрібне розділення мовців</label><details><summary>Спосіб обробки</summary><p>Завантажте завдання, обробіть його локальним інструментом і додайте файл результату. Вхідні версії та контрольні суми будуть звірені. Не кожен інструмент визначає мовців; невідомі дані залишаться невідомими.</p><p>Локальний засіб у проєкті: tools/process_master_job.py. Інструкція — mockups/master/PROCESSING.md. Файли не надсилаються у хмарну модель.</p></details><label class="check-label"><input type="checkbox" name="confirm" required>Підтверджую склад і локальний спосіб обробки</label>'}
  ],summary:v=>details([['Джерело',sourceLabel(v.source_id)],['Операція',processingOperations[v.operation]],['Файлів',processingInputs(st,v.source_id).length],['Дозвіл',processingDecision(st,v.source_id)?'Чинний':'Потрібно оформити'],['Результат','Пропозиції для людської перевірки']]),onSubmit:async v=>{const r=await dispatch({type:'workbench.processing.start',...v,expected_revision_id:rev(v.source_id),speakers_requested:v.speakers_requested.length>0,confirm:v.confirm.length>0,retry_of:previous?.id||null});go(40,{id:r.id});}});
  const update=()=>{const id=d.querySelector('[name=source_id]').value;d.querySelector('[name=operation]').innerHTML=options(ops(id),previous?.operation);d.querySelector('[data-processing-inputs]').innerHTML=table(['Файл','Розмір'],processingInputs(st,id).map(f=>[esc(f.filename),f.byte_size+' байт']));d.querySelector('[data-processing-rights]').innerHTML=processingDecision(st,id)?'<p>Дозвіл на обробку чинний.</p>':`<p>Потрібен дозвіл на обробку саме цього матеріалу. ${link(26,'Оформити дозвіл',{role:'R02',source:id,purpose:'processing'})}</p>`;};d.querySelector('[name=source_id]').onchange=update;update();
 }
 function importResult(run){
  let result=null;const d=dialog('Додати результат обробки','<label>Файл результату<input type="file" accept="application/json,.json" data-process-result required></label><div data-result-summary></div><label class="check-label"><input name="confirm" type="checkbox" required>Звірено інструмент і походження результату</label>',async fd=>{if(!result)throw Error('Оберіть файл результату.');if(!fd.has('confirm'))throw Error('Підтвердьте походження.');await dispatch({type:'workbench.processing.finish',id:run.id,result});done('Результат збережено. Пропозиції очікують людської перевірки.');},'Додати пропозиції');
  d.querySelector('[data-process-result]').onchange=async e=>{result=null;const target=d.querySelector('[data-result-summary]');try{const f=e.target.files[0];if(!f||f.size>2000000)throw Error('Оберіть JSON до 2 МБ.');const parsed=JSON.parse(await f.text());if(parsed.format!=='hereditas-processing-result/1'||parsed.job_id!==run.id||parsed.job_digest!==run.job_digest)throw Error('Це результат іншого завдання.');result=parsed;target.innerHTML=details([['Стан',labelState[result.state]||'Невідомий'],['Інструмент',result.provenance?.tool_name],['Версія',result.provenance?.tool_version],['Модель',result.provenance?.model_name||'Не зазначено'],['Результатів',result.outputs?.length||0],['Помилка',result.error||'Немає']]);}catch(error){target.textContent=error.message;}};
 }
 function review(candidate){
  const v=candidate.proposed_payload,run=by('process_run',candidate.process_run_id),file=run.job.inputs.find(x=>x.id===v.file_id),content=st.demo.file_contents[v.file_id],source=content?mediaPreview(content,file.mime_type,esc):'<pre class="reading-text">'+esc(by('entity_revision',file.revision_id)?.snapshot.body_text||'')+'</pre>';
  const fields=v.type==='text'?area('body_text','Текст після звірки',v.text)+input('language_tag','Мова тексту',v.language_tag||'und'):v.type==='metadata'?details([['Поле',metadataKind[v.metadata_kind]],['Дослівний доказ',v.evidence]])+input('value','Значення після звірки',v.value):table(['Початок, мс','Кінець, мс','Текст / мовець'],v.segments.map((s,i)=>[input('start_'+i,'Початок '+(i+1),s.start_ms,true,'number'),input('end_'+i,'Кінець '+(i+1),s.end_ms,true,'number'),area('text_'+i,'Текст фрагмента '+(i+1),s.text)+input('speaker_'+i,'Позначка мовця '+(i+1),s.speaker_label||'',false)]));
  const d=dialog('Перевірити: '+kind[v.type],'<details><summary>Порівняти з джерелом</summary>'+source+'</details><button class="button secondary" type="button" data-review-download>Завантажити джерело</button>'+details([['Файл',file.filename],['Інструмент',run.tool_name],['Впевненість',candidate.confidence==null?'Не надано':candidate.confidence]])+fields+select('decision','Рішення',[['defer','Відкласти'],['accept','Прийняти без змін'],['correct','Прийняти виправлення'],['reject','Відхилити']])+area('reason','Підстава рішення')+'<label class="check-label"><input name="confirm" type="checkbox" required>Я звірив пропозицію з джерелом</label>',async fd=>{const values=Object.fromEntries(fd),segments=v.type==='segmentation'?v.segments.map((_,i)=>({start_ms:Number(values['start_'+i]),end_ms:Number(values['end_'+i]),text:values['text_'+i],speaker_label:values['speaker_'+i]||null})):null;await dispatch({type:'workbench.processing.review',id:candidate.id,expected_revision_id:rev(candidate.id),decision:values.decision,body_text:values.body_text,language_tag:values.language_tag,value:values.value,segments,reason:values.reason,confirm:fd.has('confirm')});done('Людське рішення збережено.');},'Зберегти рішення');
  d.querySelector('[data-review-download]').onclick=()=>download(content||by('entity_revision',file.revision_id)?.snapshot.body_text,file.mime_type,file.filename);
 }
 if(!some('processing.run')&&!some('text.review'))return denied();
 const rows=t.process_run.filter(x=>x.job?allowed('processing.run',x.job.source_id)||allowed('text.review',x.job.source_id):t.process_input.some(v=>v.process_run_id===x.id&&allowed('processing.run',v.entity_id))),run=rows.find(x=>x.id===p.get('id'));if(p.has('id')&&!run)return denied();
 act('start',()=>prepare());
 if(!run){const state=p.get('state')||'',q=(p.get('q')||'').toLocaleLowerCase('uk'),filtered=rows.filter(x=>(!state||x.state===state)&&sourceLabel(x.job?.source_id||t.process_input.find(v=>v.process_run_id===x.id)?.entity_id).toLocaleLowerCase('uk').includes(q));show(heading('Опрацювання','Машинне опрацювання','Підготуйте завдання, додайте фактичний результат і перевірте кожну пропозицію.',btn('Підготувати обробку','start',!!allSources.length))+`<form class="filters"><input type="hidden" name="role" value="R03">${input('q','Пошук джерела',p.get('q')||'',false)}${select('state','Стан',[['','Усі'],...Object.entries(labelState)],state)}<button class="button">Знайти</button></form>`+panel('Запуски',table(['Операція','Джерело','Стан','Пропозиції'],filtered.map(x=>[link(40,processingOperations[x.operation]||x.operation,{id:x.id}),esc(sourceLabel(x.job?.source_id||t.process_input.find(v=>v.process_run_id===x.id)?.entity_id)),esc(x.job?labelState[x.state]:'Попередній навчальний запис'),String(t.candidate.filter(c=>c.process_run_id===x.id&&['pending','deferred'].includes(c.state)).length)])))+body(link(37,'Додати цифрові файли',{role:'R03'})+' · '+link(26,'Умови використання',{role:'R02'})));return;}
 if(!run.job){show(link(40,'← Усі запуски')+heading('Історія','Попередній навчальний запуск','Запис збережено для історії. Нові завдання працюють із фактичними файлами.',btn('Підготувати обробку','start',!!allSources.length))+body(details([['Інструмент',run.tool_name],['Стан',run.state]])));return;}
 const problem=processingProblem(st,run),write=allowed('processing.run',run.job.source_id),candidates=t.candidate.filter(x=>x.process_run_id===run.id),outputs=run.result_payload?.outputs||[];
 act('retry',()=>prepare(run));act('import',()=>importResult(run));act('job',async()=>{try{download(JSON.stringify(await processingJob(st,actor,run.id),null,2),'application/json','processing-job.json');}catch(error){done(error.message);}});
 act('result',()=>download(JSON.stringify(run.result_payload,null,2),'application/json','processing-result.json'));
 act('cancel',()=>dialog('Завершити без результату',area('reason','Причина'),async fd=>{await dispatch({type:'workbench.processing.cancel',id:run.id,reason:fd.get('reason')});done('Завдання завершено без результату.');},'Завершити'));
 candidates.forEach(c=>act('review-'+c.id,()=>review(c)));
 candidates.filter(c=>c.proposed_payload.type==='segmentation'&&c.proposed_entity_id).forEach(c=>act('layer-'+c.id,()=>{const layer=by('timed_layer',c.proposed_entity_id),file=run.job.inputs.find(x=>x.id===c.proposed_payload.file_id),entries=t.timed_layer_entry.filter(x=>x.layer_revision_id===rev(layer.id)),d=dialog('Перевірений часовий шар',mediaPreview(st.demo.file_contents[file.id],file.mime_type,esc)+table(['Фрагмент','Текст','Мовець'],entries.map((e,i)=>{const seg=by('entity_revision',e.segment_revision_id).snapshot;return [`<button type="button" class="button secondary" data-play="${i}">${seg.start_ms/1000}–${seg.end_ms/1000} с</button>`,esc(e.text_value),esc(e.speaker_label||'Не визначено')];})),null,'Закрити');d.querySelectorAll('[data-play]').forEach(b=>b.onclick=()=>{const seg=by('entity_revision',entries[Number(b.dataset.play)].segment_revision_id).snapshot,player=d.querySelector('audio,video');if(player){player.currentTime=(seg.start_ms-(file.offset_ms||0))/1000;player.ontimeupdate=()=>{if(player.currentTime>=(seg.end_ms-(file.offset_ms||0))/1000)player.pause();};player.play().catch(()=>{});}});}));

 const actions=run.state==='running'?btn('Завантажити завдання','job',write&&!problem)+' '+btn('Додати результат','import',write&&!problem)+' '+btn('Завершити без результату','cancel',write):btn('Повторити','retry',write)+' '+(run.result_payload?btn('Завантажити результат','result'):'');
 show(link(40,'← Усі запуски')+heading('Обробка',sourceLabel(run.job.source_id),'Кожна пропозиція має власне людське рішення. Неперевірені результати не змінюють архівний опис.',actions)+(problem?`<div class="notice warning">${esc(problem)}</div>`:'')+body(details([['Операція',processingOperations[run.operation]],['Стан',run.cancelled?'Завершено без результату':labelState[run.state]],['Помилка',run.error||'Немає'],['Попередній запуск',run.job.retry_of?'Є повтором попередньої обробки':'Немає']]))+
  panel('Вхідні файли',table(['Файл','Версія','Розмір'],run.job.inputs.map(x=>[esc(x.filename),by('entity_revision',x.revision_id)?.revision_no||'—',x.byte_size+' байт'])))+
  panel('Пропозиції для перевірки',table(['Вид','Зміст','Стан',''],candidates.map(c=>{const v=c.proposed_payload;return [esc(kind[v.type]),esc(v.type==='text'?v.text.slice(0,180):v.type==='segmentation'?v.segments.length+' фрагментів':c.proposed_entity_id&&v.type==='metadata'?by('assertion',c.proposed_entity_id).statement_text:metadataKind[v.metadata_kind]+': '+v.value),esc(candidateState[c.state]),['pending','deferred'].includes(c.state)?btn('Перевірити','review-'+c.id,allowed('text.review',c.id)&&!problem):c.proposed_entity_id&&v.type==='text'?link(12,'Відкрити текст',{id:c.proposed_entity_id}):c.proposed_entity_id&&v.type==='segmentation'?btn('Часовий шар','layer-'+c.id):'Рішення збережено'];})))+
  outputs.map(x=>body(((x.warnings||[]).length?'<details><summary>Зауваження інструмента</summary>'+x.warnings.map(w=>`<p class="muted">${esc(w)}</p>`).join('')+'</details>':'')+(x.speaker_segmentation==='unavailable'&&run.job.parameters.speakers_requested?'<p>Розділення мовців не виконано цим інструментом. Можна додати результат зовнішнього засобу окремим запуском; позначки мовців не встановлюють особу.</p>':''))).join('')+
  `<details class="record-history"><summary>Походження та історія рішень</summary>${body(details([['Постачальник',run.provider||'Очікується результат'],['Інструмент',run.tool_name],['Версія інструмента',run.tool_version],['Модель',run.model_name||'Не зазначено'],['Версія моделі',run.model_version||'Не зазначено'],['Параметри',JSON.stringify(run.parameters,null,2)],['Межі джерела',run.job.source_revision_id],['Контрольна сума завдання',run.job_digest]]))}${table(['Рішення','Підстава','Дата'],t.review_decision.filter(d=>candidates.some(c=>c.id===d.target_entity_id)).map(d=>[esc(d.decision),esc(d.reason),esc(d.decided_at)]))}</details>`);
 if(p.has('candidate')){const candidate=candidates.find(c=>c.id===p.get('candidate'));if(candidate&&['pending','deferred'].includes(candidate.state)&&allowed('text.review',candidate.id)&&!problem)review(candidate);}
}
