import {programmeRefs,programmeVersions,programmePdf} from '../data/programmes.mjs?v=20261007-notes1';
import {encode,download} from './session-media.mjs?v=20261007-notes1';
import {fileBytes,MAX_MEDIA_BYTES} from '../data/binary.mjs?v=20261007-notes1';
import {hint} from './help.mjs?v=20261007-notes1';
export function programmeEditor(c,r,v=null){
 const {st,rev,form,input,select,choices,esc}=c,doc=v?.snapshot,pdf=doc&&programmePdf(st,doc);
 return form(v?'Редагувати питальник':'Додати програму / питальник',input('title','Назва',doc?.title||'','text',true)+select('programme_kind','Тип',choices([['general','Загальна програма'],['thematic','Тематичний питальник']],doc?.programme_kind||'general'))+input('body_text','Текст програми / питання',doc?.body_text||'','textarea')+(pdf?'<p>PDF: '+esc(pdf.original_filename)+'</p><label class="check-label"><input type="checkbox" name="remove_pdf">Прибрати прикріплений PDF</label>':'')+'<label>PDF-файл<input type="file" name="pdf" accept="application/pdf,.pdf"></label><div class="field-control"><p>Текст або PDF до 2 МіБ</p>'+hint('Текст і PDF','Можна додати текст, PDF до 2 МіБ або обидва. PDF збереже музичні знаки та спеціальні шрифти оригіналу. Новий файл замінить вкладення лише у новій версії.')+'</div>',async fd=>{const f=fd.get('pdf');let pdf;if(f?.size){if(f.size>MAX_MEDIA_BYTES)throw Error('Оберіть PDF до 2 МіБ.');pdf={filename:f.name,mime_type:f.type||'application/pdf',content:await encode(f)};}return {type:'field.programme.item',id:r.id,expected_revision_id:rev(r.id),document_id:v?.entity_id,document_revision_id:v?rev(v.entity_id):undefined,title:fd.get('title'),programme_kind:fd.get('programme_kind'),body_text:fd.get('body_text'),remove_pdf:fd.has('remove_pdf'),pdf};});
}
export function programmePanel(c,row,{session=false}={}){
 const {st,t,by,rev,writable,esc,pg,button,panel,body,table,btn,action,form,dialog,save}=c,versions=programmeVersions(st,row),write=!session&&writable(row.id),command=v=>({type:'field.programme.item',id:row.id,expected_revision_id:rev(row.id),...v});
 action('programme-add',()=>programmeEditor(c,row));
 const rows=versions.map((v,i)=>{const doc=v.snapshot,file=programmePdf(st,doc),canReadFile=file&&writable(file.id,'domain.read')&&!!st.demo.file_contents[file.id],key='programme-'+v.id;
  action(key,()=>{let blob;if(canReadFile&&st.demo.file_contents[file.id])blob=URL.createObjectURL(new Blob([fileBytes(st.demo.file_contents[file.id])],{type:'application/pdf'}));const d=dialog(doc.title,'<p class="muted">Версія '+v.revision_no+'</p>'+(doc.body_text?'<div class="reading-text programme-text">'+esc(doc.body_text)+'</div>':'')+(blob?'<p><a class="button secondary" href="'+blob+'" target="_blank" rel="noopener">Відкрити PDF окремо</a></p><iframe class="programme-pdf" title="PDF питальника" src="'+blob+'"></iframe>':file?'<p>PDF недоступний у цьому браузері.</p>':''),null,'Закрити');if(blob)d.addEventListener('close',()=>URL.revokeObjectURL(blob),{once:true});d.querySelector('.cancel').hidden=true;});
  action(key+'-pdf',()=>download(st.demo.file_contents[file.id],'application/pdf',file.original_filename));
  if(write){action(key+'-edit',()=>programmeEditor(c,row,v));action(key+'-remove',()=>form('Прибрати питальник із дослідження',body('<p>'+esc(doc.title)+'</p><p>Створені сеанси збережуть свою версію.</p>'),()=>command({document_id:v.entity_id,document_revision_id:rev(v.entity_id),remove:true})));for(const direction of [-1,1])action(key+'-'+direction,()=>save(command({document_id:v.entity_id,document_revision_id:rev(v.entity_id),direction})));}
  return [esc(doc.title),doc.programme_kind==='thematic'?'Тематичний питальник':'Загальна програма',[doc.body_text?'Текст':'',file?'PDF':''].filter(Boolean).join(' + '),'Версія '+v.revision_no,'<div class="programme-actions">'+btn('Читати',key)+(canReadFile?' '+btn('Завантажити PDF',key+'-pdf'):'')+'</div>',(write?'<div class="programme-actions">'+btn('Редагувати',key+'-edit')+' '+btn('Вище',key+'--1',i>0)+' '+btn('Нижче',key+'-1',i<versions.length-1)+' '+btn('Прибрати',key+'-remove')+'</div>':'')];
 });
 let controls=write?btn('Додати програму / питальник','programme-add'):'';
 if(session){const research=by('field_research',row.research_id);if(research&&writable(research.id,'domain.read')){controls=button('Питальники дослідження',pg(5,{id:research.id,role:'R01',section:'programmes'}),true);action('programme-sync',()=>form('Оновити питальники сеансу',body('<p>Сеанс використовуватиме поточний перелік дослідження:</p><ul>'+programmeVersions(st,research).map(v=>'<li>'+esc(v.snapshot.title)+' · версія '+v.revision_no+'</li>').join('')+'</ul><p>Сформовані бланки залишаться без змін.</p>'),()=>({type:'field.session.programmes',id:row.id,expected_revision_id:rev(row.id),research_revision_id:rev(research.id)})));controls+=' '+btn('Оновити перелік із дослідження','programme-sync',writable(row.id)&&JSON.stringify(programmeRefs(row))!==JSON.stringify(programmeRefs(research)));}}
 return '<section class="programme-list">'+panel('Програми та питальники',table(['Назва','Тип','Матеріали','Версія','Перегляд',...(write?['Дії']:[])],rows.map(x=>write?x:x.slice(0,5))),controls)+'</section>'+body('<div class="field-control"><p>Про версії питальників</p>'+hint('Програма й тематичні питальники',session?'Тут збережено перелік для цього сеансу. Зміни дослідження можна підтягнути кнопкою. У бланку ви окремо обираєте, які тексти включити.':'Додавайте загальну програму та окремі тематичні питальники. Нові сеанси отримають цей перелік; попередні збережуть свої версії.')+'</div>');
}
