import {qualityReport,qualityDigest} from '../data/quality.mjs?v=20261002-wf17';
import {fileBytes,mediaMime} from '../data/binary.mjs?v=20261002-wf17';
import {mediaPreview,download} from './session-media.mjs?v=20261002-wf17';
import {wizard} from './wizard.mjs?v=20261002-wf17';
export async function browserProbe(content,mime){
 if(!content||!mediaMime(mime))return {result:'unsupported',method:'browser',note:'Браузерний аналіз недоступний для цього формату.'};
 const url=URL.createObjectURL(new Blob([fileBytes(content)],{type:mime})),image=mime.startsWith('image/'),element=document.createElement(image?'img':mime.startsWith('audio/')?'audio':'video');
 try{return await new Promise(resolve=>{let finished=false;const done=result=>{if(finished)return;finished=true;clearTimeout(timer);resolve(result);},timer=setTimeout(()=>done({result:'unsupported',method:'browser',note:'Перевірка не завершилася за 4 секунди.'}),4000);
  element.onerror=()=>done({result:'fail',method:'browser',note:'Браузер не зміг відкрити файл; перевірте іншим засобом.'});
  const loaded=()=>done({result:'pass',method:'browser',width:image?element.naturalWidth:element.videoWidth||null,height:image?element.naturalHeight:element.videoHeight||null,duration_ms:!image&&Number.isFinite(element.duration)?Math.round(element.duration*1000):null,note:image?'Браузер декодував зображення.':'Браузер завантажив початок запису; прослухайте або перегляньте весь файл.'});
  if(image)element.onload=loaded;else{element.onloadeddata=loaded;element.preload='auto';element.muted=true;}element.src=url;
 });}finally{element.removeAttribute('src');if(!image)element.load();URL.revokeObjectURL(url);}
}
const names={format:'Формат',resolution_ppi:'Роздільність, ppi',bit_depth:'Розрядність, біт',color_mode:'Колір',width:'Ширина',height:'Висота',sample_rate_hz:'Частота, Гц',channels:'Канали',duration_ms:'Тривалість, мс',frame_rate:'Кадрів/с',codec:'Кодек',peak_dbfs:'Пік, dBFS',clipped_samples:'Граничні семпли'};
const results={pass:'Пройдено',fail:'Не пройдено',unknown:'Потрібна перевірка',unsupported:'Потрібна зовнішня перевірка',not_applicable:'Не застосовується'};
export async function qualityDialog(ctx,rep){
 const {st,t,esc,dialog,input,select,choices,details,table,dispatch,done,rev,label}=ctx,report=await qualityReport(st,rep),expected_report_hash=await qualityDigest(report),probes=new Map();
 const rows=report.files.map((f,i)=>`<fieldset><legend>${i+1}. ${esc(f.label||f.filename)}</legend><p>${esc(f.filename)}</p>`+table(['Параметр','За планом','Виміряно','Результат'],f.comparisons.map(x=>[esc(names[x.key]||x.key),esc(x.expected),esc(x.actual??'Не визначено'),esc(results[x.result])]))+details([['Вид матеріалу',f.kind_match?'Відповідає плану':'Не відповідає плану'],['SHA-256',f.checksum==='pass'?'Повторно обчислено — збігається':'Не збігається або байти недоступні'],['Структура',results[f.structure]],...Object.entries(f.measured).filter(([key])=>['width','height','duration_ms','peak_dbfs','clipped_samples'].includes(key)).map(([key,value])=>[names[key],value])])+`<details><summary>Переглянути або прослухати</summary>${mediaPreview(st.demo.file_contents[f.file_id],f.mime_type,esc)}<button type="button" class="button secondary" data-qc-download="${i}">Завантажити оригінал</button></details><button type="button" class="button secondary" data-qc-probe="${i}">Перевірити відкриття у браузері</button><p role="status" data-qc-probe-result="${i}">Перевірку відкриття ще не виконано.</p>`+select('readability_'+i,'Огляд файла '+(i+1),choices({unknown:'Ще не перевірено',pass:'Читається / відтворюється',fail:'Є дефект'},'unknown'))+select('parameters_'+i,'Параметри файла '+(i+1),choices({unknown:'Ще не перевірено',pass:'Звірено',fail:'Є невідповідність'},'unknown'))+input('evidence_'+i,'Доказ огляду файла '+(i+1),'','textarea',false,'Зазначте, що перевірили у всьому файлі, та спостереження. Автоматичне відкриття не підтверджує зміст і якість усього запису.')+input('external_'+i,'Зовнішня перевірка файла '+(i+1),'','textarea',false,'Потрібна для невиміряних параметрів або непідтримуваного перегляду: інструмент/версія, фактичні значення, висновок і місце звіту.')+`<details><summary>Межі вимірювання</summary><p>${f.notes.map(esc).join(' ')}</p></details></fieldset>`).join('');
 const d=wizard({dialog,esc},{title:'Перевірити результат',submit:'Зберегти висновок',steps:[
  {title:'Комплектність і порядок',body:details([['Матеріал',label(rep.asset_id)],['Комплектність',`${report.files.length} із ${report.expected.length||'невідомої кількості'} частин`],['Порядок',report.order?'За планом':'Потребує звірки'],['Контрольні суми',report.integrity?'Повторно обчислено — збігаються':'Потребують перевірки']])+table(['Позиція','Очікувана частина','Файл'],report.expected.map(x=>[x.position,esc(x.label),esc(report.files.find(f=>f.position===x.position)?.filename||'Відсутній')]))+'<label class="check-label"><input type="checkbox" name="order_confirmed">Я звірив зміст і послідовність усіх частин із планом</label>'},
  {title:'Огляд і вимірювання файлів',body:rows||'<p>Файлів немає. Зафіксуйте неповний результат.</p>'},
  {title:'Рішення',body:select('outcome','Висновок',choices({incomplete:'Поки не приймати: неповний результат',recapture_required:'Відхилити та повторити фіксацію',pass_with_note:'Прийняти з відомим дефектом',pass:'Прийняти технічно'},'incomplete'))+input('notes','Підстава висновку','','textarea',true)+input('defect_note','Відомий дефект і причина його прийняття','','textarea')+'<label class="check-label"><input type="checkbox" name="better_unavailable">Кращий результат недоступний; причину задокументовано</label><label class="check-label"><input type="checkbox" name="confirm" required>Підтверджую перевірку саме цього результату</label>'}
 ],summary:v=>details([['Матеріал',label(rep.asset_id)],['Висновок',({pass:'Технічно прийнято',pass_with_note:'Прийнято з відомим дефектом',recapture_required:'Відхилено; потрібен повтор',incomplete:'Поки не прийнято'})[v.outcome]],['Підстава',v.notes],['Відомий дефект',v.defect_note||'Не зазначено'],['Наступний крок',['pass','pass_with_note'].includes(v.outcome)?'Збереження файлів і звірка архівного опису':'Усунення зауважень або повторна фіксація']]),onSubmit:async v=>{if([...probes.values()].some(x=>x.pending))throw Error('Дочекайтеся завершення перевірки відкриття.');await dispatch({type:'media.qc',id:rep.id,expected_revision_id:rev(rep.id),expected_report_hash,outcome:v.outcome,notes:v.notes,defect_note:v.defect_note,better_unavailable:v.better_unavailable.length>0,confirm:v.confirm.length>0,order_confirmed:v.order_confirmed.length>0,reviews:report.files.map((f,i)=>({file_id:f.file_id,readability:v['readability_'+i],parameters:v['parameters_'+i],evidence_note:v['evidence_'+i],external_review:v['external_'+i],browser_probe:probes.get(f.file_id)||null}))});done('Висновок і докази перевірки збережено.');}});
 d.querySelectorAll('[data-qc-download]').forEach(el=>el.onclick=()=>{const f=report.files[Number(el.dataset.qcDownload)];download(st.demo.file_contents[f.file_id],f.mime_type,f.filename);});
 d.querySelectorAll('[data-qc-probe]').forEach(el=>el.onclick=async()=>{const i=Number(el.dataset.qcProbe),f=report.files[i],status=d.querySelector(`[data-qc-probe-result="${i}"]`);el.disabled=true;probes.set(f.file_id,{pending:true});status.textContent='Перевіряю відкриття…';try{const probe=await browserProbe(st.demo.file_contents[f.file_id],f.mime_type);probes.set(f.file_id,probe);status.textContent=probe.note+(probe.width?` ${probe.width} × ${probe.height} px.`:'')+(probe.duration_ms?` ${probe.duration_ms} мс.`:'');}catch(error){probes.set(f.file_id,{result:'fail',method:'browser',note:error.message});status.textContent=error.message;}finally{el.disabled=false;}});
 return d;
}
export function qualityHistory(ctx,records){
 const {st,esc,details,action,btn,table,label}=ctx;
 return records.slice().reverse().map(q=>{const items=st.tables.qc_check_item.filter(x=>x.qc_record_id===q.id),value=items.find(x=>x.check_code==='parameters')?.measured_value;
  action('qc-report-'+q.id,()=>download(JSON.stringify({decision:q,checks:items},null,2),'application/json','quality-report.json'));
  return `<details class="record-history"><summary>${esc(({pass:'Технічно прийнято',pass_with_note:'Прийнято з дефектом',recapture_required:'Потрібен повтор',incomplete:'Не прийнято'})[q.outcome])} · ${esc(q.notes||'Без примітки')}</summary>`+details([['Хто перевірив',label(q.reviewer_person_id)],['Дата перевірки',new Date(q.checked_at).toLocaleString('uk-UA')],['Підстава',q.notes],['Відомий дефект',value?.defect_note],['Кращий результат недоступний',value?.better_unavailable?'Підтверджено':'Не зазначено']])+table(['Перевірка','Результат'],items.map(x=>[esc(({completeness:'Комплектність',order:'Порядок',checksum:'SHA-256',readability:'Читабельність / відтворення',parameters:'Параметри'})[x.check_code]),esc(results[x.result])]))+(value?.reviews||[]).map(r=>details([['Файл',value.report.files.find(f=>f.file_id===r.file_id)?.filename],['Доказ огляду',r.evidence_note],['Зовнішня перевірка',r.external_review]])).join('')+btn('Завантажити звіт','qc-report-'+q.id)+'</details>';
 }).join('');
}
