import {readerResources,readerTags,annotationView,noteTypes} from '../data/reader.mjs?v=20261002-feedback2';
import {corpusAnchor,corpusTarget,corpusKey} from '../data/corpus.mjs?v=20261002-feedback2';
import {researchVisible,sourceView} from '../data/research.mjs?v=20261002-feedback2';
import {mediaPreview} from './session-media.mjs?v=20261002-feedback2';
import {hint} from './help.mjs?v=20261002-feedback2';
export function readerWorkspace(c,src,selectedItem,corpusId,corpusRevision){
 const {st,actor,p,esc,dialog,input,details,table,panel,body,btn,act,dispatch,go,rev,sources,assertionWizard}=c,t=st.tables;
 const resources=readerResources(st,actor,src),anchor={source_entity_id:src.id,source_revision_id:src.revision_id},sourceItem={...anchor,target_entity_id:src.id,target_revision_id:src.revision_id};
 if(selectedItem&&!resources.some(x=>corpusKey(x.item)===corpusKey(selectedItem))){const view=corpusTarget(st,actor,selectedItem);if(view)resources.push({item:selectedItem,view});}
 const texts=resources.filter(x=>x.view.type==='textual_representation'),media=resources.filter(x=>x.view.type==='representation'),segments=resources.filter(x=>x.view.type==='media_segment');
 const snap=x=>t.entity_revision.find(r=>r.id===x.item.target_revision_id)?.snapshot;
 const label=x=>{const s=snap(x),term=t.vocabulary_term.find(t=>t.id===s?.kind_term_id);return (x.view.type==='textual_representation'?{diplomatic:'Транскрипція',normalized:'Нормалізація',translation:'Переклад',notation:'Нотний текст'}[term?.code]||'Текст':x.view.files.map(f=>f.filename).join(', ')||x.view.label)+(s?.language_tag?' · '+s.language_tag:'')+' · версія '+x.view.revision_no;};
 const selected=selectedItem&&corpusTarget(st,actor,selectedItem),pinned=snap({item:selectedItem||sourceItem});
 const chosenMedia=p.get('reader_media')==='none'?null:media.find(x=>x.view.revision_id===(p.get('reader_media')||(selected?.type==='representation'?selected.revision_id:pinned?.representation_revision_id)))||media[0];
 const chosenText=p.get('reader_text')==='none'?null:texts.find(x=>x.view.revision_id===(p.get('reader_text')||(selected?.type==='textual_representation'?selected.revision_id:null)))||texts[0],compare=texts.find(x=>x.view.revision_id===p.get('reader_compare'));
 const url=extra=>({...Object.fromEntries(p),...extra}),tags=readerTags(st,actor,src);
 const saveNote=(item=sourceItem,range=null,old=null)=>{
  const view=corpusTarget(st,actor,item);if(!view)throw Error('Матеріал недоступний.');
  dialog(old?'Редагувати нотатку':'Додати нотатку',details([['До матеріалу',view.title],['Версія',String(view.revision_no)],...(range?[['Виділення',view.text.slice(range.start,range.end)]]:[])])+`<label>Вид нотатки<select name="note_type">${Object.entries(noteTypes).map(([k,v])=>`<option value="${k}" ${(old?.note_type||'note')===k?'selected':''}>${v}</option>`).join('')}</select></label>`+input('body','Нотатка',old?.body||'',true,true)+`<details><summary>Особа, місце, поняття або мотив</summary>${tags.map((tag,i)=>`<label class="check-label"><input type="checkbox" name="tags" value="${i}" ${(old?.tags||[]).some(x=>x.id===tag.id&&x.kind===tag.kind)?'checked':''}>${esc({person:'Особа',place:'Місце',concept:'Поняття',motif:'Мотив'}[tag.kind]+': '+tag.label)}</label>`).join('')||'<p>Дозволених позначок немає.</p>'}</details>`,async fd=>{
   await dispatch({type:old?'research.annotation.update':'research.annotation',...item,id:old?.id,expected_revision_id:old?rev(old.id):null,body:fd.get('body'),note_type:fd.get('note_type'),tags:fd.getAll('tags').map(i=>({id:tags[Number(i)].id,kind:tags[Number(i)].kind})),range_start:range?.start??null,range_end:range?.end??null,corpus_id:corpusId,corpus_revision_id:corpusRevision});go(45,url({view:'notes',resource:'',segment:''}));
  });
 };
 const options=(rows,current,empty=false)=>(empty?'<option value="none">Не показувати</option>':'')+rows.map(x=>`<option value="${x.view.revision_id}" ${current?.view.revision_id===x.view.revision_id?'selected':''}>${esc(label(x))}</option>`).join('');
 act('reader-select',()=>dialog('Обрати матеріали для читання',`<label>Медіа<select name="reader_media">${options(media,chosenMedia,true)}</select></label><label>Основний текст<select name="reader_text">${options(texts,chosenText,true)}</select></label><label>Текст для порівняння<select name="reader_compare">${options(texts,compare,true)}</select></label>`+hint('Порівняння','Показано лише дозволені точні версії. Тексти зіставляються поруч; збіг рядків сам по собі не означає підтвердженого вирівнювання.'),fd=>go(45,url({...Object.fromEntries(fd),view:'workspace',resource:'',segment:''})),'Відкрити'));
 const textPanel=(x,key)=>{if(!x)return '<p class="muted">Дозволеного тексту не обрано.</p>';act('annotate-'+key,()=>{const el=document.querySelector('[data-reader-text="'+key+'"]');if(el.selectionStart===el.selectionEnd)throw Error('Виділіть уривок у тексті.');saveNote(x.item,{start:el.selectionStart,end:el.selectionEnd});});const r=t.entity_revision.find(r=>r.id===x.view.revision_id),origin=resources.find(v=>v.view.revision_id===r.snapshot.derived_from_revision_id);
  return '<h3>'+esc(label(x))+'</h3>'+`<textarea class="reader-text" readonly data-reader-text="${key}" aria-label="${key==='main'?'Текст для читання':'Текст для порівняння'}">${esc(x.view.text)}</textarea>`+btn('Анотувати виділення','annotate-'+key)+`<details><summary>Походження цієї версії</summary>${details([['Створено',r.recorded_at],['Вид',label(x)],['Походить із',origin?label(origin):r.snapshot.derived_from_revision_id?'Пов’язана версія недоступна':'Самостійний текст']])}</details>`;
 };
 act('reader-interval',()=>{
  if(!chosenMedia)throw Error('Оберіть аудіо або відео.');
  const current=document.querySelector('.reader-file audio,.reader-file video')?.currentTime||0;
  dialog('Анотувати часовий інтервал',`<label>Початок, с<input type="number" name="start" min="0" step="0.001" value="${current.toFixed(3)}" required></label><label>Кінець, с<input type="number" name="end" min="0" step="0.001" required></label>`+input('body','Нотатка','',true,true)+hint('Ваш фрагмент','Інтервал зберігається як ваш дослідницький фрагмент точної версії медіа. Архівний часовий шар не змінюється.'),async fd=>{await dispatch({type:'research.segment.annotation',...chosenMedia.item,start_ms:Math.round(Number(fd.get('start'))*1000),end_ms:Math.round(Number(fd.get('end'))*1000),body:fd.get('body'),note_type:'note',corpus_id:corpusId,corpus_revision_id:corpusRevision});go(45,url({view:'notes',resource:'',segment:''}));});
 });
 const relevantSegments=segments.filter(x=>snap(x)?.representation_revision_id===chosenMedia?.view.revision_id);
 const workspace=panel('Читання та перегляд',body(btn('Обрати матеріали','reader-select')+hint('Як працювати','Виділіть уривок тексту й натисніть «Анотувати виділення». Для часового фрагмента скористайтеся дією в його рядку. Нотатки, сумніви та позначки залишаються вашими дослідницькими записами.'))+body('<div class="reader-grid">'+(chosenMedia?'<section class="reader-media"><h3>'+esc(label(chosenMedia))+'</h3>'+chosenMedia.view.files.map(f=>'<div class="reader-file" data-file="'+f.id+'">'+mediaPreview(st.demo.file_contents[f.id]||'Файл не збережено в цьому браузері.',f.mime,esc)+'</div>').join('')+(chosenMedia.view.files.some(f=>f.mime.startsWith('image/'))?'<label>Масштаб зображення<input data-reader-zoom type="range" min="50" max="300" value="100"></label>':'<label>Перейти до секунди<input type="number" min="0" step="0.1" value="0" data-reader-time></label><button type="button" class="button secondary" data-reader-seek>Перейти</button><p role="status" data-reader-status></p>'+btn('Анотувати інтервал','reader-interval'))+'</section>':'<section><p>Дозволених медіа не обрано.</p></section>')+'<section>'+textPanel(chosenText,'main')+'</section>'+(compare?'<section>'+textPanel(compare,'compare')+'</section>':'')+'</div>')+(relevantSegments.length?table(['Часовий фрагмент','Текст','Нотатка'],relevantSegments.map((x,i)=>{act('segment-note-'+i,()=>saveNote(x.item));return [`<button type="button" class="button secondary" data-reader-segment="${i}">${esc(x.view.label)}</button>`,esc(x.view.text),btn('Анотувати фрагмент','segment-note-'+i)];})):body('<p class="muted">Для цього медіа дозволених часових фрагментів немає.</p>')));
 const notes=t.annotation.filter(x=>corpusAnchor(x).id===src.id&&corpusAnchor(x).revision_id===src.revision_id&&(!corpusId||x.corpus_id===corpusId)&&researchVisible(st,actor,x,'annotation'));
 const notesHtml=panel('Мої нотатки',table(['Вид і матеріал','Нотатка','Позначки','Дії'],notes.map(x=>{const v=annotationView(st,actor,x);act('note-open-'+x.id,()=>{const target=t.entity_revision.find(r=>r.id===x.target_revision_id).snapshot;go(45,url({view:'workspace',annotation:x.id,resource:'',segment:'',...(v.target.type==='textual_representation'?{reader_text:x.target_revision_id}:v.target.type==='media_segment'?{reader_media:target.representation_revision_id}:v.target.type==='representation'?{reader_media:x.target_revision_id}:{})}));});act('note-edit-'+x.id,()=>saveNote(x,x.range_start==null?null:{start:x.range_start,end:x.range_end},x));act('note-history-'+x.id,()=>dialog('Історія нотатки',table(['Версія','Вид','Нотатка'],t.entity_revision.filter(r=>r.entity_id===x.id&&annotationView(st,actor,r.snapshot)).map(r=>[String(r.revision_no),esc(noteTypes[r.snapshot.note_type||'note']),esc(r.snapshot.body)])),null,'Закрити'));act('note-assert-'+x.id,()=>assertionWizard(src,corpusId,x));return [esc(noteTypes[x.note_type||'note'])+'<br>'+esc(v.target.label)+(x.range_start==null?'':'<br>Уривок: '+esc(v.quote)),esc(x.body),v.tags.map(tag=>esc(tag.label)).join(', ')||'—',btn('До уривка','note-open-'+x.id)+btn('Редагувати','note-edit-'+x.id)+btn('Історія','note-history-'+x.id)+btn('До твердження','note-assert-'+x.id)];}),'Нотаток ще немає. Додайте спостереження до джерела або виділеного уривка.'));
 const relations=t.assertion.filter(x=>x.scope==='research'&&x.assertion_kind==='relation'&&x.subject_entity_id===src.id&&x.subject_revision_id===src.revision_id&&researchVisible(st,actor,x,'assertion'));
 const relationsHtml=panel('Запропоновані зв’язки',table(['Джерело','Зв’язок','Підстава','Стан'],relations.map(x=>{const r=t.semantic_relation.find(r=>r.assertion_id===x.id),other=sourceView(st,actor,r.object_entity_id,x.object_revision_id),term=t.vocabulary_term.find(v=>v.id===r.relation_type_term_id);return [c.link(45,other.title,{id:other.id,revision:other.revision_id}),esc(term.source_label),c.link(46,x.statement_text,{id:x.id}),'Дослідницька гіпотеза'];}),'Зв’язків ще немає.'));
 const relation=()=>{const pool=sources().filter(x=>x.id!==src.id&&x.archive_id===src.archive_id);dialog('Запропонувати зв’язок',`<label>Інше джерело<select name="object" required><option value="">Оберіть джерело</option>${pool.map(x=>`<option value="${x.id}">${esc(x.title)}</option>`).join('')}</select></label><label>Зв’язок<select name="predicate"><option value="related_to">Пов’язано з</option><option value="variant_of">Варіант виконання</option></select></label>`+input('statement_text','Підстава зв’язку','',true,true)+hint('Дослідницька гіпотеза','Запропонований зв’язок зберігається у вашій дослідницькій роботі. Прийняття архівом потребує окремої перевірки.'),async fd=>{const other=pool.find(x=>x.id===fd.get('object'));await dispatch({type:'research.relation',target_entity_id:src.id,target_revision_id:src.revision_id,object_entity_id:other?.id,object_revision_id:other?.revision_id,predicate:fd.get('predicate'),statement_text:fd.get('statement_text'),corpus_id:corpusId});go(45,url({view:'notes',resource:'',segment:''}));});};
 const bind=()=>{
  const seek=(ms,end=null)=>{const files=chosenMedia?.view.files||[],idx=files.findLastIndex(f=>f.offset_ms!=null&&f.offset_ms<=ms),file=files[idx],player=file&&document.querySelector('[data-file="'+file.id+'"] audio,[data-file="'+file.id+'"] video'),duration=snap(chosenMedia)?.duration_ms,status=document.querySelector('[data-reader-status]');if(!player||!Number.isFinite(ms)||ms<0||duration!=null&&ms>duration){if(status)status.textContent='Вкажіть час у межах доступного медіа.';return;}player.currentTime=(ms-file.offset_ms)/1000;player.ontimeupdate=()=>{if(end!=null&&player.currentTime>=(end-file.offset_ms)/1000)player.pause();document.querySelectorAll('[data-reader-segment]').forEach(b=>{const s=snap(relevantSegments[Number(b.dataset.readerSegment)]),time=player.currentTime*1000+file.offset_ms;b.setAttribute('aria-current',String(time>=s.start_ms&&time<s.end_ms));});};if(status)status.textContent='Позиція: '+ms/1000+' с';player.play().catch(()=>{});};
  const jump=document.querySelector('[data-reader-seek]');if(jump)jump.onclick=()=>seek(Number(document.querySelector('[data-reader-time]').value)*1000);
  document.querySelectorAll('[data-reader-segment]').forEach(b=>b.onclick=()=>{const s=snap(relevantSegments[Number(b.dataset.readerSegment)]);seek(s.start_ms,s.end_ms);});
  const opened=notes.find(x=>x.id===p.get('annotation'));if(opened){if(opened.range_start!=null){const el=document.querySelector('[data-reader-text="main"]');if(chosenText?.view.revision_id===opened.target_revision_id&&el){el.focus();el.setSelectionRange(opened.range_start,opened.range_end);el.scrollIntoView({block:'center'});}}else if(t.entity.find(x=>x.id===opened.target_entity_id)?.entity_type==='media_segment'){const seg=t.entity_revision.find(r=>r.id===opened.target_revision_id).snapshot;if(seg.representation_revision_id===chosenMedia?.view.revision_id)seek(seg.start_ms,seg.end_ms);}}
  const zoom=document.querySelector('[data-reader-zoom]');if(zoom)zoom.oninput=()=>document.querySelectorAll('.reader-file img').forEach(img=>{img.style.width=zoom.value+'%';img.style.maxWidth='none';img.style.maxHeight='none';});
 };return {workspace,notesHtml:notesHtml+relationsHtml,note:()=>saveNote(),relation,bind};
}
