import {reviewCase,reviewReadable,reviewLabel,reviewSourceTypes,relationPredicates,pairFits} from '../data/reconciliation.mjs?v=20261001-wf10';
import {classificationFits,catalogSchemes} from '../data/catalog.mjs?v=20261001-wf10';
import {mediaPreview} from './session-media.mjs?v=20261001-wf10';
export const caseKinds={identity:'Відповідність ресурсу',authority:'Особа, місце або установа',relation:'Зв’язок',classification:'Класифікація',generic:'Висновок про відповідність',catalog:'Архівний опис'};
export const caseStates={pending:'Очікує перевірки',deferred:'Відкладено',unresolved:'Недостатньо доказів',disputed:'Спірний випадок',accepted:'Прийнято',corrected:'Виправлено й прийнято',rejected:'Відхилено',superseded:'Замінено'};
export function reconciliationUI(c){
 const {st,t,actor,scope,by,reg,rev,esc,pg,heading,panel,dialog,dispatch,render,flash,denied,body,input,area,select,details,table,btn,link,go,action,show}=c;
 const label=id=>reviewLabel(st,id),termLabel=id=>t.term_label.find(x=>x.term_id===id&&x.kind==='preferred')?.label||'Термін';
 const sources=t.entity.filter(e=>reviewSourceTypes.includes(e.entity_type)&&reviewReadable(st,actor,e.id)&&(!scope||e.archive_id===scope));
 const refs=(archive)=>sources.filter(e=>e.archive_id===archive).map(e=>[e.id,label(e.id)]);
 const proof=(archive,source)=>select('evidence_source_id','Джерело доказу',[...refs(archive),['','Зовнішнє джерело']],source)+input('external_uri','Посилання на зовнішній доказ','',false)+input('locator','Сторінка, рядок або фрагмент')+area('quote','Цитата з джерела','',false)+area('evidence_note','Що свідчить доказ');
 const payload=fd=>{const v=Object.fromEntries(fd);return {...v,evidence_source_revision_id:v.evidence_source_id?rev(v.evidence_source_id):null};};
 const command=(view,type)=>({type,id:view.id,expected_revision_id:view.revision_id,expected_subject_revision_id:rev(view.subject),expected_object_revision_id:rev(view.object)});
 function propose(operation='identity',source=null){
  const options=sources.filter(e=>!source||e.archive_id===reg(source)?.archive_id);if(!options.length)return;const first=source||options[0].id,archive=reg(first).archive_id;
  const d=dialog(operation==='relation'?'Запропонувати зв’язок':'Запропонувати відповідність',select('id','Джерельний матеріал',options.map(e=>[e.id,label(e.id)]),first)+(operation==='relation'?select('predicate','Тип зв’язку',Object.entries(relationPredicates).map(([id,r])=>[id,r.label])):select('operation','Що звіряємо',[['identity','Чи описано той самий ресурс'],['authority','Особу, місце або установу']],operation))+select('object_id','Запропонована ціль',refs(archive))+area('source_value','Значення в джерелі','',false)+area('reason','Чому пропонуєте відповідність')+proof(archive,first),async fd=>{const v=payload(fd),r=await dispatch({type:'reconcile.propose',...v,operation:operation==='relation'?'relation':v.operation,expected_revision_id:rev(v.id),expected_object_revision_id:rev(v.object_id)});go(24,{id:r.id});},'Передати на перевірку');
  const update=()=>{const id=d.querySelector('[name=id]').value,op=operation==='relation'?'relation':d.querySelector('[name=operation]').value,predicate=d.querySelector('[name=predicate]')?.value;d.querySelector('[name=object_id]').innerHTML=sources.filter(e=>pairFits(st,op,id,e.id,predicate)).map(e=>`<option value="${esc(e.id)}">${esc(label(e.id))}</option>`).join('');d.querySelector('[name=evidence_source_id]').innerHTML=refs(reg(id).archive_id).map(([key,title])=>`<option value="${esc(key)}" ${key===id?'selected':''}>${esc(title)}</option>`).join('')+'<option value="">Зовнішнє джерело</option>';};
  d.querySelectorAll('[name=id],[name=operation],[name=predicate]').forEach(el=>el.onchange=update);update();
 }
 function rows(state,q,kind){return [...t.candidate,...t.assertion.filter(x=>x.scope==='archival'),...(t.catalog_record||[])].map(x=>reviewCase(st,actor,x.id)).filter(v=>v&&(!scope||v.archive_id===scope)&&(state==='all'||state==='pending'&&['pending','unresolved','disputed','deferred'].includes(v.state)||v.state===state)&&(!kind||v.kind===kind)&&[v.title,v.row.proposed_payload?.description,v.object&&label(v.object)].join(' ').toLocaleLowerCase('uk').includes(q));}
 const snapshotText=(id,rid)=>{const r=by('entity_revision',rid)?.snapshot||{};return panel(label(id),body(details([['Назва в цій версії',r.title||r.preferred_name||r.name||r.external_key||r.original_filename],['Версія',by('entity_revision',rid)?.revision_no],['Зміст',r.raw_text||r.summary||r.body_text||r.inscriptions||r.context_notes||r.description||r.name_note||r.coordinate_note]])+(reg(id)?.entity_type==='representation'?(r._relations?.representation_file||[]).map(f=>mediaPreview(st.demo.file_contents[f.file_id],by('file_object',f.file_id).mime_type,esc)).join(''):reg(id)?.entity_type==='file_object'?mediaPreview(st.demo.file_contents[id],r.mime_type,esc):'')));};
 function detail(id){const v=reviewCase(st,actor,id);if(!v||scope&&v.archive_id!==scope)return denied();const open=['pending','deferred','unresolved','disputed'].includes(v.state),classification=t.classification?.find(x=>x.assertion_id===id),items=(t.catalog_record_item||[]).filter(x=>x.record_id===id),subjectType=reg(v.subject)?.entity_type;
  action('review-proof',()=>dialog('Додати доказ',select('evidence_role','Значення доказу',[['supports','Підтверджує'],['contradicts','Суперечить']])+proof(v.archive_id,v.subject)+area('reason','Пояснення'),async fd=>{await dispatch({...command(v,'reconcile.evidence'),...payload(fd)});flash('Доказ збережено.');render();}));
  action('review-reopen',()=>dialog('Повторно розглянути висновок',proof(v.archive_id,v.subject)+area('reason','Чому потрібен повторний розгляд'),async fd=>{await dispatch({...command(v,'reconcile.reopen'),...payload(fd)});render();}));
  action('review-refresh',()=>dialog('Повторно зіставити версії',body('<p>Попередню основу збережено в історії. Підтвердьте нове зіставлення поточних записів.</p>')+proof(v.archive_id,v.subject)+area('reason','Результат повторного зіставлення'),async fd=>{await dispatch({...command(v,'reconcile.refresh'),...payload(fd)});render();}));
  for(const decision of ['accept','correct','reject','defer'])action('review-'+decision,()=>{
   const correction=decision!=='correct'?'':classification?select('new_term_id','Уточнений термін',t.vocabulary_term.filter(x=>{const scheme=by('vocabulary_scheme',x.scheme_id);return x.status==='active'&&scheme.status==='active'&&(!scheme.owner_archive_id||scheme.owner_archive_id===v.archive_id)&&classificationFits(subjectType,by(subjectType,v.subject),scheme.d_code);}).map(x=>[x.id,termLabel(x.id)])):select('new_object_id','Правильна ціль',sources.filter(e=>pairFits(st,v.row.proposed_payload.operation||'identity',v.subject,e.id,v.row.proposed_payload.predicate)).map(e=>[e.id,label(e.id)]));
   dialog({accept:'Прийняти висновок',correct:'Виправити й прийняти',reject:v.kind==='catalog'?'Повернути опис':'Відхилити висновок',defer:'Залишити на уточненні'}[decision],correction+(decision==='defer'?select('case_status','Стан випадку',[['unresolved','Недостатньо доказів'],['disputed','Спірний випадок']]):'')+proof(v.archive_id,v.subject)+input('method','Спосіб перевірки','Зіставлення з джерелом')+area('reason',decision==='defer'?'Що потрібно з’ясувати':'Обґрунтування рішення')+'<label class="check-label"><input type="checkbox" name="confirm" required>Я зіставив матеріал із доказами</label>',async fd=>{const p=payload(fd);await dispatch({...command(v,'reconcile.review'),...p,decision,confirm:fd.has('confirm'),new_object_revision_id:rev(p.new_object_id)});flash('Рішення й докази збережено.');render();},decision==='defer'?'Залишити на уточненні':'Зберегти рішення');
  });
  const canCorrect=classification||reg(id).entity_type==='candidate',controls=open?btn('Прийняти','review-accept',!v.stale)+(canCorrect?btn('Виправити й прийняти','review-correct',!v.stale):'')+btn(v.kind==='catalog'?'Повернути на опис':'Відхилити','review-reject')+btn('Потрібне уточнення','review-defer'):reg(id).entity_type==='assertion'&&['accepted','rejected'].includes(v.state)?btn('Переглянути висновок','review-reopen'):'';
  const applications=t.review_application.filter(x=>v.decisions.some(d=>d.id===x.review_decision_id));
  show(link(23,'← Черга перевірки')+heading('Звірка',v.title,'',`<div class="public-actions">${controls}</div>`)+body(details([['Що перевіряємо',caseKinds[v.kind]],['Стан',caseStates[v.state]]]))+(v.stale?body('<p class="notice warning">Матеріал змінився після створення пропозиції. Прийняття заблоковано.</p>'+(open&&v.kind!=='catalog'?btn('Повторно зіставити','review-refresh'):'')):'')+
   (classification?panel('Класифікація',body(details([['Джерельне формулювання',classification.source_label],['Довідник',catalogSchemes[by('vocabulary_scheme',classification.scheme_id)?.d_code]],['Запропонований термін',termLabel(classification.term_id)]]))):'')+
   (v.row.proposed_payload?panel('Запропонована відповідність',body(details([['Значення в джерелі',v.row.proposed_payload.source_value],['Нормалізована ціль',v.row.proposed_payload.normalized_label||label(v.object)],['Тип зв’язку',relationPredicates[v.row.proposed_payload.predicate]?.label||caseKinds[v.kind]],['Підстава пропозиції',v.row.proposed_payload.description||v.row.proposed_payload.reason]]))):'')+
   snapshotText(v.subject,v.basis)+(v.object?snapshotText(v.object,v.objectBasis||rev(v.object)):'')+
   (v.kind==='catalog'?panel('Склад переданого опису',table(['Складова','Стан','Дія'],items.filter(x=>x.kind!=='issue').map(i=>{const e=reg(i.target_entity_id),claim=e.entity_type==='assertion'?by('assertion',e.id):null;return [esc(claim?.assertion_kind==='classification'?termLabel(t.classification.find(x=>x.assertion_id===claim.id)?.term_id):label(e.id)),claim?esc(caseStates[claim.acceptance_state]||'Потребує перевірки'):'У зафіксованій версії',claim?link(24,'Розглянути',{id:claim.id}):link(17,'Відкрити опис',{material:v.subject})];}))):'')+
   panel('Докази',table(['Доказ','Джерело','Значення'],v.evidence.map(x=>[esc(x.evidence.note)+`<span class="sub">${esc(x.evidence.locator)}</span>`+(x.evidence.quote_text?`<blockquote>${esc(x.evidence.quote_text)}</blockquote>`:''),esc(x.evidence.source_entity_id?label(x.evidence.source_entity_id):x.evidence.external_uri),x.evidence_role==='contradicts'?'Суперечить':'Підтверджує'])),btn('Додати доказ','review-proof'))+
   panel('Історія рішень',table(['Рішення','Рецензент і час','Обґрунтування'],v.decisions.map(d=>[esc({accept:'Прийнято',correct:'Виправлено',reject:'Відхилено',defer:d.case_status==='disputed'?'Спірний випадок':'Недостатньо доказів'}[d.decision]),esc(by('account',d.reviewer_account_id)?.display_name||'Користувач')+`<span class="sub">${esc(new Date(d.decided_at).toLocaleString('uk-UA'))}</span>`,esc(d.reason)])))+
   (applications.length?panel('Зафіксований результат',table(['Результат','Версія'],applications.map(a=>{const r=by('entity_revision',a.result_revision_id)?.snapshot,identity=r?._relations?.identity_resolution?.[0],rel=r?._relations?.semantic_relation?.[0],cls=r?._relations?.classification?.[0];return [esc(identity?identity.normalized_label:rel?label(rel.object_entity_id):cls?termLabel(cls.term_id):label(a.result_entity_id)),by('entity_revision',a.result_revision_id)?.revision_no];}))):'')+
   body((['information_unit','collecting_session','field_research','source_record','document','physical_object','file_object','media_asset'].includes(subjectType)?link(17,'Опрацювати архівний опис',{material:v.subject}):link(19,'Відкрити довідковий запис',{id:v.subject}))+`<details class="page-help catalog-help"><summary>Як ухвалювати рішення</summary><p>Подібність назви не є доказом тотожності. За браку доказів залиште випадок на уточненні; суперечливі свідчення зберігайте окремо. Прийняття зберігає обидва записи й не надає дозволу на публікацію.</p></details>`));
 }
 return {propose,rows,detail,handles:id=>!!reviewCase(st,actor,id)};
}
