import {unitPeople} from '../data/participants.mjs?v=20261002-programmes2';
export function sessionRecords(c,r,units){
 const {t,label,params,pg,esc,btn,button,panel,table,body,action,unitDialog,writable}=c,text=params.get('view')==='text',base={id:r.id,role:params.get('role')||'R01',section:'records'},url=v=>pg(8,{...base,view:v});
 units.forEach(u=>action('edit-unit-'+u.id,()=>unitDialog(r,u)));
 const nav='<nav class="record-tabs" aria-label="Вигляд записів"><a href="'+url('list')+'" '+(!text?'aria-current="page"':'')+'>Список</a><a href="'+url('text')+'" '+(text?'aria-current="page"':'')+'>Текст сеансу</a></nav>';
 if(!text)return nav+panel('Послідовність записів',table(['№','Запис','Респонденти','Збирачі','Дії'],units.map((u,i)=>[String(u.position),button(u.title,pg(17,{id:u.id}),true),esc(unitPeople(t,u,label,'performer')),esc(unitPeople(t,u,label,'collector')),'<div class="public-actions">'+btn('Редагувати','edit-unit-'+u.id,writable(r.id))+btn('Вище',`unit-${u.id}--1`,writable(r.id)&&i>0)+btn('Нижче',`unit-${u.id}-1`,writable(r.id)&&i<units.length-1)+'</div>'])),btn('Додати запис','unit-add',writable(r.id)));
 return nav+panel('Текст сеансу',body('<div data-session-text="'+r.id+'"><div class="filters"><label>Пошук у тексті<input type="search" data-text-search></label><button type="button" class="button secondary" data-text-prev>Попередній збіг</button><button type="button" class="button secondary" data-text-next>Наступний збіг</button><span role="status" data-text-status></span></div>'+units.map(u=>'<article id="unit-'+u.id+'" style="margin-block:24px"><h2>'+esc(u.position+'. '+u.title)+'</h2><p>'+esc('Респонденти: '+unitPeople(t,u,label,'performer'))+'</p><p>'+esc('Збирачі: '+unitPeople(t,u,label,'collector'))+'</p><div class="reading-text" style="white-space:pre-wrap" data-search-body>'+esc(u.summary||'Текст ще не додано')+'</div>'+btn('Редагувати','edit-unit-'+u.id,writable(r.id))+'</article>').join('')+(!units.length?'<p>Записів ще немає.</p>':'')+'</div>'),btn('Додати запис','unit-add',writable(r.id)));
}
export function bindSessionText(){
 const root=document.querySelector('[data-session-text]');if(!root)return;const input=root.querySelector('[data-text-search]'),status=root.querySelector('[data-text-status]'),key='hereditas.session.search.'+root.dataset.sessionText,blocks=[...root.querySelectorAll('[data-search-body]')].map(el=>({el,text:el.textContent}));let matches=[],index=-1;
 input.value=sessionStorage.getItem(key)||'';
 const find=()=>{sessionStorage.setItem(key,input.value);matches=[];index=-1;for(const {el,text} of blocks){el.replaceChildren();const query=input.value.toLocaleLowerCase('uk');if(!query){el.textContent=text;continue;}const lower=text.toLocaleLowerCase('uk');let start=0,pos;while((pos=lower.indexOf(query,start))!==-1){el.append(document.createTextNode(text.slice(start,pos)));const mark=document.createElement('mark');mark.textContent=text.slice(pos,pos+query.length);el.append(mark);matches.push(mark);start=pos+query.length;}el.append(document.createTextNode(text.slice(start)));}status.textContent=input.value?`Збігів: ${matches.length}`:'';};
 const move=step=>{if(!matches.length)return;index=(index+step+matches.length)%matches.length;matches[index].scrollIntoView({block:'center'});status.textContent=`${index+1} із ${matches.length}`;};input.oninput=find;root.querySelector('[data-text-next]').onclick=()=>move(1);root.querySelector('[data-text-prev]').onclick=()=>move(-1);find();
}
