import {programmePanel} from './programmes.mjs?v=20261002-programmes2';
import {programmeRefs,programmeVersions} from '../data/programmes.mjs?v=20261002-programmes2';
import {annotationWorkspace,formatTime} from './annotation-workspace.mjs?v=20261002-programmes2';
import {consentEvidenceFields,bindConsentEvidence} from './consent-evidence.mjs?v=20261002-programmes2';
import {consentMedia} from '../data/consent-media.mjs?v=20261002-programmes2';
import {sessionRecords,bindSessionText} from './session-records.mjs?v=20261002-programmes2';
import {collectorCode,isCollector,participantCodes} from '../data/participants.mjs?v=20261002-programmes2';
import {eventKinds,sessionRepresentations,markerEntries} from '../data/session.mjs?v=20261002-programmes2';
import {useNames} from '../data/workbench.mjs?v=20261002-programmes2';
import {hint} from './help.mjs?v=20261002-programmes2';
import {mediaPreview,download,sessionMediaDialogs} from './session-media.mjs?v=20261002-programmes2';
export function sessionPage(c,r){
 const {st,t,actor,by,rev,label,visible,writable,params,pg,button,panel,heading,esc,body,table,details,input,select,choices,opts,btn,form,action,save,show,revisionHistory,dialog,unitDialog,prepareHandover}=c;
 const write=writable(r.id),expected=rev(r.id),command=(type,v={})=>({type,id:r.id,expected_revision_id:expected,...v});
 const sections=[['records','Записи'],['people','Респонденти'],['collectors','Збирачі'],['consents','Згоди'],['events','Перебіг'],['media','Аудіо, відео та фото'],['programmes','Програми та питальники'],['forms','Бланки']],section=sections.some(x=>x[0]===params.get('section'))?params.get('section'):'records',url=key=>pg(8,{id:r.id,role:params.get('role')||'R01',q:params.get('q')||'',research:params.get('research')||r.research_id,section:key});
 const people=t.participation.filter(x=>x.session_id===r.id),units=t.information_unit.filter(x=>x.session_id===r.id).sort((a,b)=>a.position-b.position),roles=[['performer','Респондент'],['collector','Збирач'],['observer','Присутній']],geo=t.geographic_context.find(x=>x.subject_entity_id===r.id&&x.role_code==='recording_place');
 action('edit',()=>form('Опис сеансу',input('title','Назва',r.title,'text',true)+select('date_precision','Точність дати',choices([['exact','Точна дата'],['month','Місяць'],['year','Рік'],['range','Період'],['approximate','Приблизно'],['unknown','Невідомо']],r.date_precision))+input('date_from','Початок',r.date_from,'date')+input('date_to','Завершення',r.date_to,'date')+input('date_label','Дата словами',r.date_label)+select('place_id','Місце запису','<option value="">Не встановлено</option>'+opts(visible('place'),geo?.place_id))+select('work_group_id','Робоча група','<option value="">Без групи</option>'+opts(t.work_group.filter(x=>x.research_id===r.research_id&&!t.entity.find(e=>e.id===x.id)?.retired_at),r.work_group_id))+select('location_environment','Середовище',choices([['indoor','У приміщенні'],['outdoor','Надворі'],['mixed','Змішане'],['unknown','Невідомо']],r.location_environment))+input('location_description','Місце та умови',r.location_description,'textarea')+input('recording_context','Ситуація запису',r.recording_context,'textarea',false,'Інтерв’ю, спостереження, виконання; хто ініціював і що відбувалося.')+input('context_notes','Контекст',r.context_notes,'textarea'),fd=>command('field.session.context',Object.fromEntries(fd))));
 const personRole=section==='collectors'?'collector':'performer';
 const participant=(p,chosenRole=personRole)=>form((p?'Редагувати: ':'Додати: ')+({collector:'Збирач',performer:'Респондент',observer:'Присутня особа'})[p?.role_code||chosenRole],(p?body(details([['Особа',label(p.person_id)]])):select('person_id','Особа','<option value="">Нова особа</option>'+opts(visible('person').filter(x=>personRole!=='collector'||isCollector(t,x.id)),'',x=>personRole==='collector'?collectorCode(t,x.id)+' · '+label(x.id):label(x.id)))+input('person_name','Ім’я нової особи'))+`<input type="hidden" name="role_code" value="${p?.role_code||chosenRole}">`+input('function_text','Конкретні обов’язки',p?.function_text,'textarea')+input('local_label','Позначення в записі',p?.local_label),fd=>command('field.session.participant',{participation_id:p?.id,...Object.fromEntries(fd)}));
 action('participant',()=>participant());action('observer',()=>participant(null,'observer'));people.forEach(p=>action('person-'+p.id,()=>participant(p)));
 action('unit-add',()=>unitDialog(r));action('handover',()=>prepareHandover(r));
 const timeValue=v=>{if(!v)return '';const d=new Date(v);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);};
 action('timing',()=>form('Час проведення',input('started_at','Початок сеансу',timeValue(r.started_at),'datetime-local',true)+input('ended_at','Завершення сеансу',timeValue(r.ended_at),'datetime-local'),fd=>command('field.session.timing',Object.fromEntries(fd))));
 const eventForm=e=>form(e?'Редагувати подію':'Подія сеансу',select('kind','Тип події',choices(eventKinds,e?.kind||'other'))+input('occurred_at','Час події',timeValue(e?.occurred_at),'datetime-local')+select('participation_id','Особа','<option value="">Не стосується особи</option>'+opts(people,e?.participation_id,p=>label(p.person_id)))+input('note','Що відбулося',e?.note,'textarea',true),fd=>command('field.session.event',{position:e?.position,...Object.fromEntries(fd)}));action('event',()=>eventForm());
 action('consent',()=>{let evidence;const d=form('Задокументувати згоду',select('person_id','Особа, що надає згоду',opts([...new Map(people.map(p=>[p.person_id,by('person',p.person_id)])).values()]))+'<fieldset><legend>Що дозволено</legend>'+['record_audio','record_video','record_photo','field_notes'].map(use=>`<label class="check-label"><input type="checkbox" name="uses" value="${use}">${useNames[use]}</label>`).join('')+'</fieldset>'+input('terms','Умови та обмеження','','textarea',true)+input('evidence_note','Як і ким отримано згоду','','textarea',true)+input('locator','Де зберігається підтвердження','','text',false)+consentEvidenceFields()+input('effective_at','Чинна від','','datetime-local')+input('valid_until','Діє до','','datetime-local'),async fd=>({type:'workbench.consent.create',subject_id:r.id,expected_revision_id:expected,...Object.fromEntries(fd),uses:fd.getAll('uses'),...await evidence.read()}));evidence=bindConsentEvidence(d,{st,actor,session:()=>r.id,esc,dialog});});
 let content='',bindAnnotations=()=>{};
 if(section==='records'){
  units.forEach(x=>[-1,1].forEach(direction=>action(`unit-${x.id}-${direction}`,()=>save({type:'field.reorder',id:r.id,expected_revision_id:expected,unit_id:x.id,direction}))));
  content=sessionRecords(c,r,units);
 }else if(['people','collectors','consents'].includes(section)){
  const consents=writable(r.id,'consent.read')?t.consent_record.filter(x=>x.session_id===r.id):[];
  const collector=section==='collectors',title=collector?'Збирачі':'Респонденти',rows=people.filter(p=>p.role_code===(collector?'collector':'performer'));
  content=section==='consents'?'':panel(title,table(['Номер у сеансі','Ім’я','Обов’язки / позначення','Дія'],rows.map(p=>[esc(participantCodes(t,r.id).get(p.id)),esc(label(p.person_id))+(collector?'<span class="sub">'+esc(collectorCode(t,p.person_id))+'</span>':''),esc([p.function_text,p.local_label].filter(Boolean).join(' · ')),btn('Редагувати','person-'+p.id,write)])),btn(collector?'Додати збирача':'Додати респондента','participant',write)+(collector?' '+button('Довідник збирачів',pg(18,{role:'R01',directory:'collectors'}),true):''));
  if(section==='people'){const others=people.filter(p=>p.role_code==='observer');content+=panel('Інші присутні',table(['Особа','Позначення','Дія'],others.map(p=>[esc(label(p.person_id)),esc(p.local_label||''),btn('Редагувати','person-'+p.id,write)])),btn('Додати присутню особу','observer',write));}
  if(section==='consents'||section==='people')content+=panel('Задокументовані згоди',table(['Особа','Стан','Підтвердження','Дія'],consents.map(x=>[esc(label(x.person_id)),esc({active:'Задокументована',partially_withdrawn:'Частково відкликана',withdrawn:'Відкликана'}[x.state]||x.state),esc(({document:'Скан',digital_signature:'Підпис на телефоні',audio:'Анотація аудіо',video:'Анотація відео',recorded_note:'Потребує прикріплення доказу'})[x.evidence_method]||'Потребує прикріплення доказу'),button('Переглянути / відкликати',pg(25,{id:x.id}),true)])),btn('Задокументувати згоду','consent',people.length>0&&writable(r.id,'consent.write')));
 }else if(section==='events'){
  const events=t.session_event.filter(x=>x.session_id===r.id).sort((a,b)=>a.position-b.position);events.forEach(e=>{action('event-'+e.position,()=>eventForm(e));action('remove-event-'+e.position,()=>form('Вилучити подію',body(`<p>${esc(e.note)}</p>`),()=>command('field.session.event',{position:e.position,remove:true})));});
  content=panel('Час проведення',body(details([['Початок',r.started_at?new Date(r.started_at).toLocaleString('uk-UA'):null],['Завершення',r.ended_at?new Date(r.ended_at).toLocaleString('uk-UA'):null]])),btn('Уточнити час','timing',write))+panel('Перебіг сеансу',table(['Час','Подія','Особа','Нотатка','Дії'],events.map(e=>[esc(e.occurred_at?new Date(e.occurred_at).toLocaleString('uk-UA'):'Не зазначено'),esc(eventKinds.find(x=>x[0]===e.kind)?.[1]),esc(e.participation_id?label(by('participation',e.participation_id).person_id):'—'),esc(e.note),btn('Редагувати','event-'+e.position,write)+' '+btn('Вилучити','remove-event-'+e.position,write)])),btn('Додати подію','event',write));
 }else if(section==='media'){
  const {importDialog,recordDialog}=sessionMediaDialogs(c,r,command),reps=sessionRepresentations(st,r.id).filter(rep=>!consentMedia(st,rep.id)||writable(r.id,'consent.read')),selected=reps.find(x=>x.id===params.get('media'));
  action('import',()=>importDialog());action('demo',()=>importDialog(true));['audio','video','photo'].forEach(k=>action('record-'+k,()=>recordDialog(k)));
  content=panel('Аудіо, відео та фото',table(['Матеріал','Тип','Тривалість','Анотації','Дія'],reps.map(rep=>{const layers=(t.timed_layer||[]).filter(x=>x.representation_revision_id===rev(rep.id)),proof=t.evidence.find(e=>t.media_segment.some(m=>m.id===e.source_entity_id&&m.representation_id===rep.id)),consent=proof&&t.evidence_link.find(e=>e.evidence_id===proof.id&&e.evidence_role==='consent');return [esc(label(rep.asset_id))+(consentMedia(st,rep.id)?'<span class="sub">Доказ згоди · приватний</span>':''),esc(({audio:'Аудіо',video:'Відео',photo:'Фото'})[by('media_asset',rep.asset_id)?.media_kind]||'Медіа'),by('media_asset',rep.asset_id)?.media_kind==='photo'?'—':rep.duration_ms?formatTime(rep.duration_ms):'Не визначена',String(layers.reduce((n,l)=>n+markerEntries(st,l).length,0)+t.evidence.filter(e=>t.entity_revision.find(x=>x.id===e.source_revision_id)?.snapshot.representation_id===rep.id&&t.evidence_link.some(l=>l.evidence_id===e.id&&l.evidence_role==='consent')).length),button('Відкрити й анотувати',pg(8,{id:r.id,section:'media',media:rep.id,q:params.get('q')||'',research:params.get('research')||r.research_id,role:params.get('role')||'R01'}),true)+(consent&&writable(r.id,'consent.read')?' '+button('Згода',pg(25,{id:consent.subject_entity_id,role:'R01'}),true):'')];})),btn('Додати медіафайл','import',writable(r.id,'capture.field'))+' '+btn('Записати аудіо','record-audio',writable(r.id,'capture.field'))+' '+btn('Записати відео','record-video',writable(r.id,'capture.field'))+' '+btn('Зробити фото','record-photo',writable(r.id,'capture.field'))+' '+btn('Додати навчальне аудіо','demo',writable(r.id,'capture.field')));
  if(selected){const workspace=annotationWorkspace(c,r,selected);content='<details class="media-file-picker"><summary>Файли сеансу</summary>'+content+'</details>'+workspace.html;bindAnnotations=workspace.bind;}
 }else if(section==='programmes'){content=programmePanel(c,r,{session:true});
 }else if(section==='forms'){
  const docs=t.document_context.filter(x=>x.target_entity_id===r.id&&x.context_role==='session_form').map(x=>({context:x,doc:by('document',x.document_id)}));action('form',()=>form('Сформувати бланк сеансу',body('<p>Бланк міститиме записи й перебіг сеансу. Оберіть тексти питальників, які потрібно додати в кінці.</p>')+programmeVersions(st,r).map(v=>'<label class="check-label"><input type="checkbox" name="programme_revision_ids" value="'+v.id+'">'+esc(v.snapshot.title)+(v.snapshot.body_text?'':' (лише посилання на PDF)')+'</label>').join(''),fd=>command('field.session.form',{programme_revision_ids:fd.getAll('programme_revision_ids')})));
  docs.forEach(({doc})=>{action('view-'+doc.id,()=>{const d=dialog(doc.title,body(`<pre class="reading-text" style="white-space:pre-wrap">${esc(doc.body_text)}</pre>`),null,'Закрити');d.querySelector('.cancel').hidden=true;});action('download-form-'+doc.id,()=>download(doc.body_text,'text/plain;charset=utf-8',doc.title+'.txt'));});
  content=panel('Бланки сеансу',table(['Бланк','Відповідність сеансу','Дії'],docs.slice().reverse().map(({context,doc})=>[esc(doc.title),context.target_revision_id===expected&&t.document_context.filter(x=>x.document_id===doc.id).every(x=>x.context_role==='form_programme'?programmeRefs(r).includes(x.target_revision_id):x.target_revision_id===rev(x.target_entity_id))?'Поточний':'Сеанс змінено після формування',btn('Переглянути','view-'+doc.id)+' '+btn('Завантажити','download-form-'+doc.id)])),btn('Сформувати бланк','form',write));
 }
 show(heading(r.research_id?label(r.research_id):'Польова робота',r.title,'',button('← Сеанси',pg(7,{research:params.get('research')||r.research_id,q:params.get('q')||'',role:params.get('role')||'R01'}),true))+`<div class="actions" style="margin-bottom:16px">${btn('Редагувати сеанс','edit',write)}${button('Польовий зошит',pg(9,{research:r.research_id,session:r.id}),true)}${btn('Підготувати передання','handover',writable(r.id,'intake.send'))}</div>`+`<div class="session-people-summary"><p><strong>Респонденти:</strong> ${esc(people.filter(p=>p.role_code==='performer').map(p=>participantCodes(t,r.id).get(p.id)+' · '+label(p.person_id)).join(', ')||'Не зазначено')}</p><p><strong>Збирачі:</strong> ${esc(people.filter(p=>p.role_code==='collector').map(p=>participantCodes(t,r.id).get(p.id)+' · '+label(p.person_id)+' ('+collectorCode(t,p.person_id)+')').join(', ')||'Не зазначено')}</p></div>`+`<nav class="record-tabs field-control" style="padding-right:42px" aria-label="Розділи сеансу">${sections.map(([key,title])=>`<a href="${url(key)}" ${section===key?'aria-current="page"':''}>${title}</a>`).join('')}${hint('Робота із сеансом','Уточніть обставини, респондентів, збирачів і згоди. Додавайте нотатки, події, аудіозаписи, відео та фото; позначайте зміст фрагментів без остаточної каталогізації. Файли до 2 МіБ зберігаються лише в цьому браузері. Навчальне аудіо — синтетичний приклад. Після завершення сформуйте бланк і перейдіть до звірки та передання.')}</nav>`+content);bindSessionText();bindAnnotations();
}
