import {eventKinds,sessionRepresentations,markerEntries} from '../data/session.mjs?v=20261002-wf18';
import {useNames} from '../data/workbench.mjs?v=20261002-wf18';
import {hint} from './help.mjs?v=20261002-wf18';
import {mediaPreview,download,sessionMediaDialogs} from './session-media.mjs?v=20261002-wf18';
export function sessionPage(c,r){
 const {st,t,by,rev,label,visible,writable,params,pg,button,panel,heading,esc,body,table,details,input,select,choices,opts,btn,form,action,save,show,revisionHistory,dialog,unitDialog,prepareHandover}=c;
 const write=writable(r.id),expected=rev(r.id),command=(type,v={})=>({type,id:r.id,expected_revision_id:expected,...v});
 const sections=[['records','Записи'],['people','Учасники та згоди'],['events','Перебіг'],['media','Аудіо, відео та фото'],['forms','Бланки']],section=sections.some(x=>x[0]===params.get('section'))?params.get('section'):'records',url=key=>pg(8,{id:r.id,role:params.get('role')||'R01',q:params.get('q')||'',research:params.get('research')||r.research_id,section:key});
 const people=t.participation.filter(x=>x.session_id===r.id),units=t.information_unit.filter(x=>x.session_id===r.id).sort((a,b)=>a.position-b.position),roles=[['performer','Виконавець / оповідач'],['collector','Збирач'],['observer','Присутній']],geo=t.geographic_context.find(x=>x.subject_entity_id===r.id&&x.role_code==='recording_place');
 action('edit',()=>form('Опис сеансу',input('title','Назва',r.title,'text',true)+select('date_precision','Точність дати',choices([['exact','Точна дата'],['month','Місяць'],['year','Рік'],['range','Період'],['approximate','Приблизно'],['unknown','Невідомо']],r.date_precision))+input('date_from','Початок',r.date_from,'date')+input('date_to','Завершення',r.date_to,'date')+input('date_label','Дата словами',r.date_label)+select('place_id','Місце запису','<option value="">Не встановлено</option>'+opts(visible('place'),geo?.place_id))+select('work_group_id','Робоча група','<option value="">Без групи</option>'+opts(t.work_group.filter(x=>x.research_id===r.research_id&&!t.entity.find(e=>e.id===x.id)?.retired_at),r.work_group_id))+select('location_environment','Середовище',choices([['indoor','У приміщенні'],['outdoor','Надворі'],['mixed','Змішане'],['unknown','Невідомо']],r.location_environment))+input('location_description','Місце та умови',r.location_description,'textarea')+input('recording_context','Ситуація запису',r.recording_context,'textarea',false,'Інтерв’ю, спостереження, виконання; хто ініціював і що відбувалося.')+input('context_notes','Контекст',r.context_notes,'textarea'),fd=>command('field.session.context',Object.fromEntries(fd))));
 const participant=p=>form(p?'Редагувати учасника':'Додати учасника',(p?body(details([['Особа',label(p.person_id)]])):select('person_id','Особа','<option value="">Нова особа</option>'+opts(visible('person')))+input('person_name','Ім’я нової особи'))+select('role_code','Функція',choices(roles,p?.role_code||'performer'))+input('function_text','Конкретні обов’язки',p?.function_text,'textarea')+input('local_label','Позначення в записі',p?.local_label),fd=>command('field.session.participant',{participation_id:p?.id,...Object.fromEntries(fd)}));
 action('participant',()=>participant());people.forEach(p=>action('person-'+p.id,()=>participant(p)));
 action('unit-add',()=>unitDialog(r));action('handover',()=>prepareHandover(r));
 const timeValue=v=>{if(!v)return '';const d=new Date(v);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);};
 action('timing',()=>form('Час проведення',input('started_at','Початок сеансу',timeValue(r.started_at),'datetime-local',true)+input('ended_at','Завершення сеансу',timeValue(r.ended_at),'datetime-local'),fd=>command('field.session.timing',Object.fromEntries(fd))));
 const eventForm=e=>form(e?'Редагувати подію':'Подія сеансу',select('kind','Тип події',choices(eventKinds,e?.kind||'other'))+input('occurred_at','Час події',timeValue(e?.occurred_at),'datetime-local')+select('participation_id','Учасник','<option value="">Не стосується учасника</option>'+opts(people,e?.participation_id,p=>label(p.person_id)))+input('note','Що відбулося',e?.note,'textarea',true),fd=>command('field.session.event',{position:e?.position,...Object.fromEntries(fd)}));action('event',()=>eventForm());
 action('consent',()=>form('Задокументувати згоду',select('person_id','Учасник',opts([...new Map(people.map(p=>[p.person_id,by('person',p.person_id)])).values()]))+'<fieldset><legend>Що дозволено</legend>'+['record_audio','record_video','record_photo','field_notes'].map(use=>`<label class="check-label"><input type="checkbox" name="uses" value="${use}">${useNames[use]}</label>`).join('')+'</fieldset>'+input('terms','Умови та обмеження','','textarea',true)+input('evidence_note','Як і ким отримано згоду','','textarea',true)+input('locator','Де зберігається підтвердження','','text',true)+input('effective_at','Чинна від','','datetime-local')+input('valid_until','Діє до','','datetime-local'),fd=>({type:'workbench.consent.create',subject_id:r.id,expected_revision_id:expected,...Object.fromEntries(fd),uses:fd.getAll('uses')})));
 let content='';
 if(section==='records'){
  units.forEach(x=>[-1,1].forEach(direction=>action(`unit-${x.id}-${direction}`,()=>save({type:'field.reorder',id:r.id,expected_revision_id:expected,unit_id:x.id,direction}))));
  const program=by('entity_revision',r.programme_revision_id);
  content='<div class="two-col"><div>'+panel('Послідовність записів',table(['№','Запис','Тип','Порядок'],units.map((x,i)=>[String(x.position),button(x.title,pg(17,{id:x.id}),true),x.unit_kind==='fei'?'Фольклорно-етнографічна інформація':'Твір',btn('Вище',`unit-${x.id}--1`,write&&i>0)+' '+btn('Нижче',`unit-${x.id}-1`,write&&i<units.length-1)])),btn('Додати запис','unit-add',write))+revisionHistory(r.id)+'</div><aside>'+panel('Обставини запису',body(details([['Дата',r.date_label||r.date_from],['Місце',geo?label(geo.place_id):r.location_description],['Умови',r.location_description],['Ситуація',r.recording_context],['Контекст',r.context_notes],['Група',r.work_group_id?label(r.work_group_id):null],['Учасники',people.map(p=>label(p.person_id)).join(', ')]])))+panel('Використана програма',body(`<div class="reading-text">${esc(program?.snapshot.body_text||'Не зазначено')}</div>${program?`<small>Версія ${program.revision_no}</small>`:''}`))+'</aside></div>';
 }else if(section==='people'){
  const consents=writable(r.id,'consent.read')?t.consent_record.filter(x=>x.session_id===r.id):[];
  content=panel('Учасники',table(['Особа','Функція','Обов’язки / позначення','Дія'],people.map(p=>[esc(label(p.person_id)),esc(roles.find(x=>x[0]===p.role_code)?.[1]||p.role_code),esc([p.function_text,p.local_label].filter(Boolean).join(' · ')),btn('Редагувати','person-'+p.id,write)])),btn('Додати учасника','participant',write))+
   panel('Задокументовані згоди',table(['Особа','Стан','Дозволені способи','Дія'],consents.map(x=>[esc(label(x.person_id)),esc({active:'Задокументована',partially_withdrawn:'Частково відкликана',withdrawn:'Відкликана'}[x.state]||x.state),esc(t.consent_scope.filter(v=>v.consent_id===x.id&&v.permission==='allowed').map(v=>useNames[v.use_code]).join(', ')),button('Переглянути / відкликати',pg(25,{id:x.id}),true)])),btn('Задокументувати згоду','consent',people.length>0&&writable(r.id,'consent.write')));
 }else if(section==='events'){
  const events=t.session_event.filter(x=>x.session_id===r.id).sort((a,b)=>a.position-b.position);events.forEach(e=>{action('event-'+e.position,()=>eventForm(e));action('remove-event-'+e.position,()=>form('Вилучити подію',body(`<p>${esc(e.note)}</p>`),()=>command('field.session.event',{position:e.position,remove:true})));});
  content=panel('Час проведення',body(details([['Початок',r.started_at?new Date(r.started_at).toLocaleString('uk-UA'):null],['Завершення',r.ended_at?new Date(r.ended_at).toLocaleString('uk-UA'):null]])),btn('Уточнити час','timing',write))+panel('Перебіг сеансу',table(['Час','Подія','Учасник','Нотатка','Дії'],events.map(e=>[esc(e.occurred_at?new Date(e.occurred_at).toLocaleString('uk-UA'):'Не зазначено'),esc(eventKinds.find(x=>x[0]===e.kind)?.[1]),esc(e.participation_id?label(by('participation',e.participation_id).person_id):'—'),esc(e.note),btn('Редагувати','event-'+e.position,write)+' '+btn('Вилучити','remove-event-'+e.position,write)])),btn('Додати подію','event',write));
 }else if(section==='media'){
  const {importDialog,recordDialog}=sessionMediaDialogs(c,r,command),reps=sessionRepresentations(st,r.id),selected=reps.find(x=>x.id===params.get('media'));
  action('import',()=>importDialog());action('demo',()=>importDialog(true));['audio','video','photo'].forEach(k=>action('record-'+k,()=>recordDialog(k)));
  content=panel('Аудіо, відео та фото',table(['Матеріал','Тип','Тривалість','Позначки','Дія'],reps.map(rep=>{const layer=(t.timed_layer||[]).find(x=>x.representation_revision_id===rev(rep.id));return [esc(label(rep.asset_id)),esc(({audio:'Аудіо',video:'Відео',photo:'Фото'})[by('media_asset',rep.asset_id)?.media_kind]||'Медіа'),by('media_asset',rep.asset_id)?.media_kind==='photo'?'—':rep.duration_ms?(rep.duration_ms/1000)+' с':'Не визначена',String(layer?markerEntries(st,layer).length:0),button('Відкрити',pg(8,{id:r.id,section:'media',media:rep.id,q:params.get('q')||'',research:params.get('research')||r.research_id,role:params.get('role')||'R01'}),true)];})),btn('Додати медіафайл','import',writable(r.id,'capture.field'))+' '+btn('Записати аудіо','record-audio',writable(r.id,'capture.field'))+' '+btn('Записати відео','record-video',writable(r.id,'capture.field'))+' '+btn('Зробити фото','record-photo',writable(r.id,'capture.field'))+' '+btn('Додати навчальне аудіо','demo',writable(r.id,'capture.field')));
  if(selected){
   const files=t.representation_file.filter(x=>x.representation_id===selected.id),layer=(t.timed_layer||[]).find(x=>x.representation_revision_id===rev(selected.id)),entries=layer?markerEntries(st,layer):[];
   const marker=e=>{const seg=e&&by('entity_revision',e.segment_revision_id).snapshot;form(e?'Редагувати позначку':'Додати позначку',input('start','Від, секунд',seg?seg.start_ms/1000:0,'number',true)+input('end','До, секунд',seg?seg.end_ms/1000:Math.min(1,(selected.duration_ms||1000)/1000),'number',true)+input('text_value','Зміст фрагмента',e?.text_value,'textarea',true),fd=>command('field.session.marker',{representation_id:selected.id,representation_revision_id:rev(selected.id),layer_revision_id:layer?rev(layer.id):undefined,position:e?.position,start_ms:Math.round(Number(fd.get('start'))*1000),end_ms:Math.round(Number(fd.get('end'))*1000),text_value:fd.get('text_value')}));};action('marker',()=>marker());
   entries.forEach(e=>{action('marker-'+e.position,()=>marker(e));action('seek-'+e.position,()=>{const el=document.getElementById('session-player-0');if(el&&'currentTime'in el)el.currentTime=by('entity_revision',e.segment_revision_id).snapshot.start_ms/1000;});action('remove-marker-'+e.position,()=>form('Вилучити позначку',body(`<p>${esc(e.text_value)}</p>`),()=>command('field.session.marker',{representation_id:selected.id,representation_revision_id:rev(selected.id),layer_revision_id:rev(layer.id),position:e.position,remove:true})));});
   const renderFiles=files.map((rf,i)=>{const f=by('file_object',rf.file_id);action('download-'+f.id,()=>download(st.demo.file_contents[f.id],f.mime_type,f.original_filename));return mediaPreview(st.demo.file_contents[f.id],f.mime_type,esc,'session-player-'+i)+`<p>${esc(f.original_filename)} · ${Math.round(f.byte_size/1024)} КБ ${btn('Завантажити оригінал','download-'+f.id)}</p>`;}).join('');
   const capture=by('capture_event',selected.technical_metadata?.capture_event_id);
   content+=panel(label(selected.asset_id),body(renderFiles+(capture?`<details><summary>Відомості про запис</summary>${details([['Походження',capture.settings?.origin_note],['Пристрій',capture.device_model],['Зауваження',capture.technical_incidents]])}${button('Обставини фіксації',pg(35,{id:capture.id}),true)}</details>`:''))) +(by('media_asset',selected.asset_id)?.media_kind==='photo'?'':panel('Первинні часові позначки',table(['Фрагмент','Зміст','Дії'],entries.map(e=>{const seg=by('entity_revision',e.segment_revision_id).snapshot;return [(seg.start_ms/1000)+'–'+(seg.end_ms/1000)+' с',esc(e.text_value),btn('Перейти','seek-'+e.position)+' '+btn('Редагувати','marker-'+e.position,write)+' '+btn('Вилучити','remove-marker-'+e.position,write)];})),btn('Додати позначку','marker',write&&selected.duration_ms>0))+(layer?revisionHistory(layer.id):''));
  }
 }else if(section==='forms'){
  const docs=t.document_context.filter(x=>x.target_entity_id===r.id&&x.context_role==='session_form').map(x=>({context:x,doc:by('document',x.document_id)}));action('form',()=>save(command('field.session.form')));
  docs.forEach(({doc})=>{action('view-'+doc.id,()=>{const d=dialog(doc.title,body(`<pre class="reading-text" style="white-space:pre-wrap">${esc(doc.body_text)}</pre>`),null,'Закрити');d.querySelector('.cancel').hidden=true;});action('download-form-'+doc.id,()=>download(doc.body_text,'text/plain;charset=utf-8',doc.title+'.txt'));});
  content=panel('Бланки сеансу',table(['Бланк','Відповідність сеансу','Дії'],docs.slice().reverse().map(({context,doc})=>[esc(doc.title),context.target_revision_id===expected&&t.document_context.filter(x=>x.document_id===doc.id).every(x=>x.target_revision_id===rev(x.target_entity_id))?'Поточний':'Сеанс змінено після формування',btn('Переглянути','view-'+doc.id)+' '+btn('Завантажити','download-form-'+doc.id)])),btn('Сформувати бланк','form',write));
 }
 show(heading(r.research_id?label(r.research_id):'Польова робота',r.title,'',button('← Сеанси',pg(7,{research:params.get('research')||r.research_id,q:params.get('q')||'',role:params.get('role')||'R01'}),true))+`<div class="actions" style="margin-bottom:16px">${btn('Редагувати сеанс','edit',write)}${button('Польовий зошит',pg(9,{research:r.research_id,session:r.id}),true)}${btn('Підготувати передання','handover',writable(r.id,'intake.send'))}</div>`+`<nav class="record-tabs field-control" style="padding-right:42px" aria-label="Розділи сеансу">${sections.map(([key,title])=>`<a href="${url(key)}" ${section===key?'aria-current="page"':''}>${title}</a>`).join('')}${hint('Робота із сеансом','Уточніть обставини, учасників і згоди. Додавайте нотатки, події, аудіозаписи, відео та фото; позначайте зміст фрагментів без остаточної каталогізації. Файли до 2 МБ зберігаються лише в цьому браузері. Навчальне аудіо — синтетичний приклад. Після завершення сформуйте бланк і перейдіть до звірки та передання.')}</nav>`+content);
}
