import {mediaPreview} from './session-media.mjs?v=20261002-wf19';
import {processingPage} from './processing.mjs?v=20261002-wf19';
import {can,hash} from '../data/model.mjs?v=20261002-wf19';
import {textList,textView,textKinds,kindCode,useNames,useDecision} from '../data/workbench.mjs?v=20261002-wf19';
import {wizard} from './wizard.mjs?v=20261002-wf19';

export function workbenchPages(ctx){
 const {s,actor,scope,esc,pg,shell,heading,panel,dialog,dispatch,render,flash,denied}=ctx,st=s(),t=st.tables,p=new URLSearchParams(location.search),role=p.get('role')||'R02';
 const by=(k,id)=>t[k]?.find(x=>x.id===id),reg=id=>by('entity',id),rev=id=>reg(id)?.current_revision_id,label=id=>{const e=reg(id),x=e&&by(e.entity_type,id);return x?.title||x?.preferred_name||x?.name||(x?.asset_id?by('media_asset',x.asset_id)?.title:null)||'Матеріал';};
 const allowed=(permission,id)=>can(st,actor,permission,reg(id)?.archive_id)&&(!scope||scope===reg(id)?.archive_id),some=permission=>t.archive.some(a=>(!scope||scope===a.id)&&can(st,actor,permission,a.id));
 const btn=(title,key,enabled=true)=>`<button type="button" class="button secondary" data-workbench="${key}" ${enabled?'':'disabled'}>${esc(title)}</button>`,actions={},act=(k,f)=>actions[k]=f;
 const link=(n,title,q={})=>`<a href="${pg(n,{role,...q})}">${esc(title)}</a>`,go=(n,q={})=>location.assign(pg(n,{role,...q})),done=text=>{flash(text);render();};
 const body=h=>`<div class="panel-body">${h}</div>`,input=(name,title,value='',required=true,type='text')=>`<label>${esc(title)}<input type="${type}" name="${name}" value="${esc(value)}" ${required?'required':''}></label>`,area=(name,title,value='',required=true)=>`<label>${esc(title)}<textarea name="${name}" rows="5" ${required?'required':''}>${esc(value)}</textarea></label>`;
 const options=(rows,v='')=>rows.map(([id,title])=>`<option value="${esc(id)}" ${id===v?'selected':''}>${esc(title)}</option>`).join(''),select=(name,title,rows,v='')=>`<label>${esc(title)}<select name="${name}">${options(rows,v)}</select></label>`;
 const checks=(name,rows)=>rows.map(([id,title])=>`<label class="check-label"><input type="checkbox" name="${name}" value="${esc(id)}">${esc(title)}</label>`).join('');
 const details=rows=>`<dl class="detail-list">${rows.map(([k,v])=>`<div><dt>${esc(k)}</dt><dd class="source-text">${esc(v??'—')}</dd></div>`).join('')}</dl>`;
 const table=(heads,rows)=>rows.length?`<div class="table-wrap media-table"><table><thead><tr>${heads.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map((v,i)=>`<td data-label="${esc(heads[i])}">${v}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`:body('<p>Записів поки немає.</p>');
 const show=html=>{shell(html);document.querySelectorAll('[data-workbench]').forEach(b=>b.onclick=()=>actions[b.dataset.workbench]?.());};
 const sources=permission=>t.entity.filter(e=>['information_unit','document'].includes(e.entity_type)&&!e.retired_at&&allowed(permission,e.id));
 const title=x=>label(x.subject_entity_id)+' — '+textKinds[kindCode(st,x)],texts=()=>textList(st,actor).filter(x=>!scope||x.archive_id===scope),state=x=>x.reviewed?'Перевірено людиною':x.review?.decision==='reject'?'Потребує виправлення':x.review?.decision==='defer'?'Перевірку відкладено':'Очікує перевірки';
 const search=()=>`<form class="filters"><input type="hidden" name="role" value="${esc(role)}">${input('q','Пошук',p.get('q')||'',false)}<button class="button">Знайти</button></form>`;
 const filtered=rows=>rows.filter(x=>title(x).toLocaleLowerCase('uk').includes((p.get('q')||'').toLocaleLowerCase('uk')));
 const people=subject=>{const row=by(reg(subject)?.entity_type,subject),session=row?.session_id;return t.person.filter(x=>reg(x.id)?.archive_id===reg(subject)?.archive_id&&(!session||t.participation.some(v=>v.session_id===session&&v.person_id===x.id))).map(x=>[x.id,x.preferred_name]);};
 const speakerChoices=subject=>{const session=by('information_unit',subject)?.session_id;return [['','Не зазначено'],...t.participation.filter(x=>session&&x.session_id===session).map(x=>[x.id,(x.position||'')+'. '+label(x.person_id)])];};
 function createText(){const rows=sources('text.write');if(!rows.length)return;const d=wizard({dialog,esc},{title:'Створити транскрипцію',submit:'Зберегти текст',steps:[
  {title:'Джерело',body:select('subject_id','Матеріал',rows.map(x=>[x.id,label(x.id)]))+select('kind','Вид тексту',[['diplomatic','Дослівна транскрипція'],['notation','Нотна транскрипція']])+input('dialect','Говір або місцева назва','Говір не уточнено')+select('speaker_participation_id','Мовець',speakerChoices(rows[0].id))+select('notation_mode','Спосіб нотної транскрипції',[['grammatical','Граматична'],['phonetic','Фонетична']])},
  {title:'Текст і сумніви',body:area('body_text','Текст — кожна репліка з нового рядка')+area('note','Сумнівне прочитання','',false)}
 ],summary:v=>details([['Матеріал',label(v.subject_id)],['Вид',textKinds[v.kind]],['Текст',v.body_text],['Стан','Очікує людської перевірки']]),onSubmit:async v=>{const x=await dispatch({type:'workbench.text.create',...v,expected_revision_id:rev(v.subject_id)});go(12,{id:x.id});}});d.querySelector('[name=subject_id]').onchange=e=>d.querySelector('[name=speaker_participation_id]').innerHTML=options(speakerChoices(e.target.value));}
 function review(x,decision){dialog('Перевірка тексту',details([['Текст',x.body_text]])+area('reason','Обґрунтування рішення')+'<label class="check-label"><input type="checkbox" name="confirm" required>Я звірив цю версію з джерелом</label>',async fd=>{await dispatch({type:'workbench.text.review',id:x.id,expected_revision_id:x.revision_id,decision,reason:fd.get('reason'),confirm:fd.has('confirm')});done('Рішення збережено для цієї версії.');},decision==='accept'?'Підтвердити перевірку':decision==='reject'?'Повернути на виправлення':'Відкласти');}
 function edit(x){dialog('Редагувати текст',area('body_text','Текст — кожна репліка з нового рядка',x.body_text)+select('speaker_participation_id','Мовець',speakerChoices(x.subject_entity_id),x.parts[0]?.speaker_participation_id||'')+area('note','Сумнівне прочитання','',false)+area('reason','Причина зміни'),async fd=>{await dispatch({type:'workbench.text.edit',id:x.id,expected_revision_id:x.revision_id,...Object.fromEntries(fd)});done('Збережено нову версію. Її потрібно перевірити.');},'Зберегти нову версію');}
 function segment(x){const reps=t.representation.filter(r=>allowed('text.read',r.id)&&reg(r.id).archive_id===x.archive_id);dialog('Позначити фрагмент',select('representation_id','Медіапредставлення',reps.map(r=>[r.id,label(r.asset_id)+(r.duration_ms?' · '+r.duration_ms/1000+' с':' · тривалість не зазначено')]))+input('start','Початок, секунди','0',true,'number')+input('end','Кінець, секунди','10',true,'number'),async fd=>{await dispatch({type:'workbench.segment',text_id:x.id,expected_revision_id:x.revision_id,representation_id:fd.get('representation_id'),expected_representation_revision_id:rev(fd.get('representation_id')),start_ms:Number(fd.get('start'))*1000,end_ms:Number(fd.get('end'))*1000});done('Фрагмент пов’язано з інформаційною одиницею.');},'Зберегти фрагмент');}
 function transcription(){if(!some('text.read'))return denied();const x=p.get('id')?textView(st,actor,p.get('id')):null;if(p.get('id')&&(!x||scope&&scope!==x.archive_id))return denied();
  act('create',createText);if(!x)return show(heading('Опрацювання','Тексти','Відкрийте джерело або створіть транскрипцію. Редагування зберігає попередні версії.',btn('Створити транскрипцію','create',sources('text.write').length>0))+search()+panel('Тексти',table(['Матеріал','Вид','Стан'],filtered(texts()).map(x=>[link(12,label(x.subject_entity_id),{id:x.id}),esc(textKinds[kindCode(st,x)]),esc(state(x))]))));
  act('edit',()=>edit(x));act('segment',()=>segment(x));for(const d of ['accept','reject','defer'])act(d,()=>review(x,d));
  const src=by('entity_revision',x.subject_revision_id)?.snapshot,segs=t.unit_segment.filter(u=>u.unit_id===x.subject_entity_id).map(u=>by('media_segment',u.segment_id));
  const run=x.process_run_id&&by('process_run',x.process_run_id),sourceHTML=run?.job?`<p>${esc(label(x.subject_entity_id))} · ${link(40,'Результати обробки',{id:run.id})}</p>`+run.job.inputs.filter(f=>allowed('domain.read',f.id)).map(f=>`<details><summary>${esc(f.filename)}</summary>${st.demo.file_contents[f.id]?mediaPreview(st.demo.file_contents[f.id],f.mime_type,esc):'<pre>'+esc(by('entity_revision',f.revision_id)?.snapshot.body_text||'')+'</pre>'}</details>`).join(''):`<p class="source-text">${esc(src?.summary||src?.body_text||src?.title||label(x.subject_entity_id))}</p>`;
  show(link(12,'← Тексти')+heading('Транскрипція',label(x.subject_entity_id),'Один рядок — одна репліка. Сумніви зберігаються окремо й не перетворюються на остаточне прочитання.',btn('Редагувати текст','edit',allowed('text.write',x.id)))+
   body(`<nav class="record-tabs">${link(13,'Нормалізація та переклад',{id:x.id})}${link(14,'Версії та перевірка',{id:x.id})}${link(15,'Глосарій')}</nav>`+details([['Вид',textKinds[kindCode(st,x)]],['Стан',state(x)],['Версія',x.revision_no]]))+
   panel('Джерело',body(sourceHTML))+
   panel('Текст',table(['Репліка','Мовець','Текст'],x.parts.map(v=>[String(v.position),esc(v.speaker_participation_id?label(by('participation',v.speaker_participation_id)?.person_id):'Не зазначено'),esc(v.text)])))+
   panel('Сумнівні місця',body(x.notes.map(v=>`<p>${esc(v.body)}</p>`).join('')||'<p>Не позначено.</p>'))+
   (by('information_unit',x.subject_entity_id)?panel('Часові фрагменти',body(btn('Позначити фрагмент','segment',allowed('text.write',x.id)))+table(['Початок','Кінець'],segs.map(v=>[v.start_ms/1000+' с',v.end_ms/1000+' с']))):''));
 }
 function derive(x){const kind=kindCode(st,x)==='diplomatic'?'normalized':'translation';const glossary=t.glossary_entry.filter(g=>g.archive_id===x.archive_id);wizard({dialog,esc},{title:kind==='normalized'?'Нормалізувати текст':'Перекласти англійською',submit:'Зберегти окремий текст',steps:[
  {title:'Джерело і відповідність',body:details([['Вихідний текст',x.body_text],['Версія',x.revision_no]])+area('body_text','Новий текст — збережіть кількість рядків',kind==='normalized'?x.body_text:'')},
  {title:'Збережені форми й терміни',body:input('preserved_form','Навмисно збережена форма','',false)+input('preserved_reason','Чому її збережено','',false)+select('glossary_id','Використаний термін',[['','Без терміна'],...glossary.map(g=>[g.id,g.source_term+' — '+g.transliteration])])}
 ],summary:v=>details([['Вид',textKinds[kind]],['Новий текст',v.body_text],['Походження',kind==='translation'?'Переклад із нормалізованої української':'Нормалізація дослівної транскрипції']]),onSubmit:async v=>{const row=await dispatch({type:'workbench.text.derive',...v,source_text_id:x.id,expected_revision_id:x.revision_id,kind});go(13,{id:row.id});}});}
 function translation(){if(!some('text.read'))return denied();const x=p.get('id')?textView(st,actor,p.get('id')):null;if(p.get('id')&&(!x||scope&&scope!==x.archive_id))return denied();if(!x)return show(heading('Тексти','Нормалізація та переклад','Оберіть дослівний або нормалізований текст. Кожне похідне представлення має власні версії.')+search()+panel('Доступні тексти',table(['Матеріал','Вид','Стан'],filtered(texts()).map(x=>[link(13,label(x.subject_entity_id),{id:x.id}),esc(textKinds[kindCode(st,x)]),esc(state(x))]))));
  const code=kindCode(st,x),parent=x.derived_from_revision_id&&by('entity_revision',x.derived_from_revision_id);act('derive',()=>derive(x));
  const forms=t.preserved_dialect_form.filter(v=>v.target_text_revision_id===x.revision_id),uses=t.text_glossary_use.filter(v=>x.parts.some(part=>part.id===v.text_part_id));
  show(link(13,'← Нормалізація та переклад')+heading('Текст',title(x),'Вихідний текст зберігається. Для перекладу використовується конкретна версія нормалізованої української.',code==='diplomatic'||code==='normalized'?btn(code==='diplomatic'?'Створити нормалізацію':'Створити переклад','derive',allowed('text.write',x.id)):'')+
   body(link(12,'Відкрити текст',{id:x.id})+' · '+link(14,'Версії та перевірка',{id:x.id})+' · '+link(15,'Глосарій')+details([['Стан',state(x)],['Мова',x.language_tag],['Вихідна версія',parent?.revision_no||'Дослівне джерело']]))+
   panel('Паралельний текст',table(['Джерело','Поточний текст'],x.parts.map(part=>{const alignment=t.text_alignment.find(v=>v.target_part_id===part.id);return [esc(by('text_part',alignment?.source_part_id)?.text||'—'),esc(part.text)];})))+
   panel('Навмисно збережені форми',table(['Форма','Пояснення'],forms.map(v=>[esc(v.retained_form),esc(v.reason)])))+
   panel('Використані пояснення',table(['Термін','Форма','Пояснення'],uses.map(v=>[esc(v.source_term_snapshot),esc(v.rendered_form),esc(v.explanation_snapshot)])))+
   panel('Похідні тексти',table(['Текст','Стан'],texts().filter(v=>by('entity_revision',v.derived_from_revision_id)?.entity_id===x.id).map(v=>[link(13,textKinds[kindCode(st,v)],{id:v.id}),esc(state(v))]))));
 }
 function versions(){if(!some('text.read'))return denied();const x=p.get('id')?textView(st,actor,p.get('id')):null;if(p.get('id')&&(!x||scope&&scope!==x.archive_id))return denied();if(!x)return show(heading('Перевірка','Версії текстів','Оберіть текст для порівняння та людської перевірки.')+panel('Тексти',table(['Матеріал','Вид','Стан'],texts().map(x=>[link(14,label(x.subject_entity_id),{id:x.id}),esc(textKinds[kindCode(st,x)]),esc(state(x))]))));
  const history=t.entity_revision.filter(v=>v.entity_id===x.id),old=textView(st,actor,x.id,p.get('before')||history[0].id),next=textView(st,actor,x.id,p.get('after')||x.revision_id);if(!old||!next)return denied();for(const d of ['accept','reject','defer'])act(d,()=>review(x,d));
  const decisions=t.review_decision.filter(v=>v.target_entity_id===x.id);show(link(12,'← До тексту',{id:x.id})+heading('Перевірка',title(x),'Рішення стосується точної версії. Після редагування новий текст знову потребує перевірки.',allowed('text.review',x.id)?`<div class="public-actions">${btn('Підтвердити текст','accept')}${btn('Повернути на виправлення','reject')}${btn('Відкласти','defer')}</div>`:'')+
   body(details([['Поточна версія',x.revision_no],['Стан',state(x)]]))+`<form class="filters"><input type="hidden" name="role" value="${esc(role)}"><input type="hidden" name="id" value="${x.id}">${select('before','Ліва версія',history.map(v=>[v.id,'Версія '+v.revision_no]),old.revision_id)}${select('after','Права версія',history.map(v=>[v.id,'Версія '+v.revision_no]),next.revision_id)}<button class="button">Порівняти</button></form>`+
   panel('Порівняння рядків',table(['Ліва версія','Права версія','Зміна'],Array.from({length:Math.max(old.parts.length,next.parts.length)},(_,i)=>[esc(old.parts[i]?.text||'—'),esc(next.parts[i]?.text||'—'),old.parts[i]?.text===next.parts[i]?.text?'Без змін':'Змінено'])))+
   panel('Походження версій',table(['Версія','Автор','Причина'],history.map(v=>[String(v.revision_no),esc(label(by('account',v.actor_account_id)?.person_id)),esc(v.change_reason)])))+
   panel('Рішення перевірки',table(['Версія','Рішення','Обґрунтування'],decisions.map(v=>[String(by('entity_revision',v.target_revision_id)?.revision_no),esc({accept:'Підтверджено',reject:'Повернуто',defer:'Відкладено'}[v.decision]),esc(v.reason)]))));
 }
 async function glossaryForm(g=null){const a=g?.archive_id||scope||t.archive.find(a=>can(st,actor,'text.write',a.id))?.id,expected=g?await hash(g):null;dialog(g?'Редагувати термін':'Додати термін',input('source_term','Український термін',g?.source_term)+input('transliteration','Транслітерація',g?.transliteration)+area('explanation','Пояснення',g?.explanation)+input('accepted_equivalent','Прийнятий відповідник',g?.accepted_equivalent||'',false),async fd=>{await dispatch({type:'workbench.glossary.save',...Object.fromEntries(fd),id:g?.id,archive_id:a,expected_hash:expected});done('Термін збережено. Раніше створені тексти зберігають свої пояснення.');},'Зберегти термін');}
 function glossary(){if(!some('text.read'))return denied();const q=(p.get('q')||'').toLowerCase(),rows=t.glossary_entry.filter(g=>can(st,actor,'text.read',g.archive_id)&&(!scope||scope===g.archive_id)&&[g.source_term,g.transliteration,g.explanation].join(' ').toLowerCase().includes(q));act('add',()=>glossaryForm());rows.forEach(g=>act('edit-'+g.id,()=>glossaryForm(g)));show(heading('Переклад','Робочий глосарій','Зміна пояснення тут не переписує вже використане пояснення у старих перекладах.',btn('Додати термін','add',some('text.write')))+search()+panel('Терміни',table(['Термін','Транслітерація','Пояснення','Відповідник','Дія'],rows.map(g=>[esc(g.source_term),esc(g.transliteration),esc(g.explanation),esc(g.accepted_equivalent||'Не визначено'),btn('Редагувати','edit-'+g.id,can(st,actor,'text.write',g.archive_id))]))));}
 const consentState={active:'Чинна',partially_withdrawn:'Частково відкликана',withdrawn:'Відкликана',superseded:'Замінена'};
 function consentForm(){const rows=sources('consent.write');if(!rows.length)return;const d=wizard({dialog,esc},{title:'Задокументувати згоду',submit:'Зберегти згоду',steps:[
  {title:'Учасник і матеріал',body:select('subject_id','Матеріал',rows.map(x=>[x.id,label(x.id)]))+select('person_id','Учасник',people(rows[0].id))+input('effective_at','Дата набуття чинності',st.clock.slice(0,10),true,'date')},
  {title:'Обсяг і підстава',body:select('purpose_code','Для кого дозволено перегляд і цитування',[['public','Публічне використання'],['research','Дослідницька робота']])+checks('uses',Object.entries(useNames))+area('terms','Умови згоди')+input('locator','Де збережено доказ','',false)+area('evidence_note','Приватний опис доказу')}
 ],summary:v=>details([['Учасник',label(v.person_id)],['Матеріал',label(v.subject_id)],['Дозволено',v.uses.map(u=>useNames[u]).join(', ')],['Умови',v.terms],['Результат','Згоду буде зафіксовано. Рішення про доступ ухвалюється окремо.']]),onSubmit:async v=>{const x=await dispatch({type:'workbench.consent.create',...v,expected_revision_id:rev(v.subject_id)});go(25,{id:x.id});}});d.querySelector('[name=subject_id]').onchange=e=>d.querySelector('[name=person_id]').innerHTML=options(people(e.target.value));}
 function consents(){if(!some('consent.read'))return denied();const rows=t.consent_record.filter(x=>allowed('consent.read',x.id)),x=rows.find(x=>x.id===p.get('id'));if(p.get('id')&&!x)return denied();act('add',consentForm);if(!x)return show(heading('Згоди','Згоди та умови','Доказ згоди приватний. Згода не публікує матеріал і не замінює рішення про доступ.',btn('Задокументувати згоду','add',sources('consent.write').length>0))+panel('Згоди',table(['Учасник','Умови','Стан'],rows.map(x=>[link(25,label(x.person_id),{id:x.id}),esc(x.terms_text),esc(consentState[x.state])]))));
  const scopes=t.consent_scope.filter(v=>v.consent_id===x.id),evidence=t.evidence_link.filter(v=>v.subject_entity_id===x.id&&v.evidence_role==='consent').map(v=>by('evidence',v.evidence_id));
  act('withdraw',()=>dialog('Відкликати згоду',select('use','Обсяг відкликання',[['all','Усі дозволи'],...scopes.filter(v=>v.permission==='allowed').map(v=>[v.use_code,useNames[v.use_code]])])+area('reason','Причина відкликання'),async fd=>{await dispatch({type:'workbench.consent.withdraw',id:x.id,expected_revision_id:rev(x.id),...Object.fromEntries(fd)});done('Відкликання збережено. Залежні рішення потребують перегляду.');},'Відкликати'));
  show(link(25,'← Згоди')+heading('Згода',label(x.person_id),'Часткове відкликання створює нову версію. Попередні умови та доказ залишаються в історії.',btn('Відкликати згоду','withdraw',allowed('consent.write',x.id)&&['active','partially_withdrawn'].includes(x.state)))+
   body(details([['Стан',consentState[x.state]],['Умови',x.terms_text],['Чинна з',x.effective_at]]))+panel('Обсяг',table(['Матеріал','Призначення','Використання','Дозвіл'],scopes.map(v=>[esc(label(v.target_entity_id)),esc(v.purpose_code==='research'?'Дослідницька робота':v.purpose_code==='public'?'Публічне використання':v.purpose_code),esc(useNames[v.use_code]),v.permission==='allowed'?'Дозволено':'Відкликано'])))+
   panel('Приватний доказ',body(evidence.map(v=>details([['Місце доказу',v.locator],['Опис',v.note]])).join('')))+
   panel('Історія умов',table(['Версія','Стан','Обсяг','Підстава зміни'],t.entity_revision.filter(v=>v.entity_id===x.id).map(v=>[String(v.revision_no),esc(consentState[v.snapshot.state]),esc((v.snapshot._relations?.consent_scope||[]).map(u=>useNames[u.use_code]+': '+(u.permission==='allowed'?'дозволено':'відкликано')).join('; ')),esc(v.change_reason)]))));
 }
 function processing(){return processingPage({st,t,p,actor,scope,esc,pg,dialog,dispatch,done,denied,by,reg,rev,allowed,some,btn,act,link,go,body,input,area,options,select,checks,details,table,show,heading,panel});}
 const depositStates={prepared:'Підготовлено',sent:'Надіслано',received:'Отримано',accepted:'Прийнято',rejected:'Відхилено'};
 function depositForm(action='upsert',existing=null){const a=existing?.archive_id||scope||t.archive.find(a=>can(st,actor,'deposit.manage',a.id))?.id;const rows=sources('deposit.manage').filter(e=>reg(e.id).archive_id===a&&(action==='withdraw'?t.deposit_item.some(i=>i.source_entity_uuid===e.id&&i.action==='upsert'&&['sent','accepted'].includes(by('deposit_record',i.deposit_record_id)?.state)):useDecision(st,e.id,'deposit','deposit')));const receivers=t.installation.filter(x=>x.id!==st.demo.ids.installation);wizard({dialog,esc},{title:action==='withdraw'?'Підготувати вилучення':'Підготувати депонування',submit:'Зберегти пакет',steps:[
  {title:'Приймач і склад',body:select('receiver_id','Приймальна інсталяція',receivers.map(x=>[x.id,x.name]),existing?.receiver_installation_id)+checks('source_ids',rows.map(e=>[e.id,label(e.id)]))}
 ],summary:v=>details([['Матеріали',v.source_ids.map(label).join(', ')],['Дія',action==='withdraw'?'Передати вимогу вилучити':'Передати дозволений опис'],['Підстава','Докази згод, контакти, фізичний інвентар і чернетки не передаються.']]),onSubmit:async v=>{const x=await dispatch({type:'workbench.deposit.prepare',...v,archive_id:a,action,source_revisions:Object.fromEntries(v.source_ids.map(id=>[id,rev(id)]))});go(30,{id:x.id});}});}
 function deposits(){if(!some('deposit.manage'))return denied();act('prepare',()=>depositForm());act('withdraw',()=>depositForm('withdraw'));const rows=t.deposit_record.filter(x=>allowed('deposit.manage',x.id));show(heading('Передання','Депонування','Передаються тільки дозволені описи. Приймання не публікує матеріал. Мережеве передання тут відтворюється локально.',btn('Підготувати пакет','prepare')+btn('Підготувати вилучення','withdraw'))+
  panel('Пакети',table(['Пакет','Приймач','Матеріалів','Стан'],rows.map((x,i)=>[link(30,'Пакет '+(i+1),{id:x.id}),esc(by('installation',x.receiver_installation_id)?.name),String(t.deposit_item.filter(v=>v.deposit_record_id===x.id).length),esc(depositStates[x.state])]))));}
 function deposit(){if(!p.get('id'))return deposits();const x=by('deposit_record',p.get('id'));if(!x||!allowed('deposit.manage',x.id))return denied();const items=t.deposit_item.filter(v=>v.deposit_record_id===x.id);act('send',()=>dialog('Схвалити та надіслати приклад',area('reason','Підстава передання')+'<p>Надсилання виконується лише в локальному прикладі.</p><label class="check-label"><input type="checkbox" name="confirm" required>Я перевірив склад і дозволи на передання</label>',async fd=>{await dispatch({type:'workbench.deposit.send',id:x.id,expected_revision_id:rev(x.id),reason:fd.get('reason'),confirm:fd.has('confirm')});done('Пакет схвалено й надіслано у прикладі.');},'Надіслати приклад'));
  act('receive',()=>dialog('Перевірити приймання у прикладі',select('outcome','Рішення приймача',[['accepted','Прийняти'],['rejected','Відхилити']])+area('reason','Коментар приймача','Пакет перевірено.'),async fd=>{await dispatch({type:'workbench.deposit.receive',id:x.id,expected_revision_id:rev(x.id),reject:fd.get('outcome')==='rejected',reason:fd.get('reason')});done('Відповідь приймача збережено.');},'Зберегти відповідь'));act('withdraw',()=>depositForm('withdraw',x));
  show(link(29,'← Депонування')+heading('Пакет','Дозволені описи для передання','Склад зафіксовано. Після зміни опису чи прав підготуйте новий пакет. Повторне приймання не дублює результат.',`<div class="public-actions">${btn(x.state==='rejected'?'Повторити надсилання':'Схвалити й надіслати','send',['prepared','rejected'].includes(x.state))}${btn('Перевірити приймання','receive',x.state==='sent')}${btn('Підготувати вилучення','withdraw',['sent','accepted'].includes(x.state))}</div>`)+
   body(details([['Стан',depositStates[x.state]],['Приймач',by('installation',x.receiver_installation_id)?.name],['Публікація','Не виконується під час депонування']]))+
   panel('Зафіксований склад',table(['Матеріал','Дія','Версія передання','Дозволений опис'],items.map(v=>[esc(label(v.source_entity_uuid)),v.action==='withdraw'?'Вилучити':'Оновити',String(v.source_transfer_version),esc(v.exported_payload?.summary||'Опис не передається')])) )+
   panel('Відповідь приймача',x.acknowledgement?body(`<p>${esc(x.acknowledgement.reason||'Пакет перевірено у локальному прикладі.')}</p>`)+table(['Матеріал','Результат'],(x.acknowledgement.items||[]).map(v=>[esc(label(v.source)),esc({accepted:'Прийнято',withdrawn:'Вилучено з отриманого набору',ignored_old_version:'Пропущено застарілу версію'}[v.result])])):body('<p>Відповідь ще не отримано.</p>'))+
   panel('Історія пакета',table(['Версія','Стан','Причина'],t.entity_revision.filter(v=>v.entity_id===x.id).map(v=>[String(v.revision_no),esc(depositStates[v.snapshot.state]),esc(v.change_reason)]))));
 }
 return {'PG-12':transcription,'PG-13':translation,'PG-14':versions,'PG-15':glossary,'PG-25':consents,'PG-29':deposits,'PG-30':deposit,'PG-40':processing};
}
